### ISSUE TITLE
[Feature Request] Add support for sql

### ISSUE THREAD

**Issue by letientai299** [andymass/vim-matchup#1]
Please (or how do I) add support for SQL keyword language: 

- BEGIN/END.
- CASE/WHEN/THEN/ELSE

**Comment by andymass** [comment]
This appears to work already.  Do you have an example which doesn't work properly?

**Comment by letientai299** [comment]
Confirm that this work out of the box for `*.sql` files. I got trouble due to this line in `$MYVIMRC`

```viml
au BufEnter *.sql set ft=pgsql
```
Change it to

```viml
let g:sql_type_default = 'pgsql'
```

make matchup works again.
