### ISSUE TITLE
b:matchup_matchparen_fallback = 1 not working

### ISSUE THREAD

**Issue by beardedsakimonkey** [andymass/vim-matchup#101]
### Explain the issue

When settings `b:matchup_matchparen_enabled = 0`, I'd expect matching brackets/brackes/parentheses to still be highlighted when putting the cursor on one.  But this isn't the case for me.  The issue seemt to be in finding the script number for matchparen.vim:
https://github.com/andymass/vim-matchup/blob/24c17f94e0db86b155f1b775c3204a6829be5ee9/autoload/matchup/matchparen.vim#L73
For me, `echo expand('$VIM')` outputs `/Users/tim/local/nvim/share/nvim`.  However, running `:scriptnames` shows paths beginning with a tilde. E.g. `18: ~/local/nvim/share/nvim/runtime/plugin/matchparen.vim`.
To confirm that this is the issue, making the following change seems to restore the usual matchparen higlighting:
```diff
- let l:pat = '\%#=1\V'.expand('$VIM').'\m.\+matchparen\.vim$'
+ let l:pat = '\%#=1\V'.fnamemodify(expand('$VIM'), ':~').'\m.\+matchparen\.vim$'
```

1. What vim version are you using? NVIM v0.5.0-nightly-48-g7b529e791
2. Steps to reproduce
put this in vimrc:
```
autocmd FileType vim let b:matchup_matchparen_enabled = 0 | let b:matchup_matchparen_fallback = 1
```

3. Expected behavior
open a vim file and observe that matching braces/brackets/parentheses are highlighted as they normally are by vim's matchparen plugin.
4. Observed behavior
open a vim file and observe that matching braces/brackets/parentheses are not highlighted.

### Minimal working example

Please provide a minimal working example, e.g.,

```vim
fun T(...)
endf
```

### Minimal vimrc file
```vim
set nocompatible

" load match-up
let &rtp  = '~/.vim/bundle/vim-matchup,' . &rtp
let &rtp .= ',~/.vim/bundle/vim-matchup/after'

filetype plugin indent on
syntax enable

" match-up options go here
autocmd FileType vim let b:matchup_matchparen_enabled = 0 | let b:matchup_matchparen_fallback = 1
```

**Comment by andymass** [comment]
Thank you for very the detailed report and fix!  Let me know if it works.

**Comment by beardedsakimonkey** [comment]
it seems to be working well, thanks for the quick fix!
