### ISSUE TITLE
matchup does not match dollar sign for in-line equations in tex files

### ISSUE THREAD

**Issue by aviator24** [andymass/vim-matchup#102]
### Explain the issue

Hitting % at one of the $ pair does not move the cursor to the matching $.

In the below minimal working exmaple, e.g., the cursor jumps over matching delimiter for `\left( \right)` and `{ }`, but not for `$ $`.

version : vim 8.1

### Minimal working example

Please provide a minimal working example, e.g.,

```vim
$\left( \frac{1}{2} \right) = 0$
```

### Minimal vimrc file

Please provide a minimal vimrc file that reproduces the issue. The
following should often suffice:

```vim
set nocompatible

" load match-up
let &rtp  = '~/.vim/bundle/vim-matchup,' . &rtp
let &rtp .= ',~/.vim/bundle/vim-matchup/after'

filetype plugin indent on
syntax enable
```

**Comment by andymass** [comment]
Do you use any other latex plugin generally?

**Comment by aviator24** [comment]
Yes, I use vimtex; the issue appears when I use
`let g:matchup_override_vimtex = 1`
