### ISSUE TITLE
JSX with inner . separator doesn't match closing tag

### ISSUE THREAD

**Issue by andrewplummer** [andymass/vim-matchup#103]
With the following JSX:

```
<Layout>
  <Layout.Group horizontal center spread>
  </Layout.Group>
</Layout>
```

The `%` key will not jump to (or highlight) the closing tag for `<Layout>`.
I'm using this with the `maxmellon/vim-jsx-pretty`, unsure which is responsible for the issue.

Platform: OSX 10.15.6
Version: MacVim 8.2.539

**Comment by andymass** [comment]
This is an interesting one.  vim-jsx-pretty uses a [b:match_words](https://github.com/MaxMEllon/vim-jsx-pretty/blob/c665d5ca4247b696f478f91b7c97b9e44442e4b6/after/ftplugin/javascript.vim#L20) which is subtly broken..

vim-jsx-pretty: `<\@<=\([^/][^ \t>]*\)\g{hlend}[^>]*\%(/\@<!>\|$\):<\@<=/\1>`

match-up's html: `<\@<=\([^/][^ \t>]*\)\g{hlend}\%(>\|$\|[ \t][^>]*\%(>\|$\)\):<\@<=/\1\g{hlend}>`

**Comment by andrewplummer** [comment]
Works great! Thank you!
