### ISSUE TITLE
Support HTML Tag Matching in *.vue Files

### ISSUE THREAD

**Issue by theSdev** [andymass/vim-matchup#106]
**Is your feature request related to a problem? Please describe.**
HTML tag matching does not work in *.vue files

**Describe the solution you'd like**
I think HTML tag matching should work regardless of file type. Otherwise having a way to alias *.vue to act as *.html would be nice too.

**Describe alternatives you've considered**
None

**Additional context**
*.vue files consist of three main parts, one of which is `<template>` for writing HTML.

**Comment by andymass** [comment]
Seems to work with the plugin https://github.com/posva/vim-vue

What plugin, if any, are you using for vue syntax highighting?

**Comment by theSdev** [comment]
I only use Coc Vetur<https://github.com/neoclide/coc-vetur> for Vue.

________________________________
Von: Andy Massimino <notifications@github.com>
Gesendet: Samstag, 5. September 2020, 18:18
An: andymass/vim-matchup
Cc: Samir Saeedi; Author
Betreff: Re: [andymass/vim-matchup] Support HTML Tag Matching in *.vue Files (#106)


Seems to work with the plugin https://github.com/posva/vim-vue

What plugin, if any, are you using for vue syntax highighting?

**Comment by andymass** [comment]
Sorry, I'm still a bit confused.  Does coc-vetur/coc.nvim provide syntax highlighting for vue files?

**Comment by x-ji** [comment]
I can confirm that with https://github.com/posva/vim-vue the matching seems to work in .vue files.

**Comment by jakubreron** [comment]
Any updates on this issue?
As @x-ji mentioned, installing https://github.com/posva/vim-vue fixes the bug, but it would be really great to have it resolved natively in `vim-matchup`

**Comment by andymass** [comment]
Vue is supported without any extra plugin now in modern versions of vim.

If you're using an old version of vim, you can create a file 

`.vim/after/ftplugin/vue.vim` or `.vim/ftplugin/vue.vim` containing:

    let b:match_words = matchup#util#standard_html()
