### ISSUE TITLE
Introduce function to return value of `MatchupWhereAmI` for usage in statusline

### ISSUE THREAD

**Issue by kristijanhusak** [andymass/vim-matchup#109]
**Is your feature request related to a problem? Please describe.**
More of a nice to have.

**Describe the solution you'd like**
A function that returns what `:MatchupWhereAmI` echoes. I guess the call is potentially expensive, so some debounce should also be introduced, to prevent constant recalculation.

**Describe alternatives you've considered**
[tagbar](https://github.com/preservim/tagbar) has a function that prints something like this, but it's not too detailed. Here's link to docs https://github.com/preservim/tagbar/blob/master/doc/tagbar.txt#L1068

**Comment by andymass** [comment]
Just curious what the use case will be.  MatchupWhereAmI smartly echos colors, but we can't return colors in a string.
How do you think you'll use the output?

**Comment by kristijanhusak** [comment]
I thought of using it in statusline. Colors wouldn't matter much. But now when I think about it, statusline just doesn't have enough space to show this, especially when checking some nested code.
Thanks for your help. Closing.
