### ISSUE TITLE
Disable built-in pi_paren plugin

### ISSUE THREAD

**Issue by kevinhwang91** [andymass/vim-matchup#110]
**Is your feature request related to a problem? Please describe.**

pi_paren always highlight terminal buffer, I don't want the MatchParen group to highlight in the buffer.
The below snippet doesn't disable highlight in terminal buffer:

```vim
let g:loaded_matchparen = 1
augroup MatchupMatch
    autocmd!
    autocmd TermOpen * let b:matchup_matchparen_enabled = 0
augroup END
```

I have no idea why matchup must active `matchparen.vim` and deactive it again.
https://github.com/andymass/vim-matchup/blob/5a7dd99621cd40466567afb35999700acc7f0f49/plugin/matchup.vim#L32-L41

**Describe the solution you'd like**
Skip loading `matchparen.vim` when `g:loaded_matchparen=1`.

**Comment by andymass** [comment]
does

     autocmd TermOpen * let [b:matchup_matchparen_enabled, b:matchup_matchparen_fallback] = [0, 0]

work as a work-around?

**Comment by kevinhwang91** [comment]
Yes, it works, please forgive me for not reading the document carefully.
