### ISSUE TITLE
Matchup not working for conditional statement in Fortran77

### ISSUE THREAD

**Issue by iwijaya2** [andymass/vim-matchup#111]
### Explain the issue

1. What vim version are you using?
nvim v0.4.4

2. Steps to reproduce
Install vim-matchup and use it inside Frotran77 files.

3. Expected behavior
Conditional keywords like `if` and `endif` are highlighted

4. Observed behavior
They are not highlighted. However, keywords for loop are highlighted just fine.

### Minimal working example

A minimal working example:

```Fortran
      program test
      
      implicit none
      integer i 
      real*8  temp

C   Loop statement
      do i=1,3
        temp = temp + 1
      enddo

C   Conditional statement
      if (temp.eq.3) then
        temp = temp - 1
      endif

      end program
```

### Observation
1. if I use `end if` instead of `endif`, the whole line `if (temp.eq.3) then`  will be highlighted. However, this is not consistent with the highlight for loop statement as only `do` and `enddo` are highlighted, not the whole line.
2. If I remove the following line from `after/ftplugin/fortran_matchup.vim`, the whole line `if (temp.eq.3) then`  will be highlighted.
```vim
call matchup#util#patch_match_words('\<end\s*if', '\<end\>\s*if')
```
So I can remove that line and get the highlight, but i get different behaviour for loop and conditional statement.

**Comment by andymass** [comment]
Could you see if the latest update fixes it?

**Comment by iwijaya2** [comment]
Yes, that fixed it. Thank you so much!

**Comment by iwijaya2** [comment]
Sorry, I just realized that for `if`-`endif` pair, the highlight was as expected but if we have `elseif`, it will still highlight the whole line. Is it possible to only highlight the keyword `elseif` instead of the whole line?

Small working example:
``` fortran
      program test
      
      implicit none
      real*8  temp

C   Conditional statement
      if (temp.eq.3) then
        temp = temp - 1
      elseif (temp.eq.4) then
        temp = temp - 1
      endif

      end program
```
