### ISSUE TITLE
Buggy interaction with lightline plugin

### ISSUE THREAD

**Issue by Aster89** [andymass/vim-matchup#113]
### Explain the issue
1. What vim version are you using? `VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 17 2020 21:54:53)`
2. to 4. When the matching line is out of screen (on either side), it is show superimposed on the status line. See the screencast below:
[![asciicast](https://asciinema.org/a/yDNv6mKQKO57FuwFY8GcCzY2I.svg)](https://asciinema.org/a/yDNv6mKQKO57FuwFY8GcCzY2I)

### Minimal working example
The vimrc below is ok.

### Minimal vimrc file
```vim
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  au VimEnter * PlugInstall --sync | source $MYVIMRC
endif
call plug#begin('~/.vim/plugged')
set nocompatible " to use Vim, not just vi
Plug 'itchyny/lightline.vim'
Plug 'andymass/vim-matchup'
call plug#end()

set noshowmode
set laststatus=2
```

**Comment by andymass** [comment]
This is working as expected.. it's a feature which you the match you can't see since it's above the screen  :smile: .

You may prefer popup style though;

    let g:matchup_matchparen_offscreen={'method': 'popup'}

**Comment by Aster89** [comment]
Sorry for not reading the docs :disappointed:
