### ISSUE TITLE
No highlightning for "$"

### ISSUE THREAD

**Issue by phmarek** [andymass/vim-matchup#114]
### Issue

When moving around in my sources, I get the matching paren highlighted.

But it doesn't work when moving to the end of the line and landing on a paren:

nvim v0.5.0-593-g1ca67a73c

### Minimal working example

```
  (abc
     (def
  x      ghi)))
```

With the cursor at `x` and pressing `$` I get to the last `)`, but the matching `(` isn't highlighted.

Thanks a lot!

**Comment by andymass** [comment]
Sorry, can you clarify the example?  There are two open `(` but three close `)` isn't that expected?  The other two do match.

**Comment by phmarek** [comment]
Ah sorry, that was a typo for that example. The `ghi` should also have a paren at the start:

```
(abc
   (def
  x   (ghi)))
```
