### ISSUE TITLE
Matchup brings coc-emmet to leave me inside tags instead of between them

### ISSUE THREAD

**Issue by void-m4110c** [andymass/vim-matchup#117]
### Explain the issue

Next to vim-matchup I have coc-emmet installed, which provides snippets for HTML tags.
When I type `li` I get an autocompletion popup and can select `<li>|</li>` from emmet snippets.

However, when I accept the selection my cursor `_` is left in this position: `<l_i></li>` . 
(Inside the first tag element between l and i, instead of in between the two tag elements)

If I disable vim-matchup the problem disappears. 

1. What vim version are you using?
neovim 0.5
2. Steps to reproduce
see above.

3. Expected behavior
My cursor `_` lands in this position:  `<li>_</li>`

4. Observed behavior
My cursor `_` lands in this position:  `<l_i></li>`

Thanks!

**Comment by andymass** [comment]
I don't have coc.nvim installed so it is a bit difficult for me to debug but here are a couple things to try:

1. Does the situation change with deferred matching?

    let g:matchup_matchparen_deferred = 1

2. Does this additional plugin have any effect whatsoever?

    https://github.com/antoinemadec/FixCursorHold.nvim

**Comment by void-m4110c** [comment]
@andymass You solved it, The ` let g:matchup_matchparen_deferred = 1` solved the issue.

Thank you very much! :-)
