### ISSUE TITLE
Incorrect match end in XML

### ISSUE THREAD

**Issue by phmarek** [andymass/vim-matchup#119]
### Explain the issue

With XML tags, `/` is seen as end-of-tag - but quoting isn't taken into account correctly.

IMO the background should be until `/>`.

### Minimal working example

```
<test id='file' value='bar/foo'/>
```

![xml](https://user-images.githubusercontent.com/496570/100894144-15d57380-34b4-11eb-8dee-a858e5ea5c80.png)

**Comment by andymass** [comment]
I think this was fixed at some point (seems to work now).  Please re-open if there are any issues.
