### ISSUE TITLE
Minor doc issue: there is no help tag *any*-block

### ISSUE THREAD

**Issue by kiryph** [andymass/vim-matchup#12]
You refer to `*any*` in
```
                                                         *v_a%* *a%*
a%                      select an |any| block.
                        This closely matches match vim's built-in |ab|.
```
and
```
i%                      select the inside of an |any| block.
                        This closely matches match vim's built-in |ib|.
                        See also |matchup-feat-linewise|.
```
However, there is no help tag `*any*` specified. Pressing `<C-]>` jumps to `*tag-any-white*` which is not helpful.

I suppose that you refer to following sentence in `*matchup-features*`:

> The if/endif pair is called an "open-to-close" block and the if/else, else/elsif, and elseif/endif are called "any" blocks.

BTW: Since you call your plugin 'match-up' with a hyphen, I guess you want to rename in README.md:
```diff
diff --git a/README.md b/README.md
index 7fa243d..f3effd6 100644
--- a/README.md
+++ b/README.md
@@ -365,7 +365,7 @@ default: 0

 ### Variables

-matchup understands the following variables from matchit.
+match-up understands the following variables from matchit.
 - `b:match_words`
 - `b:match_skip`
 - `b:match_ignorecase`
```
I am not a big fan of using in ordinary text `match-up` and as a repository name, variable-, and help tag-prefix `matchup`. However, it apparently is done consistently, I never wonder whether I should use a hyphen or not.

**Comment by andymass** [comment]
Thanks, good catch!

And yes, "match-up" is the correctly styled name for the plugin in documentation, but a hyphen would clearly cause troubles in vim variable names.  I decided to be consistent among tags and variables, but now I suppose tags could have hyphens, so I may re-think this..  For the repository name, I think "vim-match-up" is ugly and sounds wrong, so I went with "vim-matchup" and I will keep for now.
