### ISSUE TITLE
Recent commits has error in call to searchpos

### ISSUE THREAD

**Issue by lervag** [andymass/vim-matchup#122]
https://github.com/andymass/vim-matchup/blob/ac1d0f73a0eee3d2597f09789d45d9d332c64be5/autoload/matchup/delim.vim#L734-L735

The `searchpos` function has a different signature than the `searchpairpos` function, in particular it has fewer arguments. It seems there is a small bug in the above referenced code introduced in commit f1e67168745573ce4fd3ef939b874e6d66a7b1b4 as a result of #102.

I think the fix might be to simply remove the last `l:skip`?

**Comment by andymass** [comment]
Ah.. one of those unfortunate deltas between neovim and vim.  Sorry about that.  I'll probably have to add a wrapper function which emulates the skip expression.

Thank you for the report! :smiley:

**Comment by lervag** [comment]
No problem! And, of course, I should have checked Vim vs neovim difference. :stuck_out_tongue: 

I'm not really looking forward to the time when Vim and neovim are so far apart that I have to make an actual choice...
