### ISSUE TITLE
Vimtex v2 breaks motions for inline math

### ISSUE THREAD

**Issue by lervag** [andymass/vim-matchup#123]
In Vimtex v2, there are new highlight group names. So, instead of `texMathZoneX` there is `texMathRegionX`, and so on. Since vim-matchup uses the syntax group explicitly, it means it should be updated to support Vimtex:

https://github.com/andymass/vim-matchup/blob/master/after/ftplugin/tex_matchup.vim#L75

Perhaps you could add a simple `if exists('b:vimtex')` condition here?

**Comment by andymass** [comment]
Thanks.  Is there a way to detect vimtex v2 vs vimtex v1? (Is that necessary for backwards compatibility?)

Regarding the change, is it sufficient to change `texMathZoneX` to `texMathRegionX` or is it more complex?

**Comment by lervag** [comment]
> Thanks. Is there a way to detect vimtex v2 vs vimtex v1? (Is that necessary for backwards compatibility?)

No, sorry. I guess I should have added that. However, I have very recently changed a function name, so perhaps you could rely on that? I.e., `if exists('*vimtex#syntax#core#init_highlights')`? (I'll release v2.1 quite soon, and I could mention this as a compatibility resolution.)

> Regarding the change, is it sufficient to change `texMathZoneX` to `texMathRegionX` or is it more complex?

Yes, that should be sufficient.

**Comment by lervag** [comment]
Or, perhaps it is easier to just check if the syntax groups exist?

**Comment by lervag** [comment]
I'm thinking of `hlexists('texMathRegionX')`, which should return 1 if you are using Vimtex v2.

**Comment by andymass** [comment]
> Or, perhaps it is easier to just check if the syntax groups exist?

Perfect, that seems to be the best way.  Assuming the sequencing works out.

The part that gave me pause was "texMathRegionX, and so on." I thought maybe there were multiple things syntax groups I had to check.

I checked out this
https://github.com/lervag/vimtex/blob/4d1057effc8f9d35df72ed60c5253031e308b0d5/autoload/vimtex/delim.vim#L594

and the logic looks a bit more complex than before.  What's texMathRegionXX vs texMathRegionX?

**Comment by lervag** [comment]
> > Or, perhaps it is easier to just check if the syntax groups exist?
> 
> Perfect, that seems to be the best way. Assuming the sequencing works out.

Yes, I think it should.

> The part that gave me pause was "texMathRegionX, and so on." I thought maybe there were multiple things syntax groups I had to check.

Sorry, my bad; too fast. :)

> and the logic looks a bit more complex than before. What's texMathRegionXX vs texMathRegionX?

`texMathRegionXX` is `\(...\)`, while `texMathRegionX` is `$...$` and `$$...$$`.

**Comment by andymass** [comment]
Might be my installation/setup but neither `hlexists('texMathRegionX')` nor `exists('*vimtex#syntax#core#init_highlights')` works at the time this file is sourced.  vimtex/syntax/tex.vim happens _after_ matchup/after/ftplugin/tex.vim.  Is there anything I can check from vimtex.vim etc, basically anything before syntax step?

**Comment by andymass** [comment]
Thanks!  That seems to work (might be some corner cases but it's probably fine).

**Comment by lervag** [comment]
Great, happy to hear it! And glad to have vim-matchup working as expected again :)

**Comment by andymass** [comment]
@lervag saw some comments about texMathRegion vs texMathZone.  Is this change going to be affected?

**Comment by lervag** [comment]
Sorry, I forgot and should have notified you! Yes, after some discussions in lervag/vimtex#1880 and lervag/vimtex#1883 I decided to revert the use of `Region` back to `Zone`. This means the check for `texMathZoneX` is still valid for Vimtex now.

**Comment by lervag** [comment]
I'm sorry about the inconvenience!

**Comment by andymass** [comment]
No problem!  does it suffice to simply rollback the commit ee1d3e0 then?

**Comment by lervag** [comment]
Yes, that should suffice. :)
