### ISSUE TITLE
Bad performance after adding WinScrolled event

### ISSUE THREAD

**Issue by kevinhwang91** [andymass/vim-matchup#124]
### Explain the issue

When the cursor is at botline, and then press `j`, matchup slow down nvim.

1. What vim version are you using? nvim-0.5
2. Steps to reproduce: `L` & `jjjjjjjjjjjj`
3. Expected behavior: As fast as before
4. Observed behavior: Very slow

**Comment by andymass** [comment]
Thanks, I reverted the change.  I will have to see if this can be done efficiency in some way.
