### ISSUE TITLE
Wrong match in ruby code when using `and return if`

### ISSUE THREAD

**Issue by skamsie** [andymass/vim-matchup#126]
Wrong match in ruby code when using `and return if`. Example code to represent the problem

```ruby
def foo
  puts "foo" and return if 1 == 1
end
```
when cursor is on `def` it does not match anything, but when cursor is on `if` it matches `end` (and viceversa)

<img width="281" alt="Screenshot 2020-12-21 at 20 30 16" src="https://user-images.githubusercontent.com/7014744/102814712-5b0e0680-43cb-11eb-9825-bf78ab4be7b1.png">

**Comment by andymass** [comment]
I actually can't reproduce this.   When I open this ruby file it works correctly.  Are you able to create a minimal example config which demonstrates the issue.

**Comment by skamsie** [comment]
I figured out what was causing the issue. I had `let ruby_no_expensive = 1` in my `.vimrc`

`:help ruby_no_expensive`

If I remove it, it works correctly, even though it also highlights `return`, which I assume is expected. Is there a way to configure it so it only highlights the `end` without the returns? I have seen this also in other languages.
