### ISSUE TITLE
Allow ignoring certain symbols like `return` for example

### ISSUE THREAD

**Issue by skamsie** [andymass/vim-matchup#127]
**Is your feature request related to a problem? Please describe.**
I would like to be able to ignore matching certaing symbols like `return` for example inside a function. For example given the following ruby method:

```ruby
  def foo
    return :foo
  end
```

If I am on `def` I would like to only highlight `end` not `return` AND `end` and when I use `%` I want to jump on `end` not on `return`.

**Describe alternatives you've considered**

What I ended up doing was to comment out the code in `vim-matchup/after/ftplugin/ruby_matchup.vim` and I can get the desired behavior. But I would like a solution in the plugin to achieve this

**Comment by andymass** [comment]
Essentially, you want to ignore highlighting and moving to all "middle" words like return, elseif, etc?

**Comment by skamsie** [comment]
@andymass Yes, exactly.

**Comment by skamsie** [comment]
Actually I am not sure, whatever would be easier to implement betweenf **ignore all 'middle' words** or **ignore return**, but what bothers me most is the `return`. In particular when I use actions like `di%` for example, I can't find a case when I would like to delete up to return.

**Comment by andymass** [comment]
Actually, I think if you do `let g:matchup_delim_count_max=-1` then you already get the behavior you ask about for `di%`.  That doesn't solve the highlighting/motion problem, though.

**Comment by andymass** [comment]
I added an option `let g:matchup_delim_nomids = 1` which will inhibit matching return on if/endif.  Currently, if you hover on return it still highlights the if/endif, done entirely for ease of implementation, but  I think is also reasonably logical.

**Comment by andymass** [comment]
Closing as this seems to have at least two solutions 😃
