### ISSUE TITLE
Create github release which match vim.org versions

### ISSUE THREAD

**Issue by kiryph** [andymass/vim-matchup#13]
I've noticed that you've published your plugin `match-up` on https://vim.sourceforge.io/scripts/script.php?script_id=5624. My congratulations!

A minor thing which, however, I appreciate is if you could add to the github repository releases under https://github.com/andymass/vim-matchup/releases which match the releases under https://vim.sourceforge.io/scripts/script.php?script_id=5624. Right now what you call version 0.1 under vim.org should also exist here on github.

From my perspective this offers following advantages:
- a user can decide to follow head or to checkout a release
- a user can revert to a previous distinct version without remembering a commit hash which is not very user friendly.
- indicates possibly a minimum level of what the developer considers stable and has 'aged' a little bit; commits can sometimes break existing functionality; this already happened to me more than once. 
- for non git experts this is an alternative possibility to get your plugin.
- it is a backup for vim.org

I don't want to force you in a strict release model, but IMHO simply marking once in a while a version is good practice which you have already done.

**Comment by kiryph** [comment]
Thanks.

**Comment by andymass** [comment]
Good tip, thanks!
