### ISSUE TITLE
Relax LaTeX environment matching

### ISSUE THREAD

**Issue by lervag** [andymass/vim-matchup#131]
I just had an issue for VimTeX that at first seemed somewhat silly, but after giving it some thought I realized it is actually sensible: see https://github.com/lervag/vimtex/issues/1952.

Essentially, vim-matchup will not work for code like this:

```tex
\begin{a}
  \begin{b}
  \end{c}
\end{d}
```

Of course, this is just stupid, because this would not even compile. Still, it would be possible to easily match this just based on the `\begin` vs `\end` parts. One could even use highlighting to indicate the mismatched names specifically, which would make it easier to spot errors in ones code. I've made a simple change to VimTeX to allow this for e.g. `cse`, see https://github.com/lervag/vimtex/commit/4ff3e993ef17c7101d8db9de79674e320a20fcec. I would guess it should be quite easy to make a similar change here?

**Comment by andymass** [comment]
I am certainly not opposed to having this behind an option, as I can see the point.  But I'm not fully convinced this way is absolutely *better*.  For example, if you typed the following;

```tex
\begin{a}
  \begin{b}
   \en ... cursor ...
\end{a}
```

Under the old way, the matching is "correct" for the temporary state the buffer is in, while I'm about to type `\end{b}`.  Of course, one could also argue that this code is even _more malformed_ than your example, and thus should not be optimized for.

Suppose in the near future that instead of resorting to using regexes we had some smart way of actually smartly compiling and analyzing the document (for example via neovim's LSP).  Then what would happen?  On one hand, a `$t\to\infty$` goal of mine is is to properly handle languages like C++ by endowing it with a correct and *true* understanding of the syntax in the buffer not, just heuristic pattern matching.   On the other hand, is this an area where the regex is superior?  Is this closer to what the user *intended* versus what they literally said?

**Comment by lervag** [comment]
> I am certainly not opposed to having this behind an option, as I can see the point. But I'm not fully convinced this way is absolutely _better_.

I am not 100 % sure myself, but when I looked into it I failed to create a counter example that actually proved it is worse. And since someone already provided an example* of where this would be better, and since it was a trivial change in VimTeX, I saw no reason not to change things.

*The example was to use `cse` to change the name of the current environment to
fix typos. E.g. `\begin{test} ... \end{tes}` -> `cse` + `test` would fix the
typo.

> For example, if you typed the following;
> 
> ```
> \begin{a}
>   \begin{b}
>    \en ... cursor ...
> \end{a}
> ```
> 

Ah, I guess this shows an example where the update would make things different. With the current behaviour (and old behaviour in VimTeX), the `\begin{b}` would not be matched, and so `cse` would target the `a` environment. With the update, doing `cse` will not target the `\begin{b} ... \end{a}`, which is obviously wrong.

Ok, so there is no perfect solution here, and we're left with a choice of which case is more likely to be surprising to the user:

* The new VimTeX behaviour has the benefit of allowing things to work despite minor typos/errors, but the drawback that unfinished code may introduce unexpected behaviour.

* The old VimTeX behaviour and current matchup behaviour will not work with unmatched environments, but it seems to behave more or less as expected regardless of the "state". That is, if one expects to consider nested perfectly matching environment boundaries.

I'm not sure which of these I prefer, to be honest... perhaps I was too quick in changing this on VimTeX side...

**Comment by andymass** [comment]
I added a "match preference" which is just a filetype specific option for those filetypes which have built-in support (as opposed to just provided by the ftplugin like vimtex).

     let g:matchup_matchpref['tex'] = { 'relax_env': 1 }

Of course, this leads to the unfortunate situation where by default match-up and vimtex differ on what is a valid "env."  Maybe that's okay, `%` deals mostly with syntax and `dae` deals more with semantics.  Perhaps, this is an edge case anyway.

Not really related to this issue, but I've also been hitting against the "interface problem" where-in it seems every filetype needs to support match-up somehow and match-up needs to support every filetype.  This is similar, I think, with what you saw with vimtex + polyglot and with eventually bringing syntax highlighting fully into vimtex.

Anyway, I'll continue give this issue some more thought.

**Comment by lervag** [comment]
> I added a "match preference" which is just a filetype specific option for those filetypes which have built-in support (as opposed to just provided by the ftplugin like vimtex).
> 
> ```
>  let g:matchup_matchpref['tex'] = { 'relax_env': 1 }
> ```
> 
> Of course, this leads to the unfortunate situation where by default match-up and vimtex differ on what is a valid "env." Maybe that's okay, `%` deals mostly with syntax and `dae` deals more with semantics. Perhaps, this is an edge case anyway.

Yes, I don't see how to avoid this possibly inconsistent behaviour, unless we were to agree on one behaviour here. And I'm not sure I made the right call, to be honest. Perhaps it would be better to add an option on VimTeX side as well, e.g. `g:vimtex_env_relax_match` (set to 0 by default)?

> Not really related to this issue, but I've also been hitting against the "interface problem" where-in it seems every filetype needs to support match-up somehow and match-up needs to support every filetype. This is similar, I think, with what you saw with vimtex + polyglot and with eventually bringing syntax highlighting fully into vimtex.

Heh, it's not easy maintaining popular plugins, I guess. There's a lot of situations where I find it is not easy to find a perfect solution. So one has to choose between two or more less good alternatives. As a consequence, it is difficult, perhaps impossible, to satisfy the wishes of every single user.

**Comment by andymass** [comment]
Thanks for your very thoughtful comments as always :+1:.  I think I am OK with the state of the world, so closing.
