### ISSUE TITLE
window's topline altered when inserting linebreak before "}" if 'startofline' is reset

### ISSUE THREAD

**Issue by lacygoill** [andymass/vim-matchup#132]
**Describe the bug**

In a Vim file, the plugin might alter the view when inserting a linebreak before a `}` character.

**To Reproduce**

Run this shell command:

    vim -Nu <(cat <<'EOF'
        vim9script
        set lines=24
        set nostartofline
        set rtp^=~/.vim/plugged/vim-matchup rtp-=~/.vim rtp-=~/.vim/after
        filetype plugin indent on
        var lines = ['# {{{']
            + repeat(['#'], &lines)
            + ['def Func() #{{{']
            + ['    eval {0']
            + ['        0']
            + ['        0}']
            + ['    return 0']
            + repeat(['#'], &lines)
            + ['enddef']
        setline(1, lines)
        au VimEnter * OnVimEnter()
        def OnVimEnter()
            set ft=vim
            search('0}')
            norm! zz
        enddef
    EOF
    )

*This assumes that the plugin has been installed in `~/.vim/plugged/`.*

Notice that the cursor line is centered inside the window:

    :echo getwininfo()[0].topline
    18

Now, press `a` to enter insert mode, and `Enter` to insert a linebreak between `0` and `}`.  The topline is reset to 30:

    :echo getwininfo()[0].topline
    30

**Expected behavior**

The topline is still 18:

    :echo getwininfo()[0].topline
    18

**Screenshots**

![gif](https://user-images.githubusercontent.com/8505073/108610260-b1e88a00-73d4-11eb-8362-eadd3dec1136.gif)

**Environment**

 - vim-matchup version: https://github.com/andymass/vim-matchup/commit/52b3ec1ee8d0f78c69bae6cc32f3c2d1a023a8c8
 - Vim version: 8.2 Included patches: 1-2533
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(366)

**Additional context**

The issue disappears when `'startofline'` is set (it is by default).  It's not the first time I have weird issues because of this option.  I'm starting to think I should leave it alone.

---

I suspect the issue is triggered by the default Vim indent plugin which uses the normal `%` command, [here](https://github.com/vim/vim/blob/dc167465f87a4f03f9e085597dfcfdde39fcd2b9/runtime/indent/vim.vim#L133) and [here](https://github.com/vim/vim/blob/dc167465f87a4f03f9e085597dfcfdde39fcd2b9/runtime/indent/vim.vim#L147).

---

In the previous snippet, there are folding markers.  It seems they are not necessary to reproduce.  But where I found the issue, folding had an influence; depending on whether the folds were opened or not the topline was changed by a small amount of lines or by a big amount of lines.

---

The issue disappears if this line is commented out in the plugin:

https://github.com/andymass/vim-matchup/blob/52b3ec1ee8d0f78c69bae6cc32f3c2d1a023a8c8/autoload/matchup/motion.vim#L134

**Comment by andymass** [comment]
This is some wild bug.  Nice find and analysis.

I use `nostartofline` myself and have never seen this before.  Personally I don't consider that a solution.

Regarding the `normal %` in the indent plugin, was that always there, or is that related to a recent update?  It seems strange to me to use `normal %` instead of `normal! %` (well, because plugins and the user can do all sorts of things).

I want to say this is a vim bug, because even if `normal %` is intended, the problem seems to be that the indentexpr isn't restoring the screen properly.  One question is, does this also happen with matchit?  Or any other custom `%`?

**Comment by lacygoill** [comment]
> Regarding the normal % in the indent plugin, was that always there, or is that related to a recent update?

It's a recent update introduced a few weeks ago in [this commit](https://github.com/vim/vim/commit/82be4849eed0b8fbee45bc8da99b685ec89af59a#diff-48cf28a80003168943d20d7d40a2454ff6980019c84a3e4ac9cb7e819da22876).

The purpose was to fix [this bug](https://github.com/vim/vim/issues/7628).

> It seems strange to me to use normal % instead of normal! % (well, because plugins and the user can do all sorts of things).

I agree, but it seems intentional:

   > " For a line starting with "}" find the matching "{".  If it is at the start
   > " of the line align with it, probably end of a block.
   > " Use the mapped "%" from matchit to find the match, otherwise we may match
   > " a { inside a comment or string.

Apparently, the Vim indent plugin needs the `%` command from the matchit package to prevent a match inside a comment or a string.  I guess it assumes that the user has enabled the package (because I don't think it's enabled by default).

> I want to say this is a vim bug, because even if normal % is intended, the problem seems to be that the indentexpr isn't restoring the screen properly.

Yes, I wasn't sure the bug was in `vim-matchup`.  The problem is to get a minimal example which doesn't depend on any extra plugin.  I've tried but got tired after a few hours.  Besides, since the issue disappeared when I commented out the `matchup#pos#set_cursor()` call, I (maybe naively) assumed the issue was in the plugin; or at least it could be fixed in the plugin.

> One question is, does this also happen with matchit? Or any other custom %?

I don't think so, because I can't reproduce if I replace `set rtp...` with `packadd! matchit`:

    vim -Nu <(cat <<'EOF'
        vim9script
        set lines=24
        set nostartofline
        packadd! matchit
        filetype plugin indent on
        var lines = ['# {{{']
            + repeat(['#'], &lines)
            + ['def Func() #{{{']
            + ['    eval {0']
            + ['        0']
            + ['        0}']
            + ['    return 0']
            + repeat(['#'], &lines)
            + ['enddef']
        setline(1, lines)
        au VimEnter * OnVimEnter()
        def OnVimEnter()
            set ft=vim
            search('0}')
            norm! zz
        enddef
    EOF
    )

But maybe I need to do more tests to be sure.  I'll leave the issue open here, in case a workaround can be implemented from the `vim-matchup` side.  If it can't be fixed here, I'll close it and try to find a MWE which doesn't depend on the plugin, but that will take some time.

**Comment by andymass** [comment]
I'm still interested in finding a workaround, so feel free to keep the issue open.

I found out that if you do

    nnoremap % :<c-u>call cursor(57, 1)<cr>

it seems the problem can be reproduced without match-up.  Can it be that any `indentexpr` which moves the cursor far down will cause the view change? 

I think what's happening here is actually that from match-up's point of view, the cursor is somehow on the "return" and so `%` jumps to the `enddef` which is on line 57.
