### ISSUE TITLE
add match pattern for vim9

### ISSUE THREAD

**Issue by Shane-XB-Qian** [andymass/vim-matchup#136]
![image](https://user-images.githubusercontent.com/13550529/109825274-a159ce80-7c74-11eb-8e24-61c65581fbd2.png)

would you mind adding match pattern for vim9?
- `def` and `export def`
- perhaps should highlight `export` with `def` too, what you think?

// there would may have 'class' also, but for now, those two.

**Comment by andymass** [comment]
What specific version of vim are you on?

**Comment by Shane-XB-Qian** [comment]
On 21/03/03 02:13PM, Andy Massimino wrote:
> What specific version of vim are you on?

the latest one v8.2.2565

// vim9 means vim9 script, compared to legacy one.

-- 
shane.xb.qian

**Comment by andymass** [comment]
Well, in the latest vim, def / enddef is already highlighted as also in your screenshot.  What specifically do you want changed?

Regarding including export, perhaps this could be upstreamed to vim?  Bram picks the b:match_words patterns for vim.  I would consider adding a patch otherwise.

**Comment by Shane-XB-Qian** [comment]
um.. actually i am not sure, just felt if cursor at linehead (some 'jump' would prefer to jump to there without column information), then it would highlight directly, would be a bit convenient, but it's not a big problem...
// so it's up to you.. :-) included 'export' would be better, but 'not' also is ok..

**Comment by Shane-XB-Qian** [comment]
thx. and actually looks there would be new 'interface' keyword etc... too... not sure what's the end or too much, but so far perhaps ok. thx.

**Comment by andymass** [comment]
I think interface and class are still not supported in vim9, so we can close this.  If vim9 has updates we can address it then.
