### ISSUE TITLE
[Feature Request] Highlight outer match in visual mode

### ISSUE THREAD

**Issue by kevinhwang91** [andymass/vim-matchup#142]
I like va5a5a5 ...... (I have `xmap a5 <Plug>(matchup-a%)`) to extend selection.
  
Describe the features I expect through the following code snippets:
```vim
function Test() abort
    if 1
        echom 'test'
    endif
endfunction
```
1. cursor inside `echom 'test'`;
2. `va%`

### Actual behaviour
select from `if 1` to `endif`, `if` and `endif` are highlighted.

### Expected behaviour
select from `if 1` to `endif`, `function` and `endfunction` are highlighted, I don't care whether `if` and `endif` are highlighted or not.

**Comment by andymass** [comment]
In general, you always want the surrounding match to be highlighted?  In visual mode or always?  What is the overall goal to highlight func/endfunc?

**Comment by kevinhwang91** [comment]
> In general, you always want the surrounding match to be highlighted? In visual mode or always?
Yes, I have enable `matchup_matchparen_hi_surround_always`.

>What is the overall goal to highlight func/endfunc?
Like some expand region plugins https://github.com/terryma/vim-expand-region,  I want to quickly and accurately expand the selection with matchup.

**Comment by andymass** [comment]
This should be working now with

```vim
let g:matchup_matchparen_deferred=1
let g:matchup_matchparen_hi_surround_always=2
```

I.e., value 2 will highlight more than value 1, which is the previous behavior.

**Comment by kevinhwang91** [comment]
Nice!
