### ISSUE TITLE
Unvisible selected text in visual mode

### ISSUE THREAD

**Issue by timsofteng** [andymass/vim-matchup#143]
### Explain the issue

1. Neovim 0.5

2. Steps to reproduce
Enable gruvbox8 theme
https://github.com/lifepillar/vim-gruvbox8
Enable treesitter

3. Expected behavior
Selected text should be visible and different than regular

4. Observed behavior
Selected text can't be recognized

Expample of code

              <div class="column" style="display: inline-block;">
                <table>
                  <tr>
                    <td class="icon">
                      <a href="https://github.com/" target="_blank">
                        <img
                          alt="git"
                      /></a>
                    </td>
                  </tr>
                </table>
              </div>

Screenshot. There is selected word "class". But it's unvisible. Can't be recognized
![image](https://user-images.githubusercontent.com/51912173/112867735-ee8a5e00-90c3-11eb-9a56-551fd119e57c.png)

**Comment by andymass** [comment]
I think this is a problem with the colorscheme.  Specifically, gruvbox8 sets the Visual and MatchParen highlights to identical colors

```css
:hi MatchParen
MatchParen     xxx cterm=italic ctermbg=6 gui=italic guibg=#665c54
:hi Visual
Visual         xxx ctermbg=242 guibg=#665c54
```

Can you change one or the other?

**Comment by timsofteng** [comment]
Thanks. Sure. Let me redirect this issue to gruvbox8 repo.

**Comment by andymass** [comment]
Thanks.  Closing this then, as fixed in colorscheme upstream.
