### ISSUE TITLE
Wrong matched in case wrap of string

### ISSUE THREAD

**Issue by hanh090** [andymass/vim-matchup#144]
### Explain the issue
It highlight as `for..end` block instead of `do..end`
![Screen Shot 2021-04-05 at 13 14 58](https://user-images.githubusercontent.com/3643657/113543752-3d2e7f80-9611-11eb-9542-67ca2500d0a2.png)

### Minimal working example

Please provide a minimal working example, e.g.,

```ruby
        context 'without test' do
          it_behaves_like 'does not call for anything'
        end

```

**Comment by andymass** [comment]
I can't reproduce this.  Can you give details about your configuration?

![image](https://user-images.githubusercontent.com/6655373/113581663-735e0600-95f5-11eb-9544-40a8e41dc5c0.png)
![image](https://user-images.githubusercontent.com/6655373/113581696-7eb13180-95f5-11eb-8f70-e852a430e9bb.png)

**Comment by hanh090** [comment]
maybe conflict with another plugin, let me investigate that

**Comment by hanh090** [comment]
@andymass it was conflicted with `nvim-treesitter` plugin

**Comment by hanh090** [comment]
it related to nvim-treesitter issue which already report, proper solution can find  at here: https://github.com/nvim-treesitter/nvim-treesitter/issues/584#issuecomment-708607922

Therefore I will close this this bug
