### ISSUE TITLE
Error when starting with a Vue file

### ISSUE THREAD

**Issue by mklein994** [andymass/vim-matchup#151]
### Explain the issue

When I launch Neovim with a Vue file, I get an error message (see below) if I have `matchup { enable = true }` in my init.vim treesitter setup.

### Version information

| Name | Version | Notes |
| ---: | --- | --- |
| `neovim-git` | `NVIM v0.5.0-dev+1293-ga0da4c3a4` | Installed from the [AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=neovim-git&id=4fadf73a0f2c69118e1f0dd75ae9c0e117156f09), i.e. https://github.com/neovim/neovim/commit/a0da4c3a491f715c28f70bc2295be5fe809d72c2 |
| (system package) `tree-sitter` | `0.19.4-1` | [PKGBUILD at `eb962226aa`](https://github.com/archlinux/svntogit-community/blob/eb962226aa2b81239dcda767983d7419d2eb7ef3/trunk/PKGBUILD) |
| `~/.local/share/nvim/plugged-test/nvim-treesitter/parser-info/vue.revision` | `91fe2754796cd8fba5f229505a23fa08f3546c06` | Not sure if this is relevant. |

### Minimal working example

Once plugins and treesitter modules are installed (`:PlugUpdate` and so on), start `nvim` with the name of a file ending in `.vue` (doesn't matter if it exists or not):

```
nvim -u minimal.vim test.vue
```

I'm given an error message with the following:

```
Error detected while processing function 3[3]..4[67]..matchup#delim#get_current[1]..<SNR>44_get_delim_multi[3]..matchup#ts_engine#get_delim[3]..<SNR>41_forward:
line    1:
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 161
Press ENTER or type command to continue
```

Relevant `query.lua` line: [neovim/neovim@`a0da4c3` runtime/lua/vim/treesitter/query.lua:161](https://github.com/neovim/neovim/blob/a0da4c3a491f715c28f70bc2295be5fe809d72c2/runtime/lua/vim/treesitter/query.lua#L161)

I'm not familiar with Lua, tree-sitter or Neovim internals, so I honestly don't know what any of that means.

### Minimal init.vim file (uses `vim-plug`)

```vim
" minimal.vim
call plug#begin(stdpath('data') . '/plugged-test')
Plug 'nvim-treesitter/nvim-treesitter'
Plug 'andymass/vim-matchup'
call plug#end()

lua <<EOD
require'nvim-treesitter.configs'.setup {
  ensure_installed = "vue",
  matchup = {
    enable = true,
  },
}
EOD
```

If there's any information that I missed, please let me know.

**Comment by andymass** [comment]
Thanks for the report!

**Comment by oblitum** [comment]
Been hitting the same on Lua files, when going through curly braces.

**Comment by andymass** [comment]
@oblitum I can't seem to reproduce, do you have an example?  If this started recently, please update nvim-treesitter and do :TSUpdate.

**Comment by oblitum** [comment]
@andymass thanks, at the moment I was just editing [my `init.lua`](https://codeberg.org/oblitum/dotfiles/src/branch/archlinux/.config/nvim/init.lua), I had already `:TSUpdate` it. After review, I noticed I forgot to remove the nvim-treesitter pin on the `0.5-compat`, it's not needed anymore after nvim 0.6. So, my bad.
