### ISSUE TITLE
incorrect matching of `function` in lua if symbol `function` is present in the body of that function

### ISSUE THREAD

**Issue by vikdotdev** [andymass/vim-matchup#152]
### Explain the issue

Incorrect matching inside a function if word `function` is present in function name/variable name/comment etc.

![matching](https://user-images.githubusercontent.com/33513522/116973283-f772de80-acc4-11eb-8f81-d090b8121829.gif)

1. What vim version are you using? - `NVIM v0.5.0-dev+1285-g0150cc416`
2. Steps to reproduce - paste the function from example below
3. Expected behavior - correctly matching to the start of the function
4. Observed behavior - matching word `function` inside a comment/as a variable name/as part of the name of a different function

### Minimal working example

```lua
function M.git_path_to_current_buffer()
  local root_to_repo = vim.api.nvim_call_function('finddir', { '.git/..', vim.fn.expand('%:p:h')..';'})
  local full_path = vim.fn.expand('%:p')
  -- test_function -- delete this line to see another incorrect match

  if string.match(full_path, root_to_repo) then
    return string.gsub(full_path, root_to_repo, '') or ''
  else
    return vim.fn.expand('%:t')
  end
end
```

### Minimal init.lua file
I'm including everything that I could possible imagine might have something to do with current behavior, mind that I'm not very good at vim options.

```lua

vim.cmd('syntax enable')
vim.cmd('filetype plugin indent on')
vim.cmd('set termguicolors')
vim.cmd('set textwidth=0')
vim.cmd('set iskeyword-=_')

local indent = 2

vim.o.timeoutlen = 400
vim.o.number = false
vim.o.relativenumber = false
vim.o.shiftwidth = indent
vim.o.smartindent = true
vim.o.autoindent = true
vim.o.tabstop = indent
vim.o.expandtab = true
vim.o.hidden = true
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.wildmode = 'list:longest'
vim.o.clipboard ='unnamed,unnamedplus'
vim.o.fileencoding ='utf-8'

" load match-up
-- no plugin options, just defaults
" match-up options go here
```

**Comment by andymass** [comment]
I think this is caused by the option `vim.cmd('set iskeyword-=_').`  Do you need that setting?

If you are already using nvim-treesitter, another alternative is:
```
lua <<EOF
require'nvim-treesitter.configs'.setup {
  matchup = {
    enable = true, 
  },
}
EOF
```

**Comment by vikdotdev** [comment]
Yes, `vim.cmd('set iskeyword-=_')` is the culprit, and yes this setting is pretty important to me (jumping words over snake case is a pain without it). 

With `matchup = {  enable = true }` enable it now seems to work alright (apart from matching returns, but that's another issue). Thank you.

![fixed](https://user-images.githubusercontent.com/33513522/117111452-4c2f5b80-ad90-11eb-9ecc-50fd44dd8381.gif)

**Comment by andymass** [comment]
If you don't want return to be active you can use `let g:matchup_delim_nomids=1`.
