### ISSUE TITLE
Typescript `if-else`, `function-return`, `switch-case` matching

### ISSUE THREAD

**Issue by marcushwz** [andymass/vim-matchup#156]
Hi, thank you so much for this plugin.

**Is your feature request related to a problem? Please describe.**
I am not sure if I am missing anything, typescript `if-else`, `function-return`, `switch-case` matching does not work. For your information, I am using `vim-polyglot` and I noticed that there isn't `b:match_words` in the `/ftplugin/typescript.vim` while `/ftplugin/typescriptreact.vim` has the following:
```vim
if exists("loaded_matchit") && !exists('b:tsx_match_words')
  let b:match_ignorecase = 0
  let b:tsx_match_words = '(:),\[:\],{:},<:>,' .
        \ '<\@<=\([^/][^ \t>]*\)[^>]*\%(/\@<!>\|$\):<\@<=/\1>'
  let b:match_words = exists('b:match_words')
    \ ? b:match_words . ',' . b:tsx_match_words
    \ : b:tsx_match_words
endif
```
- However, the above pattern doesn't seem to handle the basic matching I wanted.

**Describe the solution you'd like**
- I tried to add something like:
```vim
  let b:tsx_match_words = '(:),\[:\],{:},<:>,' .
        \ '<\@<=\([^/][^ \t>]*\)[^>]*\%(/\@<!>\|$\):<\@<=/\1>,' .
        \ '\<if\>:\<el\%[se if]\>'
```
- This kind of proves that I can add to the `b:match_words`, although it does not work as I wanted to. I am just wondering if there are already solutions for this? Like adding basic `if-else`, `function-return` matching.

**Describe alternatives you've considered**
- I have tried searching through the issue and googling but to no avail. Matching through "\<Tag\>" is working fine, but I really hope I can get `if-else`, and others matching like I have in `ruby`

**Comment by andymass** [comment]
Unfortunately, it's not supported with b:match_words because there needs to be some "end" indicator, otherwise scanning becomes too slow.  In ruby we have literal "end" which allows this.

It can be supported with neovim/tree-sitter, will require modifying after/query/{}/matchup.scm file(s) to add appropriate queries.  Is this suitable?

**Comment by marcushwz** [comment]
Thanks for the reply, I will spend some time and figure out the integration with tree-sitter. The reason why I haven't migrate to tree-sitter from polyglot is that the `indentation base on filetype` seems to be breaking (or maybe my config is wrong). But yeah, it's good to know that, I can't do it with just the `b:match_words`, I guess we can close this issue first then.

**Comment by andymass** [comment]
Closing- I believe this is done, for the tree-sitter engine.
