### ISSUE TITLE
[Feature Request]: add option to make the offscreen popup has a full width of the window

### ISSUE THREAD

**Issue by elianiva** [andymass/vim-matchup#158]
**Is your feature request related to a problem? Please describe.**
I'd like to have the offscreen popup hint to be full width instead of as wide as the line content length

**Describe the solution you'd like**
use the width of the window instead of calculating the length of the line

**Describe alternatives you've considered**
none

**Additional context**
Here's some screenshots of before and after by changing `max(map(copy(l:body), 'strdisplaywidth(v:val)'))` to `winwidth(0)` in `autoload/matchup/matchparen.vim:723`

Before: 
![Shot-2021-06-01_1](https://user-images.githubusercontent.com/51877647/120254509-3b510780-c2b4-11eb-91f7-6b742a88cb6c.png)

After: 
![Shot-2021-06-01](https://user-images.githubusercontent.com/51877647/120254523-3ee48e80-c2b4-11eb-889c-4b791ba05f6c.png)

notice how the `e(0, 3)}` is missing because the content is overlayed by the popup, it doesn't look very obvious because I use the `Normal` highlight group for the popup background.

Thanks in advance!

**Comment by andymass** [comment]
I've added a "fullwidth" option:

    let g:matchup_matchparen_offscreen={'method': 'popup', 'fullwidth': 1}

BTW, there is also a border option, not customizable though.

    let g:matchup_matchparen_offscreen={'method': 'popup', 'border': 1}

NB- both of these are nvim only for now but can probably be extended to vim.
