### ISSUE TITLE
Incompatibility with zen-mode.nvim (or with NeoVim's float z-index in general)

### ISSUE THREAD

**Issue by oblitum** [andymass/vim-matchup#159]
### Explain the issue

1. What vim version are you using?
    NVIM v0.5.0-dev+1372-g056c464e8
2. Steps to reproduce
    - `:PackerSync`
    - restart neovim
    - `:ZenMode`
    - Go to a brace according to gif bellow
3. Expected behavior
    Correct matchup float position
4. Observed behavior
    Incorrect matchup float position

### Minimal working example

See gif.

### Minimal `init.lua` file

```lua
local install_path = vim.fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'
if vim.fn.glob(install_path) == '' then
    vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
    vim.api.nvim_command 'packadd packer.nvim'
end
require('packer').startup {{
    'wbthomason/packer.nvim',
    {
        'andymass/vim-matchup',
        config = function()
            vim.g.matchup_matchparen_deferred = 1
            vim.g.matchup_matchparen_offscreen = { method = 'popup' }
        end
    },
    {
        'folke/zen-mode.nvim', cmd = 'ZenMode',
        config = function()
            vim.cmd [[nnoremap <silent> <leader>M :ZenMode<cr>]]
        end
    },
}, config = {
    display = { open_fn = require('packer.util').float }
}}
```

### Additional Context

- [folke/zen-mode.nvim#Requirements](https://github.com/folke/zen-mode.nvim#%EF%B8%8F-requirements)
- https://github.com/folke/zen-mode.nvim/issues/14

### GIF

![gif-2021-06-04-122539](https://user-images.githubusercontent.com/1269815/120825738-1072e780-c530-11eb-8bbb-bb22fd203168.gif)

**Comment by andymass** [comment]
I'm not so sure this has to do with z-index.
Is this a bug in neovim?  We set the floating window 'relative': 'win' to the current window (which should be the Zen floating window) with col 0.  So neovim should be calculating the correct position.  Note that win_screenpos(0) reports what seems to be the correct column offset.

**Comment by oblitum** [comment]
Sorry as I simply have no idea on the subject as the only reference to "z-index" I've hit comes from https://github.com/folke/zen-mode.nvim/issues/14#issuecomment-846938925.

Maybe folke can bring some light as he has committed in core and may know better what's going on.

cc @folke

**Comment by folke** [comment]
This might actually be a Neovim bug. I remember I saw another zindex related issue where the relative=win didn't work as expected with a floating window. I'll check to see if I can find it

**Comment by oblitum** [comment]
I will close it here for now as suspicion leans towards a neovim bug, but discussion can keep on.

**Comment by folke** [comment]
Caused by https://github.com/neovim/neovim/issues/14735
