### ISSUE TITLE
E216 No such group or event: MatchupTreesitter

### ISSUE THREAD

**Issue by ram02z** [andymass/vim-matchup#161]
### Explain the issue
78775d82afc49cea4ddcc13bd8ccd95b3aa3bb20 added an autocmd which breaks query files. You can reproduce the issue by setting any file to the `query` filetype.

Error message:
![image](https://user-images.githubusercontent.com/59267627/124515018-4a0c6c00-ddd6-11eb-9382-20f24d2ec9ef.png)

Nvim v0.5

### Minimal vimrc file

Please provide a minimal vimrc file that reproduces the issue. The
following should often suffice:

```vim
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-treesitter/nvim-treesitter'
Plug 'andymass/vim-matchup'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close

" match-up options go here
```

**Comment by andymass** [comment]
Thank you for the report
