### ISSUE TITLE
ruby highlighter raise exception index out of data

### ISSUE THREAD

**Issue by SolaWing** [andymass/vim-matchup#162]
### Minimal working example

given following ruby in-editing file, with nvim 0.5 and treesitter plugin enabled, will raise following exception

```ruby
def run
  a = <<~EOF
end
```

![图片](https://user-images.githubusercontent.com/3897953/124729285-e18ecd80-df42-11eb-848b-f0735aeefc4b.png)

**Comment by andymass** [comment]
Are you certain this is caused by match-up and not upstream?  Does it work
if you disable match-up in init.vim but enable other treesitter modules?

**Comment by SolaWing** [comment]
@andymass seems like treesitter highlight issue. and this plugin trigger highlight on each move, make vim unusable. Sorry for disturbing you.
