### ISSUE TITLE
Press `A` in visual mode can't work as expected.

### ISSUE THREAD

**Issue by kevinhwang91** [andymass/vim-matchup#163]
### Explain the issue
`:h v_b_A_example` 

1. What vim version are you using? nvim-0.5
2. Steps to reproduce

[![asciicast](https://asciinema.org/a/425380.svg)](https://asciinema.org/a/425380)

### Minimal vimrc file

Please provide a minimal vimrc file that reproduces the issue. The
following should often suffice:

```vim
pa vim-matchup
let g:matchup_surround_enabled = 1
let g:matchup_matchparen_hi_surround_always = 2
let g:matchup_matchparen_deferred = 1
```

**Comment by tomtomjhj** [comment]
I'm having a similar problem.

Minimal example:

For nvim,
```
nvim -u NORC --cmd 'set runtimepath^=/path/to/vim-matchup'
```
For vim,
```
vim --clean -u repro.vim
```
```vim
" repro.vim
runtime defaults.vim
set runtimepath^=/path/to/vim-matchup
```

Enter the following text (`i1<CR>(2)<ESC>0k`). Note that the second line contains a parenthesis pair and is longer than the first line.
```
1
(2)
```

Then run `<C-v>j$A:`

expected:
```
1:
(2):
```

the actual result:
```
1   :
(2) :
```

**Comment by andymass** [comment]
@tomtomjhj Pushed a fix for this repro, please verify.
@kevinhwang91 I am not able to reproduce this.  Can you check if the latest commit fixes it?  If not, can you please provide the exact steps to reproduce?

**Comment by tomtomjhj** [comment]
That works for my cases. Thanks!

**Comment by kevinhwang91** [comment]
Thanks, look like the bug is gone.
