### ISSUE TITLE
bug: error for wrong number args

### ISSUE THREAD

**Issue by SolaWing** [andymass/vim-matchup#164]
![图片](https://user-images.githubusercontent.com/3897953/126099987-56102377-1b4d-4b50-b7ee-2a2f44e79594.png)

```lua
function M.detach(bufnr)
  api.nvim_call_function('matchup#ts_engine#detach', {bufnr})
end
```

```vim
function! matchup#ts_engine#detach(bufnr, lang) abort
  unlet s:attached[a:bufnr]
endfunction
```

remove lang arg in vim function seems ok

**Comment by andymass** [comment]
Fixed, thanks!  What were the steps you did which caused the error message?

**Comment by SolaWing** [comment]
@andymass nothing special. maybe plug-in update?
