### ISSUE TITLE
Using xml-ftplugin for Apache conf files

### ISSUE THREAD

**Issue by marc-aurel** [andymass/vim-matchup#166]
I'd like to use the xml-ftplugin for Apache conf files to jump easily e.g. between Location-start&end-tags.
If I switch filetype from apache to xml (:set ft=xml) in vim the xml-ftplugin is correctly loaded and used.
But I'd also like to keep my apache-filetype highlighting.
So I simply copied **after/ftplugin/xml_matchup.vim** to **after/ftplugin/apache_matchup.vim**.
But it doesn't work. What did I do wrong resp. what did I forget to make it work?

**Comment by andymass** [comment]
Apache conf syntax is quite distinct from xml, since you may have the following, which would otherwise be a self closed tag:

```conf
<Directory />
        Options FollowSymLinks
        AllowOverride None
        Require all denied
</Directory>
```

It is straightforward to create a custom pattern for this filetype:

    au FileType apache let b:match_words = '<:>,<\@<=\([^ \t>/]\+\):<\@<=/\1\g{hlend}>'

See also https://github.com/andymass/vim-matchup/wiki/The-match-up-wiki#apache-httpdconf.
