### ISSUE TITLE
Add support for ML-style (whitespace delimited w/ pattern matching) languages.

### ISSUE THREAD

**Issue by erlandsona** [andymass/vim-matchup#167]
**Is your feature request related to a problem? Please describe.**
Trying to imitate the `queries/c/matchup.scm` for `if`|`else if`|`else`, `let`|`in`, `case`|`->`, pairs in Elm. But figuring this out for Elm would be super useful for people using NVim for Haskell, Ocaml, FSharp, maybe Rust, Swift, or other languages that are starting to support pattern matching now too.

**Describe the solution you'd like**
I'd like to be able to cycle through `if`|`else if`|`else`, `let`|`in`, & `case`|`->` pairs in Elm.

**Describe alternatives you've considered**
I've gone down the `let b:match_words = '\<try\>:\<to\>:\<get\>:\<a\>:\<vim\sregex\>:\<to\>:\<work\>'` rabbit hole and a co-worker suggested I use treesitter integration to figure this out. Also, pretty sure based on this, https://github.com/andymass/vim-matchup/issues/156#issuecomment-843716162 that I'm on the right track. I don't have much experience with lisp variants / S-exprs and I'm not sure what all the keywords are / where they're exposed via treesitter / matchup specific stuff...

**Additional context**
Here's some examples of the syntax I'm trying to provide `%` cycling for.
```
module Stuff exposing (imFive)

iffy =
   -- Example If Else chain.
   if something > 0 then
        -- comment
        "Return String"
   else if somethingElse < 0 then
       "Less than Zero"
   else
       "Equals Zero"
    
-- Example Let in block sorta like do end in other languages.
imFive : Int -- type declaration
imFive =
    let
        imThree = 3
        imTwo = 
             let
                  nested = 2
             in
                  nested
    in
        imThree + imTwo
        
-- Example case of block
type Intish = One | Two | Three | Any Int

show : Intish -> String
show i =
    case i of
         One ->
              "One"
              
         Two ->
              "Two"

         Three ->
             "Three"

         Any _ -> -- may or may not be a capture / fallthrough / fallback / default case depending on the input type
               "Whatever"
```
Would love some help defining a queries/elm/matchup.scm file to enable `%` cycling through these constructs if possible.

I've also attached a screenshot of the queries file I've been tinkering with but I'm way out of my depth here.
<img width="1270" alt="Screen Shot 2021-07-23 at 9 58 18 AM" src="https://user-images.githubusercontent.com/10421138/126801013-d285a6c7-2900-4468-9b76-1f9c86111e7e.png">

**Comment by andymass** [comment]
Yeah, this is not the easiest grammar to deal with.  Can you give me some working samples?  The ones provided give errors in TSPlayground.

**Comment by erlandsona** [comment]
Updated the example sorry I ran into the same issue and the update should fix it for yah!

**Comment by andymass** [comment]
The following query seems to work in the 3 given cases.  I don't really know this language, so a deeper check would be good.

```scm
(if_else_expr
  . "if" @open.if) @scope.if

(if_else_expr
   "else" @_else
   "if"? @_if
   (#make-range! "mid.if.1" @_else @_if))

(let_in_expr
  "let" @open.let
  "in" @mid.let.1) @scope.let

(case_of_expr
  (case) @open.case
  (case_of_branch
     (arrow) @mid.case.1)) @scope.case
```

**Comment by erlandsona** [comment]
https://images.app.goo.gl/AxvvQPzTpdQTeEE9A

Thank you sir!
