### ISSUE TITLE
tpope's vim-sensible and matchup

### ISSUE THREAD

**Issue by NoahTheDuke** [andymass/vim-matchup#17]
When I have [vim-sensible](https://github.com/tpope/vim-sensible) loaded before vim-matchup, I get the error, 'match-up must be loaded before matchit'. But the docs say, 'matchit.vim should not be loaded. If it is loaded, it must be loaded before match-up (in this case, matchit will be disabled when match-up loads).'

Should the docs be fixed?

**Comment by andymass** [comment]
Thanks!  You're right, the intent was to say the opposite.

vim-sensible should be loaded after match-up.  Is this acceptable?

**Comment by NoahTheDuke** [comment]
I think that's definitely acceptable, but it does feel weird, cuz I think of vim-sensible as the "pre-plugin" that I load before all others to correctly set the stage. I don't actually know if that's how it works behind the scenes, tho, lol.
