### ISSUE TITLE
Support advanced multiline strings in lua e.g. --[=[ something ]=]

### ISSUE THREAD

**Issue by Corey-Keller** [andymass/vim-matchup#174]
**Is your feature request related to a problem? Please describe.**
Lua supports semi-arbitrary multiline comment strings in the form of matching numbers of equals signs. Meaning `--[==[`, `--[===[`, and `--[=[` will only end the comment when it encounters `]==]`, `]===]`, and `]=]` respectively. 

**Describe the solution you'd like**
It would be ideal if `%` could be used to jump to the matching start/end comment string.

**Comment by andymass** [comment]
Surprisingly, it is easier with classic than treesitter.  treesitter sees the whole block as one comment with no hook for the symbols.

In classic, I think you can use

    call matchup#util#append_match_words('--\[\(=*\)\[:]\1]')

in your after/ftplugin/lua.vim file.

**Comment by Corey-Keller** [comment]
Ok. Thanks. I assume it's mutually exclusive right? Meaning if I'm using that `after/ftplugin/lua.vim` file, I need to NOT be using [Tree-sitter integration](https://github.com/andymass/vim-matchup#tree-sitter-integration).

**Comment by andymass** [comment]
> I assume it's mutually exclusive right? 

Currently yes, though there may be an easy enhancement to get both active.

**Comment by andymass** [comment]
This should now be possible with the new `include_match_words` which heuristically determines which expressions of `b:match_words` to include.

```lua
require'nvim-treesitter.configs'.setup {
  matchup = {
    enable = true,
    ...
    include_match_words = true,
  },
}
```
