### ISSUE TITLE
which-key <SID> / <80> from vim-matchup

### ISSUE THREAD

**Issue by dsully** [andymass/vim-matchup#177]
### Explain the issue

Hi - I'm using https://github.com/folke/which-key.nvim with Neovim.

When using vim-matchup, it registers a keymap which shows up as:

<img width="174" alt="CleanShot 2021-09-12 at 06 51 42@2x" src="https://user-images.githubusercontent.com/22371/132990331-e23b5eca-d91f-4e96-9003-336cd3dc876d.png">

Ideally this wouldn't show up.

I tracked it down to these lines in `autoload/matchup.vim`, line 234

```
    " gets the current forced motion type
    nnoremap <silent><expr> <sid>(wise)
          \ empty(g:v_motion_force) ? 'v' : g:v_motion_force
```

I'm not familiar enough with vimscript to understand exactly what this does or why it is needed.

**Comment by andymass** [comment]
Can you please raise this on the which-key issue tracker?

`<sid>` mappings are common plugin implementation details and are private to match-up.  You would never type this, so it shouldn't be suggested to the user.  However, this mapping is important to implementing forcing operators (e.g., `dv%`), and it is not at all easy to remove it without losing functionality.

**Comment by dsully** [comment]
Will do. Thanks!

**Comment by andymass** [comment]
Thanks.  Separately, is it possible for a plugin to integrate with `which-key` to provide better suggestions?  Would it be helpful or is `which-key` already able to make intelligent suggestions for `match-up` somehow?

**Comment by dsully** [comment]
I'm not sure - I'd have to dig in a bit more.

You could potentially (using Lua anyways) do a pcall() check in vim-matchup to see if which-key.nvim is loaded, and then register vim-matchup keybindings with human useful descriptions.

Right now for example this is what is shown by default:

<img width="235" alt="CleanShot 2021-09-12 at 07 23 16@2x" src="https://user-images.githubusercontent.com/22371/132991364-7b4e00de-074f-4938-80c2-0f3d88608564.png">
