### ISSUE TITLE
Wrong highlight matchparen after entering InsertMode once

### ISSUE THREAD

**Issue by rhcher** [andymass/vim-matchup#180]
## Explain the issue
This phenomenon only occurs after entering vim insert mode at least once.

### Steps to reproduce
 1. run `nvim -u vimrc.vim racket.rkt`
 2. We put the cursor here and we can see that matchup is working fine
![image](https://user-images.githubusercontent.com/50723480/134021447-ef8e2512-261d-4217-bcd9-caabf6b01807.png)

 3. Then we input `a` and `backspace` key, the highlight works as expected.
![image](https://user-images.githubusercontent.com/50723480/134021515-14d68ede-3bb3-4c20-a0f7-9c533e39f906.png)

 4. However, when we input a space, it will look like this
![image](https://user-images.githubusercontent.com/50723480/134021934-35edb215-6603-4ceb-9221-8813d876ba03.png)
We can see that the wrong brackets are highlighted.

5. Then we go back normal mode. The error still exists.
![image](https://user-images.githubusercontent.com/50723480/134023361-b261a8cd-b8d0-4d36-b261-2f68578535f2.png)

### Expected behavior
highlight correct paren.

### Observed behavior
highlight wrong paren.

## Minimal working example
racket.rkt
```racket
(define insertL-f
  (lambda (test?)
    (lambda (new old l)
      (cond ((null? l) '())
            ((test? (car l) old) )))))
```

## Minimal vimrc file
vimrc.vim
```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'andymass/vim-matchup'
call plug#end()
PlugInstall | quit

let g:matchup_matchparen_deferred = 1
let g:matchup_matchparen_hi_surround_always = 1
```

## Additonal information
nvim version: NVIM v0.6.0-dev+313-g490e09c6d8 (vim has same issue)
I can provide any other information if needed

**Comment by andymass** [comment]
Thanks for the thorough report!  I think this is handled- at least, the reproduction steps behave consistently now.

**Comment by rhcher** [comment]
Yes, now it works like a charm:) Thanks for your great work.
