### ISSUE TITLE
error from vim-matchup when using signcolumn

### ISSUE THREAD

**Issue by cridemichel** [andymass/vim-matchup#182]
### Explain the issue

Most issues are related to bugs or problems. In these cases, you should
include a minimal working example and a minimal vimrc file (see below), as
well as:

1. What vim version are you using?  If using neovim, Are you using
   tree-sitter or classic matching?
   Vi IMproved 8.2 (2019 Dec 12, compilato Sep 19 2021 15:55:16)
  Version macOS - x86_64
  Patch incluse: 1-3450

2. Steps to reproduce 
    1. download the following zip file 
        [matchup_bug.zip](https://github.com/andymass/vim-matchup/files/7264778/matchup_bug.zip)
        with a minimal vimrc file and a latex file to trigger the bug
     2. open the latex file called trigger.tex with the following command
         ```bash
       vim -u minimal_vimrc trigger.tex
       ````
     3. scroll down by one line 
     4. vim shows the following error:
           <img width="1753" alt="Schermata 2021-10-01 alle 08 43 09" src="https://user-images.githubusercontent.com/15322138/135576960-57b00a1a-66e4-4bde-bb8a-c8ecb156b0a9.png">

best Cristiano

**Comment by andymass** [comment]
Thanks for the report.  I fixed the issue and placed syntax highlighting in
the popup behind an option for now:

let matchup_matchparen_offscreen={'method': 'popup', 'syntax_hl': 1}

**Comment by cridemichel** [comment]
Dear Andy,
thank you for having fixed the issue so quickly!
best Cristiano

Cristiano De Michele
***@***.***
