### ISSUE TITLE
Suspicious interaction between vim-matchup and YCM

### ISSUE THREAD

**Issue by Aster89** [andymass/vim-matchup#186]
### Explain the issue

I think this issue is a consequence of an interaction between YouCompleteMe and vim-matchup. I've posted a question on [vi.stackexchange](https://vi.stackexchange.com/questions/34677/with-youcompleteme-and-vim-matchup-some-mapping-abbreviation-is-deleting-ins), but that hasn't helped yet.

1. What vim version are you using? 8.2 same as in #183.
2. Steps to reproduce: having YouCompleteMe and vim-matchup plugins, and simply writing stuff in an existing HTML comment, so within `<!-- here -->`.
3. Expected behavior: the comment is written.
4. Observed behavior: while I write, frequently the comment gets deleted from the `!--` part (the `<` survives) to the last letter I've written.
### Minimal working example

Please provide a minimal working example, e.g.,

Unfortunately I haven't been able to find an exact way to reproduce it, but typing letters and spaces in a comment sooner or later triggers the issue. I suspect the interaction with YouCompleteMe is fundamental to the problem. As you can see in the screencast below. While I'm typing there's a pum from YCM that pops up at the `!` of `<!--`. Sometimes it's harmful, but sometimes it results in the text being deleted leftward up to that point.

[![asciicast](https://asciinema.org/a/571ZWSnqkCkw59zNZDlhumXQG.svg)](https://asciinema.org/a/571ZWSnqkCkw59zNZDlhumXQG)

Some key points in the video:

  - at the time 00:09 the prolem happens (afterwards I press `u` to restore the `!--` part of the comment)
  - at around 00:21-00:22 there's a moment you'll see a pum flashing under the `!` of `<!--`. I haven't been able to pause the screencast at that exact moment, but I think that's strongly related to the issue.

### Minimal vimrc file

Please provide a minimal vimrc file that reproduces the issue. The
following should often suffice:

```vim
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  au VimEnter * PlugInstall --sync | source $MYVIMRC
endif
call plug#begin('~/.vim/plugged')

Plug 'Valloric/YouCompleteMe'
Plug 'andymass/vim-matchup'
call plug#end()

syntax enable

let g:ycm_complete_in_comments = 1
```

**Comment by Aster89** [comment]
With some help in [YCM gitter room](https://gitter.im/Valloric/YouCompleteMe#) I've found out that I can run
```vim
:augroup matchup_matchparen
:au! matchup_matchparen TextChangedI
:au! matchup_matchparen TextChangedP
:augroup END
```
and issue persists. If I also run either this
```vim
:augroup matchup_matchparen
:au! matchup_matchparen CursorMovedI
:augroup END
```
or this
```vim
:augroup ycmcompletemecursormove
:au! ycmcompletemecursormove TextChangedI
:augroup END
```
then it disappears.

So it looks like there's some interaction between `call s:matchparen.highlight_deferred()` and YCM's pum.

**Comment by Aster89** [comment]
I didn't know, but in YCM chat room I've been made aware that if I donwload the `*.cast` file from asciinema and run it in the terminal via `asciinema play that.cast`, I can then pause with <kbd>space</kbd> and even step frame by frame via <kbd>.</kbd>. This shows the crazy jumping of the cursor that happens all the time.

Not sure anymore whether it's a YCM or vim-matchup bug.

**Comment by andymass** [comment]
Thanks for diving into this.  I will try to trace the reproduce steps.

Is there a minimal set of match-up autocmds that can be removed like this
```
:augroup matchup_matchparen
:au! matchup_matchparen CursorMovedI
:augroup END
```
then the problem goes away?  Or is it necessary to remove all of TextChangedI,TextChangedP,CursorMovedI?

**Comment by andymass** [comment]
By the way, I really doubt the following will actually help in your case (since both match-up and YCM are asynchronous), but the existing suggestion in the help docs is:

    let g:matchup_matchparen_pumvisible = 0

Curious what would do.

**Comment by Aster89** [comment]
> Or is it necessary to remove all of TextChangedI,TextChangedP,CursorMovedI?

Removing only `CursorMovedI`, the problem persists.
Removing both `TextChangedI` and `TextChangedP` but leaving `CursorMovedI` active, the problem persists.
Removing both `CursorMovedI` and `TextChangedP`, the problem persists.
Removing both `CursorMovedI` and `TextChangedI`, the problem is solved.

**Comment by Aster89** [comment]
> ```
> let g:matchup_matchparen_pumvisible = 0
> ```
> 
> Curious what this would do.

The problem persists even with this line in my vimrc.

**Comment by andymass** [comment]
Thank you.  I have a proposed fix based on the issue description in this branch: https://github.com/andymass/vim-matchup/tree/bugfix-186-ins-cur 
I have to do more testing before releasing to make sure there are no unwanted side-effects.

**Comment by andymass** [comment]
FYI I just pushed a change which should make this occurrence much more rare, although does not fix the underlying issue.
