### ISSUE TITLE
offscreen match misplaced with signcolumn

### ISSUE THREAD

**Issue by cridemichel** [andymass/vim-matchup#187]
Hi,
this is what happens with signcolumn enabled
<img width="1755" alt="Schermata 2021-10-10 alle 11 52 32" src="https://user-images.githubusercontent.com/15322138/136690854-6c5f9e46-f491-4fd9-9989-62e6f172e864.png">

best Cristiano

**Comment by andymass** [comment]
HI, I can't seem to reproduce this.  What platform (vim, neovim version) and configuration are you using?

**Comment by andymass** [comment]
Thanks, unfortunately, I still can't reproduce it.  Are you on the latest version of the plugin?  I had some relevant commits recently.

**Comment by cridemichel** [comment]
yes I am on the latest version of the plugin,
in any case thank you, 
best Cristiano

Cristiano De Michele
***@***.***
