### ISSUE TITLE
Option to remove added virtual text on closing end

### ISSUE THREAD

**Issue by gjeusel** [andymass/vim-matchup#191]
Hey there, thank you very much for this awesome plugin !

I was wondering if there was a way to remove the display of the virtual text on the closing end in the case of treesitter module enabled ?

Here is an example of a python function, the virtual text is `◀ def`:
![image](https://user-images.githubusercontent.com/16243660/140431394-c295a4f5-dfcc-4086-89c3-16cd69acfa60.png)

I can't seem to find it, where does it come from ?

**Comment by andymass** [comment]
I added a new option `disable_virtual_text` which can be used in the nvim tree-sitter config.  

Just curious, why do you want to not see this?  Is there some other way you'd prefer to see the "other side of the match?"

**Comment by gjeusel** [comment]
Thank you very much !! That was fast as hell !

Well, I just don't want to see the other side of the match, I personally don't find it useful.
I just use the enhanced '%' of this plugin :)

**Comment by andymass** [comment]
Currently it uses the same highlighting as matchparen, that is to say the `MatchParen` group (and `MatchWord` group for words).

I will consider to add another group for the virtual text.

Note that if you want to disable highlighting (the matchparen feature) entirely you can just do `let g:matchup_matchparen_enabled = 0` which would also eliminate the virtual text.

**Comment by andymass** [comment]
Added `hi MatchupVirtualText`
