### ISSUE TITLE
(c.2) Highlight matching words no longer works

### ISSUE THREAD

**Issue by twnaing** [andymass/vim-matchup#192]
### Explain the issue

1. What vim version are you using?  If using neovim, Are you using
   tree-sitter or classic matching?: 0.6 & 0.5.1 without tree-sitter
2. Steps to reproduce: open nvim, navigate to source file `@sale`
3. Expected behavior: matching words should be highlight 
4. Observed behavior: no highlight on matching words

### Minimal working example

```ruby
  def create
    @sale = Sale.create(nil, create_params).tap do |s|
      s.session = current_user.active_session
      s.user    = current_user
    end
    authorize @sale

    if @sale.save
      redirect_to @sale, notice: 'Invoice successfully created'
    else
      render action: :new
    end
  end
```

### Minimal vimrc file

Please provide a minimal vimrc file that reproduces the issue. The
following should often suffice:

```lua
" load match-up
vim.g.loaded_matchit = true
vim.cmd [[packadd packer.nvim]
return require('packer').startup(function()
  use { 'andymass/vim-matchup' }
end)
```

**Comment by andymass** [comment]
Sorry, I can't reproduce this- matching works fine here (neovim 0.5.1)  Do you possibly have any other plugins installed via packs?  Or configs that are getting loaded accidentally?

**Comment by twnaing** [comment]
I am testing this on neovim 0.5.1, 0.6 and 0.5.1+doom-nvim and none of them work for me. 

Am I understanding the feature wrong? feature c.2 is the same as [vim-illuminate](https://github.com/RRethy/vim-illuminate), right?

**Comment by andymass** [comment]
> feature c.2 is the same as vim-illuminate, right? 

No, sorry, this plugin is like matchparen for matchit.  In your example, it highlights matching syntax elements like "def" and "end."  In addition to `(` and `)`.

It does not provide functionality to highlight "other uses of the same word."

**Comment by twnaing** [comment]
Thank you for helping me understanding the feature. I had the vim-illuminate installed and misunderstood feature c.2 (resulting removing of vim-illuminate and this issue).

I'll close the issue. I'll use both matchup and illuminate.
