### ISSUE TITLE
Errors in LaTeX begin/end

### ISSUE THREAD

**Issue by jeetsukumaran** [andymass/vim-matchup#197]
### Explain the issue

1. Neovim 0.5.1, with TreeSitter

2. Steps to reproduce

In the following, position cursor at any of the "begin" statements and hit ``%``, or any of the ``end`` statements and hit ``%``:

```tex
\begin{columns}
    \begin{column}[T]
        \begin{itemize}
            \item A
            \item B
        \end{itemize}
    \begin{column}[T]
        \begin{itemize}
            \item A
            \item B
        \end{itemize}
    \end{column}
\end{columns}
```

3. Expected behavior: jump to close/begin of environment.

4. Observed behavior

When positioned at: ``\begin{...}``:

```
Error detected while processing function MatchedBlock:
line    3:
E117: Unknown function: NextEnd
E116: Invalid arguments for function cursor
```

When positioned at: ``\end{...}``:

```
Error detected while processing function MatchedBlock:                                                                             
line    6:
E117: Unknown function: PrevBegin
E116: Invalid arguments for function cursor
```

**Comment by andymass** [comment]
What is your configuration?  This error doesn't look like anything match up creates.

**Comment by jeetsukumaran** [comment]
You're right! This one is from ``vim-latex-objects``:

```
[....]plugin/vim-latex-objects.vim
22:function! <sid>PrevBegin()
40:    let start = <sid>PrevBegin()
120:        call cursor(PrevBegin(), 0)
```

Apologies for the confusion.

And THANKS for a GREAT plugin!
