### ISSUE TITLE
Incorrect matching with ruby-lang & enabled Treesitter

### ISSUE THREAD

**Issue by 99monkey** [andymass/vim-matchup#198]
the problem happend with ruby code looks like this

```
def foo
  some_func() if true
end
```

it works by default.

But after installing Tree-sitter support for ruby
```
:TSInstall ruby
```
it breaks
![image](https://user-images.githubusercontent.com/43925/142924857-cdf20474-8116-4470-b561-000c33afe8e9.png)

I tried to disable it with treesitter config - no effect

```
local present, ts_config = pcall(require, "nvim-treesitter.configs")
ts_config.setup {
   matchup = {
     enable = true,    -- false also don't help
     disable = { "ruby" }, 
   },
}
```
after TSUninstall ruby it works again

What is the next step to investigate this problem?

version nvim 0.5.1

**Comment by 99monkey** [comment]
I'm sorry, but your fix doesn't help
how can I help you to investigate issue

**Comment by andymass** [comment]
Can you please provide a minimal working example that demonstrates the issue?  I cannot reproduce it with given configuration.

**Comment by RamiGaggi** [comment]
Same issue, ruby.
Matching corrupts when CHANGING keyword
![Peek 2022-07-19 12-31](https://user-images.githubusercontent.com/79656935/179718595-e91b1d3e-e0c3-453b-8934-f4314eaaea15.gif)

**Comment by andymass** [comment]
@RamiGaggi Reproduced, I guess it is due to some stale skip query result, will check.
