### ISSUE TITLE
As part of a macro, % leaves you in Visual mode

### ISSUE THREAD

**Issue by euoia** [andymass/vim-matchup#199]
### The issue

When using `%` as part of a macro, vim can be left in visual mode.

I am not sure if this is a bug in Vim / Neovim or this plugin.

Without this plugin installed, I am not able to reproduce the issue.

I've tested using minimal configuration in Neovim 0.6.0 and Vim 8.2.

Steps to reproduce.

1. Create a file and position the cursor on the `f`:

```
foo[
]

bar[
]
```

2. Start recording a macro to register q, `qq`.

3. Do the following actions `dt[%`

4. Stop recording the macro: `q`.

5. Position the cursor on the `b`.

6. Run the macro `@q`.

Observe that you are left in visual mode.

If this is part of a larger macro, the remainder of the macro is not likely to run as expected.

### Minimal vimrc file

Here's my entire ~/.vimrc

```
call plug#begin()
Plug 'andymass/vim-matchup'
call plug#end()
```

**Comment by andymass** [comment]
I think this is actually a vim bug.  See the reproduction below.  vim is calling the operator even though it is in normal mode.

Note: A standard workaround for macro problems like this is to introduce something in the macro to "slow it down":

    nmap gs <ignore>
    let @q = 'dt[gs%'

Obviously, this is not convenient, but in some other situations is necessary.

Please report this problem to vim.  Nevertheless, I will see if there is something I can do to fix it for current and older vims.

```vim
function! Do(type) abort
    echo a:type
endfunction

nnoremap <silent> <plug>(myplug-%)
      \ :<c-u>call Do('motion')<cr>
onoremap <silent> <plug>(myplug-%)
      \ :<c-u>call Do('operator')<cr>

nmap % <plug>(myplug-%)
omap % <plug>(myplug-%)

let @q = 'dt[%'

" this fixes the macro
" nmap gs <ignore>
" let @q = 'dt[gs%'

" foo [
"
" ]
```

**Comment by euoia** [comment]
Thanks for looking into it and uncovering the cause of the problem.

It looks like this issue is being tracked by Vim here:
https://github.com/vim/vim/issues/6350

And Neovim here:
https://github.com/neovim/neovim/issues/12551

**Comment by andymass** [comment]
Pushed what I think is a harmless workaround for the vim bug in the meantime.  Essentially does what I suggested in my comment automatically.
