### ISSUE TITLE
Setting custom window options for the neovim popup window

### ISSUE THREAD

**Issue by williamboman** [andymass/vim-matchup#200]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to set some window-local options, such as `'winblend'` in the offscreen popup window that vim-matchup creates.

**Describe the solution you'd like**
I think either extending the configuration with a dict of custom options or provide some other kind of API to hook into the creation of the window would be pretty neat. Perhaps something like:

```vim
let g:matchup_matchparen_offscreen_win_opts = {
    \ 'winblend': 10
    \}
```

**Describe alternatives you've considered**
I've gone through the source code to try and see if there are ways to do this currently, but I could not figure something out.

**Comment by andymass** [comment]
Hypothetically would an autocmd make sense?  For example, something like this;

    au User MatchupOffscreenEnter set winblend=30

**Comment by williamboman** [comment]
That would probably do it! I keep forgetting the intricacies of vim - but will it really be possible to set a window-local option for a temporary floating window that never gains focus via an autocmd handler?

**Comment by andymass** [comment]
It is possible by executing the autocmd in the context of the floating window.  I am not fully sure this doesn't cause some weird side effects, but it does seem to work fine here (cf. recent commit).  If there are any issues with this approach I can revisit it.
