### ISSUE TITLE
About 'd]%'

### ISSUE THREAD

**Issue by yyy33** [andymass/vim-matchup#203]
### Explain the issue

Most issues are related to bugs or problems. In these cases, you should
include a minimal working example and a minimal vimrc file (see below), as
well as:

1. What vim version are you using?  If using neovim, Are you using
   tree-sitter or classic matching?
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 25 2021 11:17:40)
```
2. Steps to reproduce

2.1.
![image](https://user-images.githubusercontent.com/51548147/148024105-9529bf5e-87ef-4c72-8b7c-9bc1b69e6b63.png)
2.2. `d]%`
2.3. 
![image](https://user-images.githubusercontent.com/51548147/148024185-c660bc80-2625-4af4-ab24-c882119aaf05.png)

3. Expected behavior
‘endfun’ was deleted

4. Observed behavior

If your issue is instead a feature request or anything else, please
consider if minimal examples and vimrc files might still be relevant.

### Minimal working example

Please provide a minimal working example, e.g.,

```vim
if l:x == 1
  call one()
elseif l:x == 2
  call two()
else
  call three()
endif
```

### Minimal vimrc file

Please provide a minimal vimrc file that reproduces the issue. The
following should often suffice:

```vim
set nocompatible

" load match-up
let &rtp  = '~/.vim/bundle/vim-matchup,' . &rtp
let &rtp .= ',~/.vim/bundle/vim-matchup/after'

" load other plugins, if necessary
" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable

" match-up options go here
```

**Comment by yyy33** [comment]
> ### Explain the issue
> Most issues are related to bugs or problems. In these cases, you should include a minimal working example and a minimal vimrc file (see below), as well as:
> 
> 1. What vim version are you using?  If using neovim, Are you using
>    tree-sitter or classic matching?
> 
> ```
> VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 25 2021 11:17:40)
> ```
> 
> 2. Steps to reproduce
> 
> 2.1. ![image](https://user-images.githubusercontent.com/51548147/148024105-9529bf5e-87ef-4c72-8b7c-9bc1b69e6b63.png) 2.2. `d]%` 2.3. ![image](https://user-images.githubusercontent.com/51548147/148024185-c660bc80-2625-4af4-ab24-c882119aaf05.png)
> 
> 3. Expected behavior
>    ‘endfun’ was deleted
> 4. Observed behavior
> 
> If your issue is instead a feature request or anything else, please consider if minimal examples and vimrc files might still be relevant.
> 
> ### Minimal working example
> Please provide a minimal working example, e.g.,
> 
> ```viml
> if l:x == 1
>   call one()
> elseif l:x == 2
>   call two()
> else
>   call three()
> endif
> ```
> 
> ### Minimal vimrc file
> Please provide a minimal vimrc file that reproduces the issue. The following should often suffice:
> 
> ```viml
> set nocompatible
> 
> " load match-up
> let &rtp  = '~/.vim/bundle/vim-matchup,' . &rtp
> let &rtp .= ',~/.vim/bundle/vim-matchup/after'
> 
> " load other plugins, if necessary
> " let &rtp = '~/path/to/other/plugin,' . &rtp
> 
> filetype plugin indent on
> syntax enable
> 
> " match-up options go here
> ```

This is the config file
```
let g:matchup_transmute_enabled = 1
let g:matchup_matchparen_offscreen = {'method': 'popup'}
let g:matchup_delim_stopline = 1500
let g:matchup_matchparen_stopline = 1500
let g:matchup_matchparen_deferred = 1
let g:matchup_matchparen_hi_surround_always = 1
let g:matchup_text_obj_linewise_operators = []
let g:matchup_surround_enabled = 1
function! s:matchup_convenience_maps()
  xnoremap <sid>(std-I) I
  xnoremap <sid>(std-A) A
  xmap <expr> I mode()=='<c-v>'?'<sid>(std-I)':(v:count?'':'1').'i'
  xmap <expr> A mode()=='<c-v>'?'<sid>(std-A)':(v:count?'':'1').'a'
  for l:v in ['', 'v', 'V', '<c-v>']
    execute 'omap <expr>' l:v.'I%' "(v:count?'':'1').'".l:v."i%'"
    execute 'omap <expr>' l:v.'A%' "(v:count?'':'1').'".l:v."a%'"
  endfor
endfunction
call s:matchup_convenience_maps()
function! Where(...)
    if a:1 == '!'
        MatchupWhereAmI?
    else
        MatchupWhereAmI
    endif
endfunction
command! -nargs=0 -range -bang -bar -register Where call Where('<bang>')

```

**Comment by yyy33** [comment]
This is text
````
function! GetShellSingle(...) range
    if a:0 == 1
        let COMMAND_LIST = getline("'[", "']")
    elseif a:0 == 2
        let COMMAND_LIST = getline(a:1, a:2)
    else
        return 0
    endif

    call map(COMMAND_LIST, 'substitute(v:val, ''^\s*'', repeat('' '', 4), '''')')
    call insert(COMMAND_LIST, "cat <<- 'EOF'")
    call insert(COMMAND_LIST, 'vim -nNEsu NONE --not-a-term -S <(') 
    call add(COMMAND_LIST, '    %p') 
    call add(COMMAND_LIST, '    q!') 
    call add(COMMAND_LIST, 'EOF') 
    call add(COMMAND_LIST, ') \') 

    let COMMAND_STR = join(COMMAND_LIST, "\n")
    call setreg('+', COMMAND_STR, 'l')
endfunction
````

**Comment by andymass** [comment]
Thanks, it is a bug.  However the expectation is that `d]%` does not delete `endfunction` because it is an exclusive motion.
