### ISSUE TITLE
Adapt treesitter queries to new Lua parser

### ISSUE THREAD

**Issue by zeertzjq** [andymass/vim-matchup#204]
`nvim-treesitter` has switched to a new Lua parser (<https://github.com/nvim-treesitter/nvim-treesitter/commit/c80715f883b8c7963782973b23297c5dec7924be>, <https://github.com/nvim-treesitter/nvim-treesitter/issues/2293#issuecomment-1015846555>), and the queries in this plugin need adapting.

**Comment by andymass** [comment]
Thanks for reporting.  Users will have to use `:TSUpdate` when upgrading the plugins.
