### ISSUE TITLE
[Bug] Matched item overrides status bar

### ISSUE THREAD

**Issue by alexmozaidze** [andymass/vim-matchup#209]
Config: https://github.com/alexmozaidze/dotfiles/blob/main/.config/nvim/init.vim
NeoVim v0.6.1 classic matching

# Steps to reproduce

1. Install this plugin
2. Put your cursor on anything that matches, making sure the highlighted thing is right under the status bar
3. The status bar now disappears forcing the matched thing to get shown

# Expected behavior

It doesn't mess with status bar

# Observed behavior

Status bar yeets out of existence for the duration of matching

# Minimal working example

I'll just put some screenshots.
Before:
![2022-02-07-033838_1366x722_scrot](https://user-images.githubusercontent.com/51371527/152706520-62b1b307-26f2-4a6f-917e-9e44a8740af9.png)

After:
![2022-02-07-033857_1366x722_scrot](https://user-images.githubusercontent.com/51371527/152706529-671d77d4-b652-4ec1-bf0e-3960264090d2.png)

# Minimal vimrc file

I didn't configure the plugin in any way, I just imported it

```vim
call plug#begin()
Plug 'andymass/vim-matchup'
call plug#end()
```

**Comment by andymass** [comment]
Yes, it is working exactly as intended. :slightly_smiling_face:    If you don't like it in the statusline, just use this option:

    let g:matchup_matchparen_offscreen={'method': 'popup'}
