### ISSUE TITLE
display matchin end with virtual text at side of cursor

### ISSUE THREAD

**Issue by FelipeLema** [andymass/vim-matchup#223]
**Is your feature request related to a problem? Please describe.**
I like how virtual text _to the side of code_  is presented for various uses (namely errors & DAP)

**Describe the solution you'd like**
When standing on a opening/close, the matching end is presented at the side of the cursor rather than at the top / bottom of the current window

**Describe alternatives you've considered**
Perhaps some configuration could be a function? maybe `position = function(arg1, arg2) end` with ready-to-use functions like `position = require('match-up.decoration').window_border` or `display = requrie('match-up.display').virtual_text("side")`

**Additional context**
NA

**Comment by andymass** [comment]
Interesting idea, can you show any mockup of how it will look?

**Comment by FelipeLema** [comment]
Just here below is the way it is right now. The cursor is at `}` and the match is overlapping the top code line. The highlight for this is "little-lighter-than-black background, italic"

![Captura de Pantalla 2022-05-17 a la(s) 15 40 52](https://user-images.githubusercontent.com/1232306/168896562-7656d4e3-ac04-411a-b1e6-6cabbae033c9.png)

And here below is the way I'm requesting. Same window, same cursor position, the virtual text with the matching line is _at the side of the cursor_ with the same highlight

![Captura de Pantalla 2022-05-17 a la(s) 15 40 52](https://user-images.githubusercontent.com/1232306/168897058-01d9565c-2b6a-4a2e-bd3a-6580c5dd9326.png)

maybe other users will prefer a different highlight (single color text, like diagnostics virtual text), but the idea stays the same

**Comment by FelipeLema** [comment]
come to think of it, this may have conflicts with other virtual text to the side ... I know that it's solved by setting a priority, but I dunno the specifics

**Comment by FelipeLema** [comment]
oh, so it's not virtual text, but rather a window (excellent, no conflict)

it looks like there's quite a handful of (vimscript) code already in `s:do_offscreen()` and it would require an overhaul to do an APi that can be extended as mentioned above

also, it seems that `disable_virtual_text` mostly covers this feature anyway

**Comment by andymass** [comment]
Sorry for the delay here, I think I found an easy way to do it. (I finished this some time ago just forgot to push it, oops).  Can you please test?

To use it, `g:matchup_matchparen_offscren = {..., 'position': 'cursor'}`.  nvim only.

**Comment by FelipeLema** [comment]
that configuration will show the text at the appropiate position, although neovim is showing it with the highlight being overriden (I've defined a different background + italic for that highlight, and it's showing it with default background + normal)

It seems like the `Normal` highlight of that popup window has very low priority vs the other highlighting that may be in place (regex syntax hl and/or treesitter hl). Whatever it is, I'm aware that handling highlighting in windows is complicated, so  my guess is that such a problem will be handled in a separate issue.

thanks again
