### ISSUE TITLE
Error message from matchup#transmute#dochange

### ISSUE THREAD

**Issue by lervag** [andymass/vim-matchup#225]
I'm getting the following error message relatively often from vim-matchup:

```
Error detected while processing function 24[3]..25[118]..matchup#transmute#tick[11
]..matchup#transmute#dochange:
line   39:
E716: Key not present in Dictionary: "regexone[l:corr.side]).'\)'"
Error detected while processing function 24[3]..25[118]..matchup#transmute#tick[11
]..matchup#transmute#dochange:
line   42:
E716: Key not present in Dictionary: "groups)"
Error detected while processing function 24[3]..25[118]..matchup#transmute#tick[11
]..matchup#transmute#dochange:
line   42:
E116: Invalid arguments for function copy
Error detected while processing function 24[3]..25[118]..matchup#transmute#tick[11
]..matchup#transmute#dochange:
line   43:
E121: Undefined variable: l:groups
Error detected while processing function 24[3]..25[118]..matchup#transmute#tick[11
]..matchup#transmute#dochange:
line   43:
E116: Invalid arguments for function keys
```

It usually appears when I navigate vertically with `k`. I have the following config, although I assume only the `transmute` option is relevant here?

```vim
let g:matchup_matchparen_offscreen = {}
let g:matchup_override_vimtex = 1
let g:matchup_transmute_enabled = 1
```

On neovim nightly, Arch Linux. I can go deeper with this and try to create a reproducible and minimal example, but wanted to throw it out first to check if it maybe was something simple...

**Comment by andymass** [comment]
Does the filetype you're using have tree-sitter enabled?

Just pushed a change- I am not sure it will resolve the error you saw but if it did that would be great.

**Comment by lervag** [comment]
Sorry, should have mentioned that: The filetype I see this in most is Lua, and yes, Tree-sitter is enabled. I've updated and tried to reproduce, but could not. However, the error seems a little bit flaky. I'll test for a few days and close the issue as resolved if I don't see the error anymore.

Thanks for the quick response and possibly quick fix!

**Comment by lervag** [comment]
Thanks again. I've not seen the error in 5 days, so I'll assume it is resolved. If not, I'll reopen after doing some further investigation to pinpoint what is happening.
