### ISSUE TITLE
Performance issues with large file

### ISSUE THREAD

**Issue by stevearc** [andymass/vim-matchup#227]
### Explain the issue

_What vim version are you using?_  Neovim 0.7.0 w/treesitter

I'm seeing performance issues when using vim-matchup in a relatively large file (~4000 lines). Typing is noticeably stuttery. I've tried to tweak the available options, but none of them seem to have any impact on the lag. Is there an option I'm missing that would help here?

### My matchup config

```lua
vim.g.matchup_surround_enabled = 1
vim.g.matchup_matchparen_deferred_show_delay = 1000
vim.g.matchup_matchparen_deferred_hide_delay = 1000
vim.g.matchup_matchparen_timeout = 100
vim.g.matchup_matchparen_insert_timeout = 20
require("nvim-treesitter.configs").setup({
  matchup = {
    enable = true,
  },
})
```

### Output of :MatchupShowTimes
```
                                   average       last          maximum
[loader_init_buffer]
  done                             1.01ms        0.51ms        1.42ms
[loading]
  init_done                        3.65ms        3.65ms        3.65ms
[loading_module]
  misc                             0.01ms        0.01ms        0.01ms
  surround                         0.02ms        0.02ms        0.02ms
  motion                           0.07ms        0.04ms        0.08ms
  matchparen                       0.91ms        0.91ms        0.91ms
  loader                           2.01ms        2.01ms        2.01ms
[matchparen.highlight]
  get_current                    119.80ms        0.48ms      215.13ms
[s:get_delim]
  first_pass                       0.15ms        0.15ms        0.25ms
  nothing_found                    0.17ms        0.17ms        0.27ms
[ts_engine.get_delim]
  fail                           119.46ms        0.12ms      214.80ms
```

I did my own profiling, and while there is a decent chunk of time spent in `cmp`, it all happens after I stop typing. By contrast, I see vim-matchup appear in the flame chart after every single keypress.
![Screen Shot 2022-05-27 at 12 37 50 PM](https://user-images.githubusercontent.com/506791/170779013-226449ad-af56-42bd-9100-2d3a7c85ebd0.png)

**Comment by andymass** [comment]
Thanks for these details.  Can we zoom into the lua function level?
What are you using to profile / make these charts, it looks very useful!

**Comment by andymass** [comment]
Also can you provide the file or an analog of the file?  What is the type of file?  Can a synthetic one be generated easily?

**Comment by stevearc** [comment]
Oh that's a good point! I was able to replicate the issue with a burner file https://pastebin.com/9fMXJjJM

Unfortunately the function information doesn't seem to get much more detailed than what you can see. Here's the trace: https://www.dropbox.com/s/1rfea715lyyo1w3/profile.json?dl=0
You can view it in chrome://trace or https://ui.perfetto.dev/

The trace was generated with an [unreleased plugin I hacked together](https://github.com/stevearc/dotfiles/tree/master/vimplugins/profile), so don't trust the numbers too much 😅 
In particular it looks suspicious that at the beginning of `collect_group_results` you can see the call to `iter_group_results` complete almost immediately, but then it takes ~150ms for `collect_group_results` to complete. I think this is because the tracing is done with monkey patching, and it only patches functions on the module root, but the iterator is declared as a local function. Probably the majority of that time is spent somewhere in the iterator.

---

After writing that I went and manually instrumented the iterator function. Suspicions confirmed: that's where all the time is spent. Happy to do some additional instrumentation if you want me to drill down further
![Screen Shot 2022-05-27 at 4 45 10 PM](https://user-images.githubusercontent.com/506791/170800847-92ce9d59-770a-437e-aead-8ba98d09c2e0.png)

(I believe this is for one keypress)

**Comment by stevearc** [comment]
FWIW I understand that this is a rather large file and there are some hard limits to what you can reasonably do with that. I would be perfectly happy with a solution that allows me to easily disable vim-matchup for large files, or enforces a hard time limit to computation, or limits the scope of the matchup search to just the local region of the file.

**Comment by andymass** [comment]
Thank you, this helps immensely.  While I deep dive on the performance improvement opportunities, there a few things that stick out.  In your original message you set a bunch of deferred parameters, but it appears you never actually enabled deferred matching, i.e.,

    vim.g.matchup_matchparen_deferred = 1

As the name implies, this simply defers matching until after your cursor stops moving like what you mentioned `cmp` does.  It helps, although it's not everything as it hurts when you are typing slowly enough for it to trigger.

`vim.g.matchup_matchparen_deferred_show_delay` is the critical parameter here that needs to be tuned (unfortunately, it does not support changing on the fly, you need to update your vimrc/init.vim).  With deferred matching and show_delay=300, insert mode feels mostly tolerable to me, though it is problematic in normal mode and transitions between modes.

What is unfortunate that all the work you show in the performance chart is memoized by buffer tick (which is what nvim-treesitter does also), which is totally helpless when the buffer is constantly changing.

If nothing else comes to me I have some simple ideas
- Better respect stopline (local region, as you suggest) and timeout within lua (there are very few breakpoints in the lua code right now, unlike in the pure vimscript implementation which checks for timeouts constantly).
- Separate stopline and timeout settings for insert mode. 
- Separate deferred timing for insert mode.

PS: I have no idea if it's related, but another user brought up an issue with timers and CursorHold plugins: https://github.com/andymass/vim-matchup/issues/100

**Comment by andymass** [comment]
Btw, one can also disable matching entirely in insert mode via

    let g:matchup_matchparen_nomode = 'i'

**Comment by stevearc** [comment]
Derp! I missed that I had to set an option to enable deferred highlighting >.<

Honestly, that's good enough for me. There's some slight lag when switching modes, and there can be hiccups if I wait *just* long enough to hit the delay timeout, but it's barely noticeable to me.

Thanks for the help!

**Comment by hinell** [comment]
I got 6000+ lines files and this plugin made my workflow as slow as hell, please, enable `matchup_matchparen_deferred` by default and document possible performance troubleshooting. Thank you.

Checkout profile log btw.

[profile.log](https://github.com/andymass/vim-matchup/files/13050347/profile.log)
