### ISSUE TITLE
Inconsistent highlighting in insert mode

### ISSUE THREAD

**Issue by ribelo** [andymass/vim-matchup#232]
### Explain the issue

Fennel

![2022-07-04-011516_grim](https://user-images.githubusercontent.com/1815898/177061549-7d76a062-98be-43ac-a234-49904bfb1b62.png)

Clojure

![2022-07-04-011458_grim](https://user-images.githubusercontent.com/1815898/177061552-6b7e49f3-61b2-43e6-8e3c-1b3668396364.png)

nvim+treesitter

**Comment by andymass** [comment]
What is your nvim-treesitter configuration?

**Comment by ribelo** [comment]
Even if I remove the treesitterr configuration, it does not change anything. To be sure, I even removed `:nvim-treesitter/nvim-treesitter`. No change. However, disabling vim-matchup via vim.g.matchup_enabled solves the problem in fennel.

**Comment by andymass** [comment]
Can you share the full code snippets?

**Comment by ribelo** [comment]
I don't know exactly what was interfering, but I kicked out nvim, recovered the old config and it works 🙃

Sorry for bothering you.
