### ISSUE TITLE
Add quotes (' ") support

### ISSUE THREAD

**Issue by mario-amazing** [andymass/vim-matchup#234]
Could you add jumping between quotes `' "`, by pressing `%`?

**Comment by gaoqiangks** [comment]
It will be pleasant to see it.

**Comment by zhengpd** [comment]
@andymass how would you think about supporting quotes?

**Comment by gaoqiangks** [comment]
> @andymass how would you think about supporting quotes?

我是用vscode+neovim插件来写latex, 主要是行内公式是用$....$来表示的, 所以经常需要在两个美元符号之间跳转, 我觉得这个功能应该是跟双引号单引号一样的.   虽然vim下的vimtex插件提供了这个功能, 但是在vscode+neovim下这个功能不能正常工作.

**Comment by andymass** [comment]
It can be done in nvim+treesitter, but cannot be done in vim, is that okay?

Also should this be default?  or opt in only?

**Comment by mario-amazing** [comment]
The configuration will be enough

**Comment by andymass** [comment]
Added experimental quotes support (for javascript and cpp only so far).  What filetypes do we need?

To enable, add enable_quotes = true in lua config.

**Comment by zhengpd** [comment]
@andymass Good work! I think can enable it for all filetypes, and disable some when we actually encounter any problem. For now I don't see any drawback of enabling it globally.

**Comment by andymass** [comment]
Unfortunately, it does not seem possible to enable everywhere with current Treesitter query restrictions.

**Comment by zhengpd** [comment]
@andymass I didn't know the TS restrictions. How about creating a new issue tracking the quotes support progress, like

- [x] js
- [ ] lua

We can get a clear picture from this list about what need to be done in future, and potentially discuss what might block a language away from quotes support.

**Comment by andymass** [comment]
Good idea @zhengpd 
Closing in favor of https://github.com/andymass/vim-matchup/issues/287
