### ISSUE TITLE
How to ignore tokens in comments

### ISSUE THREAD

**Issue by Dav-v** [andymass/vim-matchup#239]
Hi all, I've just recently discovered this plugin and I find it already really useful. There is only one thing that bothers me a little, tokens in comments. For example, in this simple piece of code the second parenthesis between /* */ shadows the first correct one after main(), so when I press % on the parenthesis on line 3 nothing happens, and if I press % on the parenthesis on line 6 the cursor goes to the parenthesis between /* */

```c
#include "stdio.h"

int main() {
  /* { */
  printf("Hello World\n");
}
```
I've already tried with adding to my .init.nvim
```vim
let g:matchup_delim_noskips = 2   " don't recognize anything in comments
```
but the problem remains. Sorry if this may seem a stupid question, but I wasn't able to find a solution.
I use nvim v0.7.2 with neovide 0.9.0

**Comment by andymass** [comment]
Do you use tree sitter?  Do you have it installed or enabled?

**Comment by andymass** [comment]
Found a bug which I think was causing this.  Let me know if that doesn't fix it.

**Comment by Dav-v** [comment]
Hi @andymass , it works perfectly now, thanks! Yes, I am using the treesitter integration with
```lua
require("nvim-treesitter.configs").setup({
...
  matchup = {
    enable = true, 
  }
})
```
