### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by rainerborene** [andymass/vim-matchup#24]
as `vim-matchup` is a replacement... wouldn't be a good idea to include on the `README` instructions about how to disable the default plugins?

like...

```VimL
let g:loaded_matchit = 1

Plug 'stuff'
```

**Comment by andymass** [comment]
match-up should disable matchit automatically so this shouldn't be necessary, but I added a note about it in the readme.

Were you having trouble before you added `let g:loaded_matchit = 1`?

**Comment by andymass** [comment]
Closing, because I think this has been addressed.
