### ISSUE TITLE
Add support for django template tags

### ISSUE THREAD

**Issue by ambadyanands** [andymass/vim-matchup#240]
**Is your feature request related to a problem? Please describe.**
Currently django template tags such as `{% block %} {% endblock %}` are not matched.

**Describe the solution you'd like**
It'd be nice if django template tags are matched when `filetype=htmldjango`.

**Describe alternatives you've considered**
None.

**Additional context**
[Here](https://docs.djangoproject.com/en/dev/ref/templates/builtins/#built-in-tag-reference) is a complete list of django's built-in tags from official docs.

Thanks.

**Comment by andymass** [comment]
This should be automatic if you use a plugin like https://github.com/tweekmonster/django-plus.vim

Alternatively, you can copy this code block into your config's `after/ftplugin/htmldjango.vim`

https://github.com/tweekmonster/django-plus.vim/blob/master/after/ftplugin/htmldjango.vim#L16

Do either of these work for you?

**Comment by ambadyanands** [comment]
Thanks, installing django-plus made it work. 

So I hope the philosophy is that if there exists a dedicated plugin with match{it,up} support then don't add it to matchup. I understand that it reduces duplication of efforts and helps in ease of maintenance.
