### ISSUE TITLE
Treesitter won't start with terraform files when vim-matchup is an added plugin to AstroNvim

### ISSUE THREAD

**Issue by queue-tip** [andymass/vim-matchup#256]
### Explain the issue

After vim-matchup is added to AstroNvim, treesitter won't start on a buffer containing a terraform file (written in hcl). Before moving to neovim >= 0.8.0 and the new treesitter highlight groups, everything worked as expected.

1. What vim version are you using?   I'm using Neovim 0.8.0 with tree-sitter and the AstroNvim configuration
2. Steps to reproduce:
- [Install](https://astronvim.github.io/#%EF%B8%8F-installation) AstroNvim
- Start neovim and install the `hcl` treesitter parser with the command `:TSInstall hcl`
- Open a file written in hcl, like a Terraform file, and you will see syntax highlighting for it
- In AstroNvim's `lua/` directory, create the directory `user/plugins` and the file `user/plugins/init.lua`
- The `user/plugins/init.lua` file's contents should be: `return { ["andymass/vim-matchup"] = {}, }`, as shown below
- Quit neovim and restart with `nvim +PackerSync` to install vim-matchup
- Open the same Terraform file
3. Expected behavior: I expect to see syntax highlighting for the `terraform` file
4. Observed behavior: No highlighting of any kind because treesitter no longer starts for the buffers with terraform files

### Minimal working example

This can be used as the sample terraform file, if saved as `sample.tf`

```HCL
module "elasticache" {
  source = "../modules/elasticache"

  server                        = var.server
  environment                   = var.environment
  vpc_id                        = module.network.vpc_id
  subnet_ids                    = module.network.public_subnet_ids
  node_type                     = var.cache_cluster_node_type
  num_cache_clusters            = 2
  engine_version                = "5.0.5"
  replication_group_description = "${var.server}-${var.environment}"
  soft_alert_action_name        = ["soft-alerts-technology-team"]
  hard_alert_action_name        = ["hard-alerts-technology-team"]
  http_security_group_id        = module.ecs.host_security_group
  enable_soft_alerts            = var.enable_soft_alerts
}

```

### Minimal config

This is not a vimrc but it's the minimal config that needs to be added to AstroNvim to reproduce the problem.

After installing neovim 0.8.0, and AstroNvim, add the plugin by creating the file `~/.config/nvim/lua/user/plugins/init.lua` with the contents:

```lua
return { ["andymass/vim-matchup"] = {}, }
```

**Comment by andymass** [comment]
This sounds bizarre.  What does TSModuleInfo say (specifically for hcl)?

**Comment by queue-tip** [comment]
Before installing vim-matchup:

```
>> default         autotag  context_commentstring  highlight  incremental_selection  indent  matchup  rainbow  
hcl                ✗        ✓                      ✓          ✓                      ✗       ✗        ✓        
```

After installing vim-matchup:

```
>> default         autotag  context_commentstring  highlight  incremental_selection  indent  matchup  rainbow  
hcl                ✗        ✗                      ✗          ✗                      ✗       ✗        ✗        
```

If the hcl parser is reinstalled with TSInstall, treesitter is enabled for each buffer with a terraform file and TSModuleInfo's output is as expected. The problem returns if I quit and restart neovim.

**Comment by queue-tip** [comment]
It was a mistake in my config. When vim-matchup loads after nvim-treesitter there is no issue.
