### ISSUE TITLE
Ruby save - Error detected while processing CursorMoved Autocommands for "*"

### ISSUE THREAD

**Issue by dualfade** [andymass/vim-matchup#262]
When placing the cursor over a loop ( ex: def; end ) an error occurs on save.

lunarvim.org - latest
release-1.2/neovim-0.8-222a872

Archlinux neovim -- current
neovim 0.8.0-3

![image](https://user-images.githubusercontent.com/2522757/200198201-839c3de5-8b67-4791-873d-e71abf0c8db1.png)

now save while the function is highlighted --
:w

![image](https://user-images.githubusercontent.com/2522757/200198219-baede926-a977-4104-b616-f90cf3a5555a.png)

config.lua --
From: https://www.lunarvim.org/docs/plugins/extra-plugins#vim-matchup

-- https://github.com/andymass/vim-matchup
  {
    "andymass/vim-matchup",
    event = "CursorMoved",
    config = function()
      vim.g.matchup_matchparen_offscreen = { method = "popup" }
    end,
  },

This does not happen if you save, when a function is NOT highlighted. 
Seams to be working on other main languages fine. At least when I tested just to see if it was ruby specific. 

Thanks !

**Comment by andymass** [comment]
I am not sure how to specify this in lunavim, but does the error happen if you don't lazy load the plugin, and load it on startup (not CursorMoved)?

**Comment by dualfade** [comment]
Good question. I was just trying to load this up in a baseline neovim to see if there is any diff. I can try that and ping you back.

Much appreciated.

**Comment by dualfade** [comment]
Well.. I tried adding it too "*/master/lua/lvim/plugins.lua" and get the same issue. This is where all the main ( static and supported ) plugins load. Nbd. It's not a show stopper and only seams to be happening with ruby.

Thank you.
Sincerely,

**Comment by andymass** [comment]
Thanks for trying it.  I downloaded lunarvim and was unable to reproduce the original issue, with base config + enabled match-up as described.

I also notice that the instructions do not include enabling tree-sitter integration, which according to lunarvim documentation (similar to rainbow) is done via:

    lvim.builtin.treesitter.matchup.enable = true                                                                                                                 

I think users of lunarvim will have better results with this enabled.

**Comment by dualfade** [comment]
Ok. It's official. You rule. Works like a top ! and you are right. awesome and thank you.

Enabled it in my config.lua 

Closing !! ;)
