### ISSUE TITLE
Why matchup is always loaded at last when vim starts?

### ISSUE THREAD

**Issue by fjchen7** [andymass/vim-matchup#264]
When I run `:scriptnames` I find that matcup will always be loaded after my customized configuration in `after/plugin`.

![image](https://user-images.githubusercontent.com/10106636/200487806-00c52747-539d-42a3-8ea2-b3c13ce9f4ed.png)

(the `plugged/` is where my plugins)

The situation is that: [which-key](https://github.com/folke/which-key.nvim) will register the detected keybinding. I want to unregister those matchup binds, but my configurations (the `which-key.lua` and `which-key.presets.lua` in screenshot) are loaded before markup loading and will be overwritten.

Only matchup behaves like this and most plugins will loaded before configurations in `after/plugin`.

I wonder how to make matchup loaded earlier. Is there any workaround? Thanks a lot!

Environment: neovim 0.8.0 with Vim plug as plugin management.

**Comment by andymass** [comment]
The reason for this is most parts of match-up are lazy-loaded (these are the autoload files).  However, the maps are created earlier than the scripts you list here.  You should still be able to unregister them using nunmap.  Alternatively, you can bind them like follows

    nmap <plug>(ignore-1) <plug>(matchup-z%)

Finally, you can `let g:matchup_mappings_enabled = 0` to disable all mappings (to create your own)
 
Can you tell me which maps are the ones that aren't able to be removed?
