### ISSUE TITLE
[Feature] Ability to jump to parent match context

### ISSUE THREAD

**Issue by Nate-Wilkins** [andymass/vim-matchup#267]
**Problem**
When in a specific context like:

```text
<div>
  <span>One</span>
  <span>Two</span>
  <span>Three|</span>
</div>
```

Getting to the start of `<div>` is difficult.

**Possible Solutions**
- Add a mapping that can jump to the parent match. Possibly `[p%`?
- Another plugin or custom mapping but I haven't found anything yet.

**Comment by andymass** [comment]
If you do `[%` and `[%` again it goes to the div, is that different from the expected?

**Comment by Nate-Wilkins** [comment]
Oh, okay. 
Yeah it kindof does what I expect but I need to press it 6 times.
And it seems inconsistent? Not sure what that's about but I removed most of my configuration to test it and that's what its doing. I'll have to look into it a bit more.

I'll close this out bc I think that is the desired functionality I was looking for, it just isn't working for me at the mooment.

Thank you!

**Comment by andymass** [comment]
If there is any modification or alternate which can make it more useful let
me know.
