### ISSUE TITLE
Does not appear to work with nested languages

### ISSUE THREAD

**Issue by unphased** [andymass/vim-matchup#271]
### Explain the issue

For example I've got some code with a different language embedded: 

```lua
vim.cmd([[
  noremap <C-S> :update<CR>
  vnoremap <C-S> <ESC>:update<CR>
  cnoremap <C-S> <C-C>:update<CR>
  inoremap <C-S> <ESC>:update<CR>
  function! TmuxWindow(dir)
    let nr=winnr()
    silent! exe 'wincmd ' . a:dir
    let newnr=winnr()
    if newnr == nr && !has("gui_macvim")
      let cmd = 'tmux select-pane -' . tr(a:dir, 'hjkl', 'LDUR')
      call system(cmd)
      " echo 'Executed ' . cmd
    endif
  endfun
]])
```

In this lua buffer I would like to see `function` and `endfun` toggling with matchit. But it does not recognize it. 

The syntax in this area is definitely correctly recognized as vim language from treesitter's perspective. So it makes me curious if treesitter is being leveraged for language lookup or if language is just following buffer filetype.

**Comment by andymass** [comment]
Does treesitter recognize this as a nested grammar?  I loaded this in nvim and it looks like it is treated as just a string.  Is there a way to get it to parse/highlight this region?

**Comment by andymass** [comment]
Nevermind, I was missing the vim parser and highlighting works now.

I tried adding a basic query set
```
(function_definition
  "function" @open.function
  "endfunction" @close.function) @scope.function

(if_statement
  "if" @open.if
  "endif" @close.if) @scope.if
```

It seems the plugin still doesn't work with the nested region, trying to figure that out.

**Comment by unphased** [comment]
Made any progress with this? 

I think leveraging treesitter to do the right thing with plugins like this is at the core of what I'm looking for from treesitter. This is probably the last thing preventing me from considering 100% complete code intuitive editor behavior. 

I have no problem with us having to tweak/add queries to get treesitter to apply the correct language detection to any given embedded string calls, even though I haven't tried making new queries yet, I feel confident already that treesitter can handle that.

**Comment by andymass** [comment]
Yes, we use treesitter for lookups with neovim and nvim-treesitter (see https://github.com/andymass/vim-matchup#tree-sitter-integration) when a query (.scm) is available.

Just required a tweak to consider all trees in the document.  It should work now.

**Comment by unphased** [comment]
That is wonderful. Thank you for taking a look into this, and I would imagine this really elevates the plugin to a new level for having this capability!! I will make more tickets if I encounter further issues.

**Comment by unphased** [comment]
This totally works! But not in all cases. 
In testing with if/else/fi construct in bash: 
- Doesn't work in a yaml file in which bash language is being detected but matchup isnt picking it up
- Similar situation for bash inside a RUN inside a dockerfile
- Works on a plain bash script

It does work for a function definition inside a `vim.cmd([[` vimscript block inside lua. 

I opened up TSPlayground and brought up anonymous nodes, language display, hl groups, but there is nothing there to indicate why the first group works and the second group does not when in both cases the inner language is clearly being seen properly by Treesitter at least. 

Is there something additional we need to add to tell matchup when to pick up these sublanguages? Something else I'm missing?

**Comment by unphased** [comment]
I made the following edit 
![image](https://user-images.githubusercontent.com/1542910/220483072-cf1776e9-2898-45e6-9c07-f69d0968f53d.png)
And in the lua file:
```
getting matches from bufnr: 1
lang detected! lua
lang detected! vim
lang detected! vim
lang detected! vim
lang detected! vim
lang detected! vim
lang detected! vim
lang detected! vim
getting matches from bufnr: 1
lang detected! lua
lang detected! vim
lang detected! vim
lang detected! vim
lang detected! vim
lang detected! vim
lang detected! vim
lang detected! vim
Press ENTER or type command to continue
```
Well, first item, wonder why this runs twice. 
But back to the topic at hand, definitely sees instances of vim in here!

In neither of the dockerfile or yaml files is ANY of this output present. So the code isn't running!

**Comment by andymass** [comment]
There are two main requirements, one is treesitter needs to recognize it as
a injected syntax (please check with nvim treesitter), and two you need to
add queries to after/queries as I did in the last commits on this ticket.

Please create a PR to add the queries as needed, I don't have capacity to
contribute every language.  There are many examples in the folder.

**Comment by unphased** [comment]
Awesome will do! All told this is a pretty rare situation that crops up but happy to contribute the relevant queries. This totally addresses my concerns by the way. Thank you.

**Comment by unphased** [comment]
Small question - since the bash queries are definitely already there as we have already seen, is it just that I have to add some/any queries for the languages I'm talking about (YAML and Dockerfile) and then the system will just automagically work? I'll test that. 

Let's say that's what happens, what could we do to just make this not necessary. What if for example for the Dockerfile lang we actually don't want to establish any matchup queries whatsoever?

**Comment by andymass** [comment]
Yeah so queries from both languages need to be present for it to work as
expected.  Otherwise match-up won't know to turn on those code bits.  It's
possible even an empty scm file would work but I haven't verified that.
 If not we can add some trivial query to turn it on.

**Comment by andymass** [comment]
This is a bit of a current limitation but the workaround is so trivial I
don't want to implement something else.

**Comment by unphased** [comment]
Sure. I made an empty dockerfile matchup.scm and it did cause the prints to come in 
```
getting matches from bufnr: 1
lang detected! dockerfile
lang detected! bash
lang detected! bash
lang detected! bash
lang detected! bash
lang detected! bash
lang detected! bash
lang detected! bash
lang detected! bash
```

however still no matchup functionality came in. I am now researching how to make a new trivial query to put inside.

**Comment by unphased** [comment]
Neither an empty query file nor a trivial one worked, so I went on to construct a working dockerfile query and got it working in my dockerfile:
```
(string_array
  ("[") @open.strarr
  (double_quoted_string) @mid.strarr.1
  ("]") @close.strarr
) @scope.strarr
```
However the embedded bash matchups are still not working.

**Comment by unphased** [comment]
let me know if there is some other stuff i can check... ran out of ideas

**Comment by andymass** [comment]
Please provide an example file with the syntaxes you're referring to.
Preferably a new issue.

**Comment by unphased** [comment]
> Please provide an example file with the syntaxes you're referring to. Preferably a new issue.

It's posted here: https://github.com/andymass/vim-matchup/issues/276
