### ISSUE TITLE
Ability to rebind %

### ISSUE THREAD

**Issue by unphased** [andymass/vim-matchup#273]
I use matchup functionality to navigate around a lot, and with this plugin as an example, it promises to allow us to customize and add a lot more matching capabilities. 

For me `%` is not really quick at all to type and I had been using 
```
nmap ` %
vmap ` %
omap ` %
au filetype markdown vmap ` S`
```
for years. These are recursive maps. 

Of course, I can ```vim.keymap.set({'n', 'v', 'o'}, '`', '%')``` which works great but it does not help for textobjects. I understand that they are operator pending mode mappings, but it's not clear what to do to customize them. 

There is this section from the Readme: 

> You may use the following maps I% and A% for convenience: 
> ```
> function! s:matchup_convenience_maps()
>   xnoremap <sid>(std-I) I
>   xnoremap <sid>(std-A) A
>   xmap <expr> I mode()=='<c-v>'?'<sid>(std-I)':(v:count?'':'1').'i'
>   xmap <expr> A mode()=='<c-v>'?'<sid>(std-A)':(v:count?'':'1').'a'
>   for l:v in ['', 'v', 'V', '<c-v>']
>     execute 'omap <expr>' l:v.'I%' "(v:count?'':'1').'".l:v."i%'"
>     execute 'omap <expr>' l:v.'A%' "(v:count?'':'1').'".l:v."a%'"
>   endfor
> endfunction
> call s:matchup_convenience_maps()
> ```

But it's mostly greek to me: 
- what is `(std-I)`? Arbitrary name?
- `xmap <expr> I mode()=='<c-v>'?'<sid>(std-I)':(v:count?'':'1').'i'` <-- no idea what it does

**Comment by andymass** [comment]
Hey, that code snippet is for a different usecase and is not applicable
here I think.   Can I understand that you just want to replace % with some
custom key in all mappings?   Or is your request something different or
more nuanced?

**Comment by unphased** [comment]
> just want to replace % with some custom key in all mappings

affirmative!

**Comment by andymass** [comment]
Note that you _should_ be able to easily rebind any of the keys like 

    vim.keymap.set({'n', 'x', 'o'}, '`', '<plug>(matchup-%)')
    vim.keymap.set({'x', 'o'}, 'i`', '<plug>(matchup-i%)')
    vim.keymap.set({'x', 'o'}, 'o`', '<plug>(matchup-o%)')
    ...

and the plugin will take care of the rest, i.e., it won't bind `%` if you asked it to be a different key.   This allows full customization, and there are only a handful maps to worry about.

I am still thinking about whether it makes sense to make a global variable to change all `%` to something else.

**Comment by unphased** [comment]
Yeah that makes perfect sense. So I would just grep in the source for these calls and make all of them after loading the plugin and it should do the trick for now it seems.

**Comment by unphased** [comment]
So far I've been driving with 
```
  nmap ` %
  vmap ` %
  omap ` %
```
in a `vim.cmd` and nothing's broken yet. fwiw.
