### ISSUE TITLE
Problem with formating lisp like languages

### ISSUE THREAD

**Issue by ribelo** [andymass/vim-matchup#274]
### Explain the issue

1. What vim version are you using?  If using neovim, Are you using
   tree-sitter or classic matching?

nvim nightly, treesitter mode

2. Steps to reproduce
- format code
- add space before paren
- move back one character so that you stand in the position where the paren will appear after formating
- format code using lsp-format

3. Expected behavior
no spamming with errors

5. Observed behavior
https://user-images.githubusercontent.com/1815898/219212513-afd115c4-88ab-4e61-8420-72feaaf6f35b.mp4

```
Error detected while processing CursorMoved Autocommands for "*"..function 6[3]..7[89]..matchup#delim#get_matching[20]..<SNR>81_get_matching_delims[86]..matchup#delim#skip0[2]..matchup#ts_syntax#skip_expr[5]..matchup#ts_syntax#synID[1]..<SNR>84_forward:
line    1:
E5108: Error executing lua ...ed-0.8.2/share/nvim/runtime/lua/vim/treesitter/query.lua:499: bad argument #2 to 'handler' (string expected, got nil)
stack traceback:
	[C]: in function 'handler'
	...ed-0.8.2/share/nvim/runtime/lua/vim/treesitter/query.lua:499: in function 'match_preds'
	...ed-0.8.2/share/nvim/runtime/lua/vim/treesitter/query.lua:584: in function '(for generator)'
	...vim-matchup/lua/treesitter-matchup/third-party/utils.lua:67: in function 'fn'
	...2/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:210: in function 'for_each_tree'
	...vim-matchup/lua/treesitter-matchup/third-party/utils.lua:45: in function 'get_hl_groups_at_position'
	...m-matchup/lua/treesitter-matchup/third-party/hl-info.lua:74: in function 'get_treesitter_hl'
	.../nvim/lazy/vim-matchup/lua/treesitter-matchup/syntax.lua:83: in function 'synID'
	[string "luaeval()"]:1: in main chunk
```

**Comment by andymass** [comment]
Would you be able to see if this is still a problem in latest HEAD?

**Comment by ribelo** [comment]
Look like there is still a problem

**Comment by andymass** [comment]
The trace is inside nvim code, haven't found the problem yet.  I am having trouble reproducing this, can you provide any more reproduction info?  Such as configuration, language server, plugins used.

**Comment by ribelo** [comment]
To make it easier I updated nightly from `NVIM v0.9.0-dev-fb1db80` to `NVIM v0.9.0-dev-204a8b1`, and it started working. Earlier, it wasn't working on a (some) stable version either. Seems like the error was on treesitter's side, which had a major update recently. Sorry for bothering you. By the way, thanks for the awesome plugin and your work <3
