### ISSUE TITLE
Matchup treesitter support doesn't work in certain Sublanguage situations 

### ISSUE THREAD

**Issue by unphased** [andymass/vim-matchup#276]
### Explain the issue

Matchup treesitter support works in some sublanguage combos but not in others. 

Working: VimL in Lua
Non-working: Bash in Dockerfile, Bash in Yaml

### Minimal WORKING example 

```lua
vim.cmd([[
  function! Test()
    echo "Hello World"
  endfunction
]])
```

Putting cursor inside function shows matchup highlighting and `%` working across `function` and `endfunction` in the VimL inside Lua.

## Minimal FAILING example

```dockerfile
FROM alpine

RUN if [ -z "$TEST" ]; then echo "TEST is not set"; else echo "TEST is set"; fi
```

Putting cursor on `if` does not highlight the `else` or `fi`, as it would when in a bash filetype buffer. Nor does `%` work on it.

### Minimal vimrc file

```lua
vim.cmd([[
  set nocompatible
  " load match-up
  let &rtp  = '~/.local/share/nvim/lazy/vim-matchup,' . &rtp
  let &rtp .= ',~/.local/share/nvim/lazy/vim-matchup/after'

  " load treesitter
  let &rtp  = '~/.local/share/nvim/lazy/nvim-treesitter,' . &rtp
  let &rtp .= ',~/.local/share/nvim/lazy/nvim-treesitter/after'

  " load other plugins, if necessary
  " let &rtp = '~/path/to/other/plugin,' . &rtp
  filetype plugin indent on
  set nocompatible
  syntax enable
]])

-- set up treesitter
require("nvim-treesitter.configs").setup({
  matchup = {
    enable = true,
    disable = {},
  },
})

-- match-up options
vim.g.matchup_matchparen_offscreen = { method = "popup" }
vim.g.matchup_surround_enabled = 1
vim.g.matchup_matchparen_deferred = 1
vim.g.matchup_matchparen_hi_surround_always = 1
```

**Comment by andymass** [comment]
Seems to work with a) bash queries b) stub dockerfile query file to pick up the injections

**Comment by unphased** [comment]
ok thanks. hopefully we'll find that we can do this in other scenarios as well and i'll contribute them back to this project when I find them
