### ISSUE TITLE
Improper output for MatchupWhereAmI

### ISSUE THREAD

**Issue by thisduck** [andymass/vim-matchup#281]
### Explain the issue

Seems like this commit https://github.com/andymass/vim-matchup/commit/80ad7817e58755a602f993163f61f3500978ebe5 introduces a bug in the output of `MatchupWhereAmI` in neovim with treesitter plugin installed. It works fine when treesitter is installed.

1. What vim version are you using?  If using neovim, Are you using
   tree-sitter or classic matching?
Neovim 0.9.0, treesitter installed.
2. Steps to reproduce
Run `:MatchupWhereAmI` in neovim with treesitter.
4. Expected behavior
<img width="879" alt="Screenshot 2023-04-09 at 1 52 38 PM" src="https://user-images.githubusercontent.com/293689/230788765-e4d3ca04-d613-434c-9e55-21f557e13a7b.png">

5. Observed behavior
<img width="1694" alt="Screenshot 2023-04-09 at 1 53 32 PM" src="https://user-images.githubusercontent.com/293689/230788771-47ceae68-3340-47ea-8e02-d5509b7164c1.png">

When I revert the `80ad7817e58755a602f993163f61f3500978ebe5` commit, it works as expected.

**Comment by andymass** [comment]
Thanks for clearly reporting.
