### ISSUE TITLE
Off screen match displaying as popup causes error in Neovim

### ISSUE THREAD

**Issue by comiluv** [andymass/vim-matchup#282]
### Explain the issue
In Neovim, with options `vim.g.netrw_fastbrowse = 0` and relative line numbers shown, after the cursor moves to a position where a pop up for the off screen match is to be shown, pop up shows with its content showing original buffer and below error message is displayed:
```lua
Error detected while processing CursorMoved Autocommands for "*"..function 3[3]..4[153]..<SNR>12_do_offscreen[21]..<SNR>12_do_offscreen_popup_nvim:
line   51:
E5555: API call: Invalid buffer id: 4
```
* Screenshot of the issue happening
![GIF 2023-04-11 10-46-56](https://user-images.githubusercontent.com/19642705/231183547-e789a150-6ca0-4a69-9a35-fae753989238.gif)

* What vim version are you using?  If using neovim, Are you using
   tree-sitter or classic matching?
`NVIM v0.10.0-dev-36+g7ffe45017`, classic matching (see minimal vimrc)
* Steps to reproduce
1. Place these two big lua files in a directory: https://pastebin.com/G1ewNFAC, https://pastebin.com/brkpeDqP
2. Note that above lua files are used only to trigger off screen match popups, any other big code files would do
3. `nvim .` in the directory
4. Open the first file
5. `G` to move the cursor to the end of file
6. `:Ex`
7. Open the second file
8. `G` to move the cursor to the end of file
9. see error

### Expected behavior
`return {` is shown at the top of the buffer as the off screen match pop up

### Observed behavior
The error message is shown and a pop up that mirrors the buffer around the current cursor position is shown

### Minimal vimrc file
Note vim-matchup was installed using lazy.nvim in the below minimal vimrc
```lua
vim.cmd([[
  set nocompatible
  " load match-up
  let datapath = stdpath('data')
  let &rtp  = datapath . '/lazy/vim-matchup,' . &rtp
  let &rtp .= ',' . datapath . '/lazy/vim-matchup/after'

  " load other plugins, if necessary
  " let &rtp = '~/path/to/other/plugin,' . &rtp
  filetype plugin indent on
  set nocompatible
  syntax enable
]])

-- match-up option
vim.g.matchup_matchparen_offscreen = { method = "popup" }

-- netrw option
vim.g.netrw_fastbrowse = 0

-- vim options
vim.opt.number = true
vim.opt.relativenumber = true
```
`vim.g.netrw_fastbrowse` is an option to automatically close netrw buffer after entering a file. See https://vi.stackexchange.com/questions/14622/how-can-i-close-the-netrw-buffer and `:help netrw_fastbrowse`

`vim.opt.number` and `vim.opt.relativenumber` are commonly used options to display relative line number on the gutter.

**Comment by andymass** [comment]
Thanks for reporting, the last commit may fix it.

**Comment by comiluv** [comment]
Looks fixed, thank you
