### ISSUE TITLE
The plugin doesn't match Ruby's method rescue/ensure keywords

### ISSUE THREAD

**Issue by aliaksandrb** [andymass/vim-matchup#285]
Method level `ensure, rescue` keywords are not matched.

<img width="260" alt="Screenshot 2023-04-17 at 11 45 32 AM" src="https://user-images.githubusercontent.com/526022/232581790-8303ad76-3dea-4bad-8c2c-463b4f1d516e.png">

It works good for explicit blocks with the these keywords though:

<img width="266" alt="Screenshot 2023-04-17 at 11 48 05 AM" src="https://user-images.githubusercontent.com/526022/232582296-0b7dfb1d-7fbe-4b3e-96c8-35bdfdaee913.png">

**Comment by andymass** [comment]
Are you using vim or neovim+treesitter?

**Comment by aliaksandrb** [comment]
@andymass yes! I have this in config:
```lua

require('nvim-treesitter.configs').setup({
  matchup = {
    enable = true,
    disable_virtual_text = false,
  },
})
```

While `matchup` configured with these options:
```vim
vim.g.matchup_matchparen_offscreen = { method = 'popup' }
vim.g.matchup_surround_enabled = 1
vim.g.matchup_transmute_enabled = 1
```

**Comment by andymass** [comment]
thanks for the suggestion!
 https://github.com/andymass/vim-matchup/commit/c815e58644ef8d6fff49686c8ff114ca36cf170c

**Comment by aliaksandrb** [comment]
It works perfectly, thank you! 👍
