### ISSUE TITLE
[improve][feature] only highlight the first word in an opening tag

### ISSUE THREAD

**Issue by Zeitvertreib** [andymass/vim-matchup#30]
Hey, no bug or such, and I really like to get started with this plugin, but something just popped up right away my mind as went along.

So on (long html) tags its pretty annoying that my colorscheme highlighting gets overwritten.
(So ether toggle the plugin when editing or: )

Great would be to highlight only the first word in an opening tag (including '<' and closing '>')
like so:
**<li** *class*="something" *attr*="attr and class is nicely highlighted" **>** item **\</li>**
instead of:
**<li class="something" keyattr="attr and class has no highlight anymore"\>** item **\</li>**

Or maybe you have any hints for me to change the highlighting.. ? ..or the plugin is intended to work that way, and it's a bug I experience on my setup? I don't know.

ty in advance and sry if this is post is misplaced
<hr>
Edit:

`hi MatchParen gui=bold`
Works fine for me, for now. But I'd like something better

**Comment by andymass** [comment]
You could customize the plugin to highlight only the tag name but it isn't currently possible to highlight pieces which are not contiguous (like the opening and closing `<` `>` of the tag).  Note also the opening `<` is not actually highlighted for tags by, design.  Initially it doesn't sound like a bug to me, but perhaps I am misunderstanding the situation.

Thus, I am curious:
 1. Which colorscheme are you using?  Can you show me a screenshot of what it looks like currently?
 2. Why do you want syntax to be preserved for the highlighted tag?
 3. Do you only want syntax to be preserved in insert mode or in all modes?

**Comment by Zeitvertreib** [comment]
I possibly overlooked the thing, that you may only highlight the tag name only.
This could be an sufficient solution. How is it done?

However, (1) here is a [screenshot](https://prnt.sc/jeo5bs), using despacio. (But the behavior remains with others I use (gotham, mustang, wombat..)) (Taken in normal mode, but looks the same in insert mode.)
(2) The code in the screenshot is usable in vuejs, the tags get verbose sometimes.
It is possible to restructure, like in the screenshot seen on the .workaround, but that gets obtrusive on smaller tags. ..also sometimes it's many attributes, with smaller "{..}"-sections, so it's nicer to have them on one line.
(3) Probably preserving syntax in insert mode would be sufficient.
..fancy would be, when on the closing tag, that the opening one is fully highlighted, and when you % to it, it would 'disappear', to syntax only and `<` `>`. (but that might be a bit overdone, idk. ..however, as it is in the screenshot, its distracting. I do like my syntax, it helps me focus, so I like to preserve it. at least in insert mode.)

**Comment by nickspoons** [comment]
I've also found the highlighting of the entire opening tag jarring. To limit the tag matching to only include the `<` and the opening tag name, I use this in `~/.vim/after/ftplugin/html.vim`:
```vim
call matchup#util#patch_match_words(
   \ '<\@<=\([^/][^ \t>]*\)\%(>\|$\|[ \t][^>]*\%(>\|$\)\):<\@<=/\1>',
   \ '<\@<=\([^/][^ \t>]*\)\ze\%(>\|$\|[ \t][^>]*\%(>\|$\)\):<\@<=/\1>'
   \)
```

This of course limits the entire match, so you can't `%` from anywhere in the opening tag, only the tag name. But for me, the readability is more important.

**Comment by andymass** [comment]
@nickspoons solution is what I had in mind originally, but as mentioned, it affects the cursor behavior too.  It's not currently possible to do this and it is not yet obvious to me how "partial highlight" would be specified as a regular expression.  I would like to keep this issue open and plan to address it in the future.

I added two enhancements so far related to this issue:

1) You can now change the highlight of the "current" word separately from the normal highlight.  For example,

      augroup matchup_highlight
        autocmd!
        autocmd ColorScheme * hi MatchParenCur gui=bold cterm=bold
      augroup END

will be much less jarring than the default for many colorschemes.

2) You can disable highlighting entirely in insert mode:

        let g:matchup_matchparen_nomode = 'i'

where `i` stands for "insert mode."

**Comment by Zeitvertreib** [comment]
I like where this is going.
However I (preferably) need to set the `call matchup#util#patch_match_words(..` in my `.vimrc`.
(Because I load my vim 'portable' (on systems/ directories I may or may not change) and also I'd like to have this behavior on more then html files (e.g. `*.vue` files ))
I tried altering the plugins `/bundle/vim-matchup/after/ftplugin/html.vim` `#patch_match_words` arguments to @nickspoons suggestion. ..no effect.
Also made a copy of that file, named it `vue.vim`, same directory, no effect.
Any suggestions?

@andymass 
1) doesn't work for me (no difference in pluginbehavior which I recognize)
2) works like a charm

**Comment by andymass** [comment]
@Zeitvertreib Do you use https://github.com/posva/vim-vue or something else?  Since it's the vue filetype, not html, so you can use the following in your vimrc:

```vim
function VueCustomMatchWords()
    call matchup#util#patch_match_words(
        \ '<\@<=\([^/][^ \t>]*\)[^>]*\%(>\|$\):<\@<=/\1>',
        \ '<\@<=\([^/][^ \t>]*\)\ze\%(>\|$\|[ \t][^>]*\%(>\|$\)\):<\@<=/\1>'
        \)
endfunction
let g:matchup_hotfix_vue = 'VueCustomMatchWords'
```
All this does is a literal string replacement on the `b:match_words` variable supplied by `vim-vue` (actually just copies the built-in html one).  Alternatively, you could set `b:match_words` directly to whatever regex you want.  This situation is made complicated because as far as the plugin is concerned vue and html are completely different filetypes.

**Comment by andymass** [comment]
I think this works now.  You can configure it for the vue and html filetypes:

    let g:matchup_matchpref = {}
    let g:matchup_matchpref.vue = {'tagnameonly': 1}
    let g:matchup_matchpref.html = {'tagnameonly': 1}

Alternatively, you can tweak highlighting for the match under the cursor:

    hi MatchParenCur gui=bold

Or, for all words, without changing the parentheses highlights.

    hi MatchWord gui=bold

**Comment by nickspoons** [comment]
Was there any reason you didn't add an `after/ftplugin/xml_matchup.vim` so xml files could also specify `tagnameonly`?

**Comment by andymass** [comment]
Not really, other than oversight since xml and html are truly different file types in vim.  Updated.

By the way, I'm concerned that all these `after/ftplugin` tweaks are going to become unsustainable in the long run but I can't think of an alternative besides providing my own database to replace vim's built-in ftplugin matchit support :-/.
