### ISSUE TITLE
[Feature Request]: Hybrid winbar/statusline option for offscreen matches

### ISSUE THREAD

**Issue by Subjective** [andymass/vim-matchup#305]
**Is your feature request related to a problem? Please describe.**
I like the idea of having offscren matches be displayed in the status line, especially for those below the visible window. But it is somewhat unituitive for offscreen matches above to be displayed there, even with a directional indicator symbol $\Delta$.

**Describe the solution you'd like**
It would be cool if we could get an option to display offscreen matches below to display in the status line, and matches above in the winbar.

**Describe alternatives you've considered**
The `popup` option seems to address the aforementioned issue, but seems to have a limited horizontal width, causing much of the matching pair to be cutoff (e.g. for method headers).

**Comment by andymass** [comment]
You should be able to set fullwidth on the popup, does that help?

    let g:matchup_matchparen_offscreen = {'method': 'popup', 'fullwidth': 1}

**Comment by Subjective** [comment]
Thanks! I probably should of looked through the help file more carefully. It works great, especially with syntax highlighting enabled.

However, I noticed there's a vertical beam in the number column, but only on the top popup window. Is this intentional? If so, is there any way to disable this or maybe customize the decoration?

<img width="61" alt="image" src="https://github.com/andymass/vim-matchup/assets/56745535/3d3c091c-ea5e-4ad8-819c-a3648d4aafd4">

**Comment by andymass** [comment]
Can you zoom the screenshot out a bit to show more context?

**Comment by Subjective** [comment]
Yeah sure, hopefully these screenshots show it better. Ideally, I would like to get the matching line number to show up in the number column (along with all the other line numbers), replacing the weird symbol. Then the beginning of both matching lines would vertically be aligned (they would be at the same indent level as their actual location in the file).

**`|` Symbol in number column for matching function:**
<img width="906" alt="image" src="https://github.com/andymass/vim-matchup/assets/56745535/7afe813a-9751-42e5-8a50-0ab44c407e35">

**`2` in number column for matching loop:**
<img width="912" alt="image" src="https://github.com/andymass/vim-matchup/assets/56745535/d7b878c3-6197-4869-af44-1bd56788c8e3">

**Comparison between statusline and popup display methods:**
<img width="917" alt="image" src="https://github.com/andymass/vim-matchup/assets/56745535/34fa617a-c0a7-4a85-823f-bcb6e09e30d1">

**Comment by andymass** [comment]
I think this is a bad interaction with the plugin you're using to draw lines, perhaps https://github.com/lukas-reineke/indent-blankline.nvim? 

This should be fixable, though.

**Comment by andymass** [comment]
That being said, I can't actually reproduce it with indent-blankline.nvim, so I might be missing something

**Comment by Subjective** [comment]
Okay, after some testing, the misalignment has to do with the signcolumn being enabled.

<img width="972" alt="image" src="https://github.com/andymass/vim-matchup/assets/56745535/8afa04c9-e66a-4acf-8de4-f8ecc8f58ef8">


Here are steps to reproduce:

1. Copy and paste the below config into `repro.lua`
2. `$ nvim -u repro.lua`
3. Hover over a text object with a matching pair

```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

vim.opt.relativenumber = true
vim.opt.signcolumn = "yes"

-- install plugins
local plugins = {
	{ "catppuccin/nvim", name = "catppuccin" },
	{
		"andymass/vim-matchup",
		init = function()
			vim.g.matchup_matchparen_offscreen =
				{ method = "popup", fullwidth = 1, highlight = "Normal", syntax_hl = 1 }
		end,
	},

	{},
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("catppuccin")

I'll have to look more into the weird symbols (I believe it has to do with the foldcolumn being enabled).

**Comment by Subjective** [comment]
Alright, here's a minimal config that can reproduce the weird symbols in the number column. When signcolumns are enabled, everything in the matching line is shifted over to the right, and as a result, the stuff in the fold column is shifted into the number column:

<img width="849" alt="image" src="https://github.com/andymass/vim-matchup/assets/56745535/6dcfeaf6-b1ba-4350-8aba-96a1df4dd82f">


<details>

<summary>Minimal repro.lua</summary>

```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	{ "catppuccin/nvim", name = "catppuccin" },
	{
		"andymass/vim-matchup",
		init = function()
			vim.opt.relativenumber = true
			vim.opt.signcolumn = "yes"
			vim.g.matchup_matchparen_offscreen =
				{ method = "popup", fullwidth = 1, highlight = "Normal", syntax_hl = 1 }
		end,
	},
	{
		"VonHeikemen/lsp-zero.nvim",
		branch = "v2.x",
		dependencies = {
			-- LSP Support
			{ "neovim/nvim-lspconfig" }, -- Required
			{ -- Optional
				"williamboman/mason.nvim",
				build = function()
					pcall(vim.api.nvim_command, "MasonUpdate")
				end,
			},
			{ "williamboman/mason-lspconfig.nvim" }, -- Optional

			-- Autocompletion
			{ "hrsh7th/nvim-cmp" }, -- Required
			{ "hrsh7th/cmp-nvim-lsp" }, -- Required
			{ "L3MON4D3/LuaSnip" }, -- Required
		},
	},
	{
		"kevinhwang91/nvim-ufo",
		event = "VeryLazy",
		dependencies = "kevinhwang91/promise-async",
		init = function()
			vim.o.foldcolumn = "1"
			vim.o.foldlevel = 99 -- Using ufo provider need a large value, feel free to decrease the value
			vim.o.foldlevelstart = 99
			vim.o.foldenable = true

			-- Using ufo provider need remap `zR` and `zM`.
			vim.keymap.set("n", "zR", require("ufo").openAllFolds)
			vim.keymap.set("n", "zM", require("ufo").closeAllFolds)
		end,
		config = function()
			require("ufo").setup()

			local lsp = require("lsp-zero").preset({})

			lsp.on_attach(function(client, bufnr)
				lsp.default_keymaps({ buffer = bufnr })
			end)

			lsp.set_server_config({
				capabilities = {
					textDocument = {
						foldingRange = {
							dynamicRegistration = false,
							lineFoldingOnly = true,
						},
					},
				},
			})

			lsp.setup()
		end,
	},
}

require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("catppuccin")
-- add anything else here
```


</details>

**Comment by andymass** [comment]
Thanks for the clear reproduction steps.  I think I fixed it, let me know if there are more issues.

**Comment by Subjective** [comment]
Thanks, that seems to have fixed the misalignment for the repro I sent, though I do wonder if there's any way to get the correct foldchar to display or just hide it altogether.

**Actual line**:
<img width="110" alt="image" src="https://github.com/andymass/vim-matchup/assets/56745535/4e27f3bb-7f56-496a-bd68-f92828be1fd9">

**Matchparen popup**:
<img width="116" alt="image" src="https://github.com/andymass/vim-matchup/assets/56745535/bafbd5a4-7840-4cc2-8644-826aea2041b4">

Also, on my normal config it seems like line numbers are being incorrectly positioned in the signcolumn instead of the number column. Not entirely sure why, I'll have to investigate it some more.

**Line numbers in signcolumn**:
<img width="125" alt="image" src="https://github.com/andymass/vim-matchup/assets/56745535/8c78eec5-0c80-409c-86d5-40017c664447">

**Comment by Subjective** [comment]
Okay, I found the root cause of the issue, it has to do with the fact the statuscolumn is enabled. It was added recently to Neovim 0.9.0, and allows for customization of all the side columns, including right-aligned relative line numbers, moving the signcolumn to the right of the number column, etc. As this is unrelated to the original focus of this issue, I'll just open a new one.
