### ISSUE TITLE
Latest tree-sitter-c parser breaks vim-matchup

### ISSUE THREAD

**Issue by lucario387** [andymass/vim-matchup#310]
### Explain the issue

This is more of a notification, as I don't know how to label this issue.

Using vim-matchup with [tree-sitter-c from this commit afterwards](https://github.com/tree-sitter/tree-sitter-c/tree/6ef89c54e1a1c786e9b2ec2d0d694bb7b0152c2a) makes it broken, as the queries noted below is now invalid
https://github.com/andymass/vim-matchup/blob/3c4ccc489002fe72b5d2e2ffc4b3b5a7d3ab65d8/after/queries/c/matchup.scm#L21-L23

**Comment by stumash** [comment]
this seems also to be happening for python

**Comment by andymass** [comment]
Merged PR
