### ISSUE TITLE
Error since last update → If treesitter matchup is enabled

### ISSUE THREAD

**Issue by Zeioth** [andymass/vim-matchup#314]
### Explain the issue

It hapens after opening nvim or any file, or if I try to ESC the error.

![screenshot_2023-07-30_02-33-21_624439731](https://github.com/andymass/vim-matchup/assets/3357792/cb269ecc-6dc7-4916-b7e8-52c8cd01d88c)

### The error stop showing if

* I revome vim-matchup

or

* If I comment  matchup in treesitter, then I can use the plugin normally without errors.

``` lua
      matchup = {
        enable = true,
        enable_quotes = true,
      },
```

### More info (should be irrelevant)

It seems to hapen in both nvim stable and git.

### My vim-matchup config (should be irrelevant)
It's the one I've been using for months

```lua
  {
    "andymass/vim-matchup",
    event = "VeryLazy",
    config = function()
      vim.g.matchup_matchparen_deferred = 1   -- work async
      vim.g.matchup_matchparen_offscreen = {} -- disable status bar icon
    end,
  },
```

**Comment by andymass** [comment]
Did you run :TSUpdate?

**Comment by Zeioth** [comment]
Apologies: After wiping my ~/.local/share/nvim and doing

```lua
:TSInstall c
:TSInstall lua
```

The error is gone. I normally have auto_install on treesitter. Maybe something went wrong there.

All good now thank you for looking into it @andymass
