### ISSUE TITLE
Feature request: disable closing hint

### ISSUE THREAD

**Issue by simonmandlik** [andymass/vim-matchup#316]
Would it be possible to add option to disable / modify the ending `◀ if` hint here?

![](https://user-images.githubusercontent.com/16707112/258225835-b4100a6f-ff9c-49d9-a084-fd3cc4d3a4e5.png)

**Comment by andymass** [comment]
Actually, you can disable it by passing disable_virtual_text = true in the nvim-treesitter config, does the suffice?

**Comment by simonmandlik** [comment]
Thanks!
