### ISSUE TITLE
Wrong matching across strings

### ISSUE THREAD

**Issue by Isrothy** [andymass/vim-matchup#322]
### Explain the issue

1. What vim version are you using?  If using neovim, Are you using
   tree-sitter or classic matching?
```
❯ nvim --version  
NVIM v0.10.0-dev-1031+gc431d820e
Build type: RelWithDebInfo
LuaJIT 2.1.1693350652
Run "nvim -V1 -v" for more info
```
Both tree-sitter and classic matching produce this bug

2. Steps to reproduce
In a file, write two strings.
One string contains a '{' and another contains a '}'
For example
```lua
local s1 = "{...."
local s2 = ".....}"

```
Then move the cursor onto on of the dots.

4. Expected behavior
No parentheses is highlighted
<img width="243" alt="image" src="https://github.com/andymass/vim-matchup/assets/61075605/74cf3422-2f7e-4378-95cc-9d7f5043afc3">

5. Observed behavior
The parentheses are highlighted
<img width="239" alt="image" src="https://github.com/andymass/vim-matchup/assets/61075605/fb63cf8d-e68c-43f9-a710-bc4c6c60055d">

### Minimal working example

```lua
local s1 = "{...."
local s2 = ".....}"

```

### Minimal vimrc file

I'm using lazy for neovim
```lua
{
"andymass/vim-matchup",
init = function()
	vim.g.loaded_matchparen = 1
	vim.g.matchup_matchparen_deferred = 1
	vim.g.matchup_matchparen_hi_surround_always = 1
end,
}
```

**Comment by andymass** [comment]
Does the following option do what you want (disable matching in strings)?

```vim
let g:matchup_delim_noskips = 2
```

Unfortunately, I don't see any way in treesitter to match this

```lua
local s3 = "{.....}"
```

but not this

```lua
local s1 = "{...."
local s2 = ".....}"
```

as the braces are not tree nodes.

**Comment by Isrothy** [comment]
Thank you for your reply.
I tried this method. It works without `vim.g.matchup_matchparen_hi_surround_always = 1`. No matching in strings.
However, if I turn on `vim.g.matchup_matchparen_hi_surround_always` and `matchup_matchparen_deferred`, this issue still exists.
