### ISSUE TITLE
Matchup adding random characters on the beginning of the buffer.

### ISSUE THREAD

**Issue by zer09** [andymass/vim-matchup#325]
### Explain the issue

When `matchup_matchparen_offscreen` method is set to `popup`, and you split the screen and go off screen and the paren matched, it will add some random character on the beginning of the file. Something like the image below.

![Screenshot 2023-10-11 181323](https://github.com/andymass/vim-matchup/assets/780780/4cf47097-5317-48b4-b14b-80e79b0e9a47)

1. What vim version are you using? 
```
NVIM v0.10.0-dev-1284+gf67517bba-dirty
Build type: Release
LuaJIT 2.1.1695653777
Run "nvim -V1 -v" for more info
With tree-sitter
```
3. Steps to reproduce
Open a file split the window, and scroll to the bottom until offscreen.
5. Expected behavior
It should not add random characters on the first line of the buffer.
7. Observed behavior
It add random characters on the first line of the buffer.

### Minimal vimrc file

Please provide a minimal vimrc file that reproduces the issue. The
following should often suffice:

```lua
return {
	"andymass/vim-matchup",
	version = false,
	event = "VeryLazy",
	config = function()
		vim.g.matchup_matchparen_offscreen = {}
		vim.g.matchup_matchparen_deferred = 1
		vim.g.matchup_motion_override_Npercent = 0 -- enable vim default {count}%
	end,
}
```

**Comment by samtgarson** [comment]
I'm also getting this fairly frequently, and it's _extremely_ frustrating 😅 it's a shame as the offscreen popup functionality is so useful most of the time.

It seems to be writing the contents of the bottom popup (including line number, sometimes repeated many times) to the top line of the file?

![Screen Recording 2023-10-14 at 16 58 17](https://github.com/andymass/vim-matchup/assets/6242344/cf6635fb-b546-4643-89cf-5f2761d094c8)

**Comment by kongjun18** [comment]
I also ran into this problem, but I couldn't reproduce it stably. I found that this BUG is caused by the text that should be written into the popup window being written into the buffer. The call chain is as follows.


```vim
Error detected while processing function <SNR>53_timer_callback[20]..7[153]..<SNR>53_do_offscreen[21]..<SNR>53_do_offscreen_popup_nvim[67]..<SNR>53_populate_floating_win[48]..<SNR>53_set_popup
```

> I'm also getting this fairly frequently, and it's _extremely_ frustrating 😅 it's a shame as the offscreen popup functionality is so useful most of the time.
> 
> It seems to be writing the contents of the bottom popup (including line number, sometimes repeated many times) to the top line of the file?
> 
> ![Screen Recording 2023-10-14 at 16 58 17](https://user-images.githubusercontent.com/6242344/275249689-cf6635fb-b546-4643-89cf-5f2761d094c8.gif) [ ![Screen Recording 2023-10-14 at 16 58 17](https://user-images.githubusercontent.com/6242344/275249689-cf6635fb-b546-4643-89cf-5f2761d094c8.gif) ](https://user-images.githubusercontent.com/6242344/275249689-cf6635fb-b546-4643-89cf-5f2761d094c8.gif) [ ](https://user-images.githubusercontent.com/6242344/275249689-cf6635fb-b546-4643-89cf-5f2761d094c8.gif)

**Comment by sandeshghanta** [comment]
+1 to this issue, took a while to figure out which plugin was messing up my nvim buffers with same symptoms. 

Currently have disabled plugin to bypass this issue.

**Comment by ray-x** [comment]
It took me a while to find out vim-matchup adding new line on top of my file. It exists in both neovim 0.9.x and 0.10. It might relate to cursor movement.

**Comment by andymass** [comment]
Can anyone please provide a configuration and reproduction steps?

**Comment by ray-x** [comment]
I saw same behavior as @samtgarson. This may relate to relatively large lua file(>300 loc). But I couldn't reproduce it stably.
my setup
```lua
      vim.g.matchup_enabled = true
      vim.g.matchup_surround_enabled = true
      -- vim.g.matchup_transmute_enabled = 1
      vim.g.matchup_matchparen_deferred = true
      vim.g.matchup_matchparen_offscreen = { method = 'popup' }
      vim.cmd([[nnoremap <c-s-k> :<c-u>MatchupWhereAmI?<cr>]])

-- treesitter
    matchup = {
      enable = enable, -- mandatory, false will disable the whole extension
    },

```

**Comment by CMOISDEAD** [comment]
Actually I have the same problem, but it happens only if I have activated `matchup_matchparen_offscreen method = popup` and `vim.g.matchup_matchparen_deferred = 1`, it happens that if I move to the end of the file these numbers appear at the beginning of the file, it is not necessary to have the window split, but it is necessary to have Neotree open.

**Comment by mehalter** [comment]
I can also report that I'm still having this problem with both `vim.g.matchup_matchparen_deferred = 1` and the offscreen method set to popup with a split open.

**Comment by mehalter** [comment]
@andymass is there any way to get this issue re-opened since the problem still persists?
