### ISSUE TITLE
Svelte error was reported after treesitter's commit of svelte parsing

### ISSUE THREAD

**Issue by 0x7a7a** [andymass/vim-matchup#340]
Hi,@amaanq 
I found that you recently submitted an coomit on svelte parsing to treesitter,Related [commit](https://github.com/nvim-treesitter/nvim-treesitter/commit/3a7b5a9fb46c261b83eadb126463a6e7bdfc8c78)
There are some problems. Can you take a look at it for me.

<img width="1563" alt="image" src="https://github.com/andymass/vim-matchup/assets/8832748/b7af0d88-bff7-45ee-85ae-703d5248224d">

  
>I have reduced the version of tressiter:  'b3e53e94232d2bc6d70516efbd932bcce3ba8e1e',this works well

**Comment by amaanq** [comment]
did you even look at the open prs...

**Comment by 0x7a7a** [comment]
> did you even look at the open prs...

Sorry, I just saw that there's a pr that hasn't been merged yet.
I tried to update the treesitter to the latest and disable matchup,i get a new mistake.
<img width="980" alt="image" src="https://github.com/andymass/vim-matchup/assets/8832748/9c4d1bd8-62ef-4ab0-8555-7d4f34c33dbb">
If needed I can start a new issue in the tressiter project and close this

**Comment by 0x7a7a** [comment]
> [nvim-treesitter/nvim-treesitter#3092](https://github.com/nvim-treesitter/nvim-treesitter/issues/3092)

Thank you for your help. I solved the problem after a complete reinstallation.
