### ISSUE TITLE
Matching on end of line matches the next pair

### ISSUE THREAD

**Issue by lisinge** [andymass/vim-matchup#36]
Awesome plugin, really enjoy using it. There is only one behaviour that doesn't work like i'm used to.

Using % with vim-matchit on the end of a line matched on pair on the current line like this: https://asciinema.org/a/DPPj9AucHWXAiqqVbSgYRDqX3
But using % with vim-matchup on the end of a line matches on the next pair, not the pair on the current line like this: https://asciinema.org/a/KTK9LWM5Gt4pG3qSNMYqvpSor

This happens a lot to me when using `$` to go to the `do` in a ruby block.

**Comment by andymass** [comment]
Seems reasonable.  Let me know if there are any issues.

**Comment by lisinge** [comment]
@andymass That was quick. Thanks! Will test this straight away!
