### ISSUE TITLE
Deepcopy in function "s:matchparen.highlight" fails when nesting is too deep

### ISSUE THREAD

**Issue by lukelbd** [andymass/vim-matchup#38]
I am using VIM 8.0, with patches 1-1300.

After updating to the latest version of this plugin, while working on an HTML file and moving the cursor over certain tags, I get the error

```
Error detected while processing function 5:
line   91:
E698: variable nested too deep for making a copy
```

I traced this to the `deepcopy` call in the function `s:matchparen.highlight` in `autoload/matchup/matchparen.vim`. Not sure how this can be fixed, but I'm sure a silent failure would work for now, instead of the error message popup. I just wrapped the `deepcopy` line in a `try..endtry` statement; in the `catch` block, there is an empty `return` statement.

Thanks in advance.

**Comment by andymass** [comment]
Are you using `g:matchup_transmute_enabled`?

Do you happen know which tags cause this and whether transmute stops working when it happens?

**Comment by lukelbd** [comment]
Yep, I am.

It happens in a ginormous file (lists 202 downloads within `<li><a href="url">url</a></li>` tags), but oddly enough, for every single tag, not just the list items (e.g. it fails when mousing over the `<head>` and `<body>` tags). Transmute indeed does stop working when this happens.

**Comment by andymass** [comment]
Thanks, that helps.  I *think* I understand why this is happening, but I can't fix it satisfactorily right now.  It seems to work if I simply change `deepcopy()` to `copy()`.  This removes the possibility of the error (hopefully it doesn't cause other issues).

The reason I prefer this change to `try..catch` is `deepcopy()` has performance implications as well and I'd like to remove it if possible.  Although, when you have so many tags, there's not much one can do to be performant anyway.  Note also transmute doesn't work with `<ul>/<ol>/<li>` tags, which is a known issue.
