### ISSUE TITLE
[Bug] Errors on startup when editing git commit message

### ISSUE THREAD

**Issue by henrebotha** [andymass/vim-matchup#4]
#### Steps to reproduce

1. In any git repo, stage some changes: `$ git add .`
2. Then open Vim to edit the commit message: `$ git commit`

#### Expected behavior

Vim opens without incident.

#### Observed behavior

Vim spits out an error immediately:

```
Error detected while processing function matchup#init[2]..<SNR>13_init_modules[7]..matchup#delim#init_module[11]..matchup#delim#init_buffer[3]..<SNR>14_init_delim_lists[61]..matchup#delim#get_capture_groups:
line   11:
E117: Unknown function: matchstrpos
E15: Invalid expression: matchstrpos(a:str, l:pat, l:start)
Press ENTER or type command to continue
```

And then once proceeding past this error to open Vim, another set of errors:

```
"~/dev/tempgit/.git/COMMIT_EDITMSG" 16L, 406C
Error detected while processing function matchup#delim#init_buffer[3]..<SNR>14_init_delim_lists[61]..matchup#delim#get_capture_groups:
line   11:
E117: Unknown function: matchstrpos
E15: Invalid expression: matchstrpos(a:str, l:pat, l:start)
line   12:
E121: Undefined variable: l:match
E15: Invalid expression: l:match[1] < 0 | break | endif
line   31:
E171: Missing :endif:   endwhile
line   11:
E117: Unknown function: matchstrpos
E15: Invalid expression: matchstrpos(a:str, l:pat, l:start)
line   12:
E121: Undefined variable: l:match
E15: Invalid expression: l:match[1] < 0 | break | endif
line   31:
<snip>
```

Truncated, because it loops apparently infinitely (if I hit `G` to go to the end of the errors, it just keeps scrolling and scrolling).

### Minimal vimrc file

```vim
set nocompatible
filetype off

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall
  autocmd VimEnter * close
endif

call plug#begin()

Plug 'andymass/matchup.vim'

call plug#end()
```

**Comment by andymass** [comment]
Thanks for the report.   What version of vim does this occur in?

**Comment by henrebotha** [comment]
D'oh, sorry! I should have specified. I'm seeing this in my system Vim installation on macOS:

```
:version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr  4 2017 18:14:54)
Included patches: 1-898, 8056
Compiled by root@apple.com
Normal version without GUI.
```

I just quickly tested Neovim and MacVim (the latter of which is what I actually use). Neither exhibits this error.

```
:version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 25 2017 09:00:57)
MacOS X (unix) version
Included patches: 1-771
Compiled by Homebrew
Huge version with MacVim GUI.
```

```
:version
NVIM v0.2.0
Build type: Release
```

**Comment by henrebotha** [comment]
Actually, I see now that if I just open the offending Vim version, I get the first part of the error as well (i.e. not the infinite looping error message, but the one before that). So not altogether git-related.

**Comment by andymass** [comment]
I have added an implementation of `matchstrpos` for compatibility with vim versions that do not have it.  This should fix the immediate error, but you may run into other compatibility problems.  I have not yet figured out what the minimum vim version I will support is.

**Comment by henrebotha** [comment]
Tested it _very_ quickly, with no success, but I'll check again later in more detail.

**Comment by andymass** [comment]
Added a few compatibility fixes.  master has been tested back to version 7.4.1689.

Branch compat-898 has been tested back to version 7.3.898.  I don't have access to your specific version or platform, but you can try that branch.  A couple warnings:
   - there might be some performance drawbacks to the functions used for compatibility in older versions
   - I cannot guarantee support for old vim versions far into the future

**Comment by andymass** [comment]
All compatibility changes are now in master, so I think it should work for you now.  If you have any issues, feel free to comment and/or re-open.
