### ISSUE TITLE
Error "warning: adding embedded git repository"

### ISSUE THREAD

**Issue by lucascaton** [andymass/vim-matchup#40]
1. What vim version are you using?

```
MacVim Version 8.1.280 (151)
VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 15 2018)
```

2. Steps to reproduce

* Add `Plug 'andymass/vim-matchup'`
* Run `:PlugInstall`

3. Expected behavior

I was expecting to add this plugin (folder) to my repo (my [vimfiles](https://github.com/lucascaton/vimfiles)).

4. Observed behavior

**Git** gets confused when I try to add the plugin to my repo (vimfiles):

`$ git add plugged/vim-matchup`

```sh
warning: adding embedded git repository: plugged/vim-matchup
hint: You've added another git repository inside your current repository.
hint: Clones of the outer repository will not contain the contents of
hint: the embedded repository and will not know how to obtain it.
hint: If you meant to add a submodule, use:
hint:
hint: 	git submodule add <url> plugged/vim-matchup
hint:
hint: If you added this path by mistake, you can remove it from the
hint: index with:
hint:
hint: 	git rm --cached plugged/vim-matchup
hint:
hint: See "git help submodule" for more information.
```

This doesn't happen with my other plugins.

Am I doing anything wrong? Could you please shed some light?
Thank you very much.

**Comment by andymass** [comment]
It doesn't really make sense to `git add` a repository.. do you mean to use submodules (as the warning says)?  But I don't understand why this would be different for this plugin vs any other.

I would recommend using submodules **or** vim-plug but not both to manage your plugins.  There is no advantage to submodules if you are already using PlugInstall/PlugUpdate.

**Comment by lucascaton** [comment]
Thanks, @andymass!

How would you recommend? To add `/plugged` folder to my `.gitignore`?

Thanks again!

**Comment by andymass** [comment]
Yeah, it's a good idea to add `plugged/ ` to `.gitignore` because if you already have the list of plugins as `Plug <repo>` statements it's not necessary to also add the folders to version control.

Closing, as I think it is not related to the plugin itself.. at least I can't see why it would be since this repo is just a standard repo.

**Comment by lucascaton** [comment]
Thanks, @andymass!

**Comment by lucascaton** [comment]
By the way, I just realised I opened this ticket in the wrong repo.
I meant to open it in https://github.com/junegunn/vim-plug 🤦‍♂️

Sorry about that 😄

**Comment by abhinahii** [comment]
hi

**Comment by abhinahii** [comment]
Write something that makes sense
