### ISSUE TITLE
[question] How to highlight only the tag name?

### ISSUE THREAD

**Issue by jlesquembre** [andymass/vim-matchup#42]
![a](https://user-images.githubusercontent.com/1058504/47311097-26f6f980-d639-11e8-96dc-4405f9e00084.png)

Is it possible to highlight only the tag name? The screenshot is from a javascript file.

Looking at the plugin code, I found an option called `tagnameonly` but seems that doesn't work for javascript files.

**Comment by andymass** [comment]
This looks like an html file, not a javascript file.. https://github.com/Polymer/lit-element/blob/master/demo/lit-element.html
The following should work:

    let g:matchup_matchpref.html = {'tagnameonly': 1}

If it doesn't work, what is the output of `:set filetype?`

**Comment by jlesquembre** [comment]
You found the example I used, but I moved the javascript code to a js file. It looks like a html file, but is a javascript file, the html code is inside a template string. It's similar to JSX syntax, if you want to know more about it see https://polymer.github.io/lit-html/guide#lit-html-templates

You can see the same problem on this file: https://github.com/Polymer/lit-html/blob/master/demo/clock.js

![screenshot](https://user-images.githubusercontent.com/1058504/47316849-6547e500-d648-11e8-8cea-39a7b56e0441.png)

I have this on my vimrc:

```viml
let g:matchup_matchpref = {
    \ 'html': { 'tagnameonly': 1, },
    \ 'javascript':  { 'tagnameonly': 1, },
    \}
```

It looks like the `tagnameonly` option works for `html` but not for `javascript`. 

> If it doesn't work, what is the output of `:set filetype?`

filetype=javascript

**Comment by andymass** [comment]
Actually it seems to work correctly for me (in both html and javascript filetypes).  Are you using any external filetype plugin for javascript?  What is the output `:scriptnames`?

**Comment by jlesquembre** [comment]
Yes, I'm using https://github.com/MaxMEllon/vim-jsx-pretty and looks like that is the reason.

I found that if here: 
https://github.com/MaxMEllon/vim-jsx-pretty/blob/master/after/ftplugin/javascript.vim,
I replace it with (as you wrote in https://github.com/andymass/vim-matchup/issues/35#issuecomment-413307832)
```viml
setlocal matchpairs=(:),{:},[:],<:>
let b:match_words = '<\@<=\([^/][^ \t>]*\)\g{hlend}[^>]*\%(/\@<!>\|$\):<\@<=/\1>'
```
everything works as expected. I'm thinking about sending a PR to the vim-jsx-pretty project, with something like: 

```viml
if exists("loaded_matchup")
  let b:match_ignorecase = 0
  setlocal matchpairs=(:),{:},[:],<:>
  let b:match_words = '<\@<=\([^/][^ \t>]*\)\g{hlend}[^>]*\%(/\@<!>\|$\):<\@<=/\1>'
elseif exists("loaded_matchit")
  let b:match_ignorecase = 0
  let b:match_words = '(:),\[:\],{:},<:>,' .
        \ '<\@<=\([^/][^ \t>]*\)[^>]*\%(>\|$\):<\@<=/\1>'
endif
```

Do you think is makes sense or do you have a better solution?

**Comment by andymass** [comment]
Sorry for the delay.  I think currently it makes more sense to handle this locally using the hotfix feature.  Then you can personalize the highlight however you like.  For example, put this in your vimrc:

    function! JsxHotfix()
        setlocal matchpairs=(:),{:},[:],<:>
        let b:match_words = '<\@<=\([^/][^ \t>]*\)\g{hlend}[^>]*\%(/\@<!>\|$\):<\@<=/\1>'
    endfunction
    let g:matchup_hotfix_javascript = 'JsxHotfix'

**Comment by jlesquembre** [comment]
Don't worry for the delay, and thanks for the advice, I didn't know about the hotfix feature.

I did some tests and that works perfectly :-)

Thank you for the effort you put on matchup, it's really a great plugin, I think vim should replace matchin with matchup
