### ISSUE TITLE
Not working in cmdline-window

### ISSUE THREAD

**Issue by okeke8v** [andymass/vim-matchup#43]
### Explain the issue
I hove trouble with using `%` in command-line-window.  Is this in the specifications?
1. What vim version are you using? --  VIM 8.1.0500
2. Steps to reproduce -- See below
3. Expected behavior -- Jump to match pair
4. FYI, vim-matchup works fine in a normal window.

### How to reproduce the problem
1. start vim ` vim -u {PATH/TO/Minimal-vimrc} `.
1. type `q/` and enter the command-line-window.
1. type `i[]<Esc>` and try to jump with `%` .

### Minimal vimrc file

```vim
unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim
let g:loaded_matchit = 1
set rtp+={/PATH/TO/vim-matchup}
set packpath=
```

**Comment by andymass** [comment]
Thanks for the clear report!  Yes, it was an oversight.  Let me know if there are any issues.
