### ISSUE TITLE
Hotfix for combined filetype

### ISSUE THREAD

**Issue by bootleq** [andymass/vim-matchup#46]
Hi, similar to issue 42, I'm try to highlight only tagname in JSX file follow the `g:matchup_hotfix_javascript` solution https://github.com/andymass/vim-matchup/issues/42#issuecomment-437415565.

I can confirm it works except that my `&:filetype` is `javascript.jsx` (contains a dot `.`).
Read Vim help that `'filetype'` can contain dots, which  means several separated types, could we add support for this? Maybe detect dots and try each filetype's hotfix. Thank you very much.

**Comment by andymass** [comment]
Can you tell me which plugins you use for JavaScript and jsx?  And an example document?

**Comment by andymass** [comment]
The simplest fix is to allow the syntax `g:matchup_hotfix['javascript.jsx']`.

This allows the following:
```vim
function! JsxHotfix()
    echo 'JsxHotfix'
    setlocal matchpairs=(:),{:},[:],<:>
    let b:match_words = '<\@<=\([^/][^ \t>]*\)\g{hlend}[^>]*\%(/\@<!>\|$\):<\@<=/\1>'
endfunction
let g:matchup_hotfix = { 'javascript.jsx': 'JsxHotfix' }
```

Note that this should also work:
```vim
autocmd FileType javascript.jsx let b:matchup_hotfix = 'JsxHotfix'
```

**Comment by bootleq** [comment]
Thanks very much for your great work!
Just confirmed both solution works.
