### ISSUE TITLE
Conditional compilation #ifdef and splitting if() then statement over two lines

### ISSUE THREAD

**Issue by mirino23** [andymass/vim-matchup#51]
I was trying out the features **(a.1) jump between matching words** (command `%`) and **(a.2) jump to open and close words** (commands `[%` and `]%`) to jump, for example, from one `if` to the next `elseif`. However, I work with programs that contain `#ifdef` for conditional compilation. Also, sometimes `if() then` are split over two lines by means of the character `&`. In these cases, the commands `%`, `[%` or `]%` seem not to be working.
Here is an example:
```
program ifElseIfElseProg
implicit none

   integer :: a = 100
 
   if( a == 10 ) then
  
      a = a + 1
#ifdef three_d
		 + 3
#endif      
   
   else if( a == 20 )
&  then
      print*, "Value of a is 20" 
  
   else if( a == 30 ) then
   
      print*, "Value of a is 30" 
  
   else
   
      print*, "None of the values is matching" 
      
   end if
   
   print*, "exact value of a is ", a
 
end program ifElseIfElseProg
```

**Comment by andymass** [comment]
Can you tell me what language this is, and if you use any filetype plugins for it?

**Comment by mirino23** [comment]
The language is FORTRAN.
My .vimrc reads:

```
call plug#begin('~/.vim/plugged')
Plug 'andymass/vim-matchup'
call plug#end()
" Uncomment the following to have Vim jump to the last position when reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal! g'\"" | endif
endif
```

**Comment by andymass** [comment]
Thanks.  Note that I can't handle multi-line matches at the moment so "then" isn't highlighted.  Also I can't support every possible line continuation.
