### ISSUE TITLE
delim match hangs on file that has very long column

### ISSUE THREAD

**Issue by ZSaberLv0** [andymass/vim-matchup#53]
### Explain the issue

1. What vim version are you using?

    vim 8.1

2. Steps to reproduce

    1. supply a file that has:
        * few lines
        * very very long column
        * typically, `xxx.min.js` files
    2. move cursor to line end
    3. move cursor by `j` or `k`

3. Expected behavior

    cursor move freely

4. Observed behavior

    vim hangs on matchup's delim match, `ctrl-c` to break would result on:

    ```
    Error detected while processing function 2[3]..3[55]..matchup#delim#get_current[1]..<SNR>171_get_delim:
    line  107:
    Interrupted
    ```

### Minimal vimrc file

```vim
set synmaxcol=200

" match-up options go here
let g:matchup_matchparen_status_offscreen=0
let g:matchup_matchparen_pumvisible=0
let g:matchup_mappings_enabled=0
let g:matchup_text_obj_enabled=0
let g:matchup_matchparen_stopline=20
```

NOTE: `g:matchup_matchparen_deferred` would only delay the issue,
when it actually starts to match, vim still hangs on matching

**Comment by andymass** [comment]
Simplest thing was to add a check if the current column is greater than `synmaxcol`, and I added some other performance tweaks.  Hopefully this improves things.

**Comment by ZSaberLv0** [comment]
that did solve the issue, thanks
