### ISSUE TITLE
Wrong matching in vim files

### ISSUE THREAD

**Issue by bfrg** [andymass/vim-matchup#54]
`vim-matchup` finds wrong matching keyword in `vim` files.

Minimal example:
```vim
function! Foo(var, func)
    return a:func(a:var)
endfunction
```
Put the cursor on `endfunction`. The plugin will highlight `endfunction`, `return`, and `func` in the parentheses. I would have expected it to highlight the function declaration keyword `function` instead of `func`.
The following search pattern won't match `func` in parentheses: `fu\%[nction]\ze!\=\s\+\(s:\)\=\w\+\s*(`.

**Comment by andymass** [comment]
I forget why this wasn't done already.  Hopefully there are no side effects.

Added this case to the skip expression, which is simpler than adding to the func regex.

**Comment by bfrg** [comment]
Sorry to bother you again, here's another [Vim function](https://github.com/tpope/vim-scriptease/blob/master/autoload/scriptease.vim#L425-L436) where the match fails:
```vim
function! Foo(list, var)
  return sort(a:list, s:function('a:var'))
endfunction
```
Adding `vimUserFunc` to `b:match_skip` seems to work.

**Comment by andymass** [comment]
Thanks.  Added `vimUserFunc`.  I have to think more about how to handle the other case.

**Comment by andymass** [comment]
It actually looks like this is working out of the box now.
