### ISSUE TITLE
Hi, I would like to know what`s the theme of screen shot in markdown file?

### ISSUE THREAD

**Issue by alanding1989** [andymass/vim-matchup#55]
**Hi, would you please tell me what`s the theme of screen shot in markdown file?**

**Comment by andymass** [comment]
It is https://github.com/drewtempelmeyer/palenight.vim/ with `let g:palenight_terminal_italics = 1` and customized `MatchParen` highlight:

    autocmd ColorScheme palenight hi MatchParen cterm=italic gui=italic

**Comment by alanding1989** [comment]
> It is https://github.com/drewtempelmeyer/palenight.vim/ with `let g:palenight_terminal_italics = 1` and customized `MatchParen` highlight:
> 
> ```
> autocmd ColorScheme palenight hi MatchParen cterm=italic gui=italic
> ```

thank you man , I will try. :)
