### ISSUE TITLE
add support to customize the i key in i% motion

### ISSUE THREAD

**Issue by ri-aje** [andymass/vim-matchup#59]
### Explain the issue

allow to customize the `i` key in `i%` operator/text-object.

If your issue is instead a feature request or anything else, please
consider if minimal examples and vimrc files might still be relevant.

### Minimal working example

Please provide a minimal working example, e.g.,

```
function ()
{
 ...
}
```

when cursor is on the opening `{`, I would like to press `vu%` key sequence and have it functional as what `vi%` would normally do. similarly apply `u%` to all cases where `i%` is functional.

in case you wonder why I seem to ask for a weird feature. it's to work with non-querty keyboard layout, specifically for colemak layout which places the `i` key on the physical `u` key. usually I can accommodate the customization in vimrc if the text object support is done through https://github.com/kana/vim-textobj-user, but yours seems to be in house made, so I have to open a feature request. thanks.

### Minimal vimrc file

Please provide a minimal vimrc file that reproduces the issue. The
following should often suffice:

```vim
set nocompatible

  call plug#begin('~/.vim/bundle')
   Plug 'andymass/vim-matchup'
  call plug#end()
```

**Comment by andymass** [comment]
You should be able to do this with:

    xmap u% <plug>(matchup-i%)
    omap u% <plug>(matchup-i%)

If your vim is older than 8.1.0648 and you use forcing (i.e., `dvu%`, `dVu%`, etc) you can also include:

    call call(matchup#motion_sid().'make_oldstyle_omaps', ['u%', 'i%'])

**Comment by ri-aje** [comment]
the second example worked. thanks.
