### ISSUE TITLE
[feature] implement deferred highlighting

### ISSUE THREAD

**Issue by andymass** [andymass/vim-matchup#6]
Navigating with highlighting can sometimes be slow.  Deferred highlighting would improve cursor performance, while introducing a short delay to highlighting (for example 40 milliseconds seems reasonable).

This would introduce the following options
```vim
let g:matchup_matchparen_deferred = 0 / 1
let g:matchup_matchparen_deferred_show_delay = 40
let g:matchup_matchparen_deferred_hide_delay = 200
```

Only available if `has('timers')`.

cf #5.

**Comment by kiryph** [comment]
I've tried your branch `feature-deferred` with following settings:
```viml
let g:matchup_matchparen_deferred = 1
let g:matchup_matchparen_deferred_show_delay= 10
```

I like it. I think the default delay is too large. But I guess this is personal preference.

**Comment by andymass** [comment]
Thank you for testing.  This feature is in master now.  There should be no change to default behavior unless the user enables it explicitly.

I agree, the default was too large.  I made it 50 milliseconds, which seems acceptable to me and is more conservative than 10 in case the user has a slow key repeat.
