### ISSUE TITLE
Support for <:> in C++

### ISSUE THREAD

**Issue by bergercookie** [andymass/vim-matchup#60]
Hi,

I'm aware that the <:> matching is fully functional in languages like HTML. However, in languages like C++ where I have to explicitly set `set matchpairs+=<:>`, highlighting and `%`-jumping doens't seem to work.

Anything I'm missing?
How hard would it be to add support for this?

**Comment by andymass** [comment]
Where in your configuration are you setting `set matchpairs+=<:>`?

**Comment by bergercookie** [comment]
Oh, apologies.
I had set matchpairs but forgot to reload the plugin.

Works fine, closing this.
