### ISSUE TITLE
customized b:match_words doesn't cycle properly

### ISSUE THREAD

**Issue by ri-aje** [andymass/vim-matchup#61]
### Explain the issue

Most issues are related to bugs or problems. In these cases, you should
include a minimal working example and a minimal vimrc file (see below), as
well as:

1. What vim version are you using?
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
Included patches: 1-1453

2. Steps to reproduce
see bottom for min vimrc file. put these content in a ftl file, i.e., free marker file, e.g., `t.ftl`
```
<#if>
<#elseif>
<#else>
</#if>
```

use vim to open it and place cursor on `#if`. any char should be fine. observe the `#if-#elseif-#else-/#if` set is highlighted (this is correct and expected). then press `%` to navigate to the next match. keep pressing until the cursor reaches `/#if`. press `%` again and notice the cursor doesn't jump to the corresponding opening `#if`, i.e., the `%` won't result a jump cycle among matches.

3. Expected behavior
`%` cycles between `#if-#elseif-#else-/#if` tags.

4. Observed behavior
cursor eventually stops on `/#if` tag and unable to make further movement with `%`

### Minimal vimrc file

Please provide a minimal vimrc file that reproduces the issue. The
following should often suffice:

```vim
set nocompatible

  call plug#begin('~/.vim/bundle')
   Plug 'andymass/vim-matchup'
  call plug#end()

  let b:match_words='#if:#elseif:#else:/#if'
```

**Comment by andymass** [comment]
Since `#if` matches part of `/#if` you need to modify the regular expression to disambiguate, e.g.,

    let b:match_words='/\@<!#if:#elseif:#else:/#if'
