### ISSUE TITLE
Support maxmellon/vim-jsx-pretty?

### ISSUE THREAD

**Issue by davidsierradz** [andymass/vim-matchup#62]
### Explain the issue

Hi!, it seems that [mxw/vim-jsx](https://github.com/mxw/vim-jsx) is abandoned, I migrated to [MaxMEllon/vim-jsx-pretty](https://github.com/MaxMEllon/vim-jsx-pretty), I have this in my `init.vim`:

```vimscript
function! JsxHotfix()
  echo 'JsxHotfix'
  setlocal matchpairs=(:),{:},[:],<:>
  let b:match_words = '<\@<=\([^/][^ \t>]*\)\g{hlend}[^>]*\%(/\@<!>\|$\):<\@<=/\1>'
endfunction

autocmd FileType javascript let b:matchup_hotfix = 'JsxHotfix'
```

But the highlight and `%` doesnt seems to work.

Thanks for this awesome plugin!

**Comment by andymass** [comment]
The reason this doesn't work is the open `<` and close `>`  are showing up as comments:

    jsxOpenPunct   xxx links to jsxPunct
    jsxPunct       xxx links to jsxCloseString
    jsxCloseString xxx links to Comment

I'm not sure whether this is intentional or a bug in the syntax definitions of MaxMEllon/vim-jsx-pretty

**Comment by andymass** [comment]
FYI, a workaround in the mean-time is to define the skip expression manually instead of using the default one:

    function! JsxHotfix()
        setlocal matchpairs=(:),{:},[:],<:>
        let b:match_words = '<\@<=\([^/][^ \t>]*\)\g{hlend}[^>]*\%(/\@<!>\|$\):<\@<=/\1>'
        let b:match_skip = 's:comment\|string'
    endfunction

**Comment by davidsierradz** [comment]
Fixed in [https://github.com/MaxMEllon/vim-jsx-pretty/commit/007b85e1d51f4dbbba2c15ca4a34b5ff7a8db9ef](https://github.com/MaxMEllon/vim-jsx-pretty/commit/007b85e1d51f4dbbba2c15ca4a34b5ff7a8db9ef)

Thanks!
