### ISSUE TITLE
could not match C++ template < > pairs

### ISSUE THREAD

**Issue by huaihuaiVV** [andymass/vim-matchup#69]
typedef BOOST_DEDUCED_TYPENAME boost::conditional<
            boost::is_signed<no_cvr_prefinal_t>::value,
            boost::make_signed<no_cvr_prefinal_t>,
            boost::type_identity<no_cvr_prefinal_t>
        >::type no_cvr_prefinal_lazy_t;

can not natch the first < , after "conditional" word ,
ti think it is easy to detect it ,  if < coms after a word and don't have space around it , it should be a template operator , not a C language > <  >= <= compare operators ,
then we can match it to find the > symbol .

**Comment by andymass** [comment]
What about using this in your vimrc?

```vim
function! CppTemplate()
  call matchup#util#append_match_words(
        \ '\%(\s\@<!<\|<\s\@!\)=\@!:\%(\s\@<!>\|>\s\@!\)=\@!')
endfunction
if !exists('g:matchup_hotfix')
  let g:matchup_hotfix = {}
endif
let g:matchup_hotfix.cpp = 'CppTemplate'
set matchpairs-=<:>
```

**Comment by huaihuaiVV** [comment]
just try it ,

<img width="622" alt="image" src="https://user-images.githubusercontent.com/5601971/64094228-a5f6ab80-cd8d-11e9-87bf-a261dc4ed98f.png">

it worked ,

Thanks very much !

could this be add to  matchup CPP filetype script ?

**Comment by andymass** [comment]
You can use

    let g:matchup_matchpref = {'cpp': {'template': 1}}
