### ISSUE TITLE
[Bug] matchparen highlights one additional character in augroup XXX augroup END

### ISSUE THREAD

**Issue by kiryph** [andymass/vim-matchup#7]
See following screenshot:
![matchup](https://user-images.githubusercontent.com/371756/32847926-85939842-ca2b-11e7-8241-451e5e134a24.png)

**Comment by andymass** [comment]
Believe it or not, this is not a bug but is due to the definition of `b:match_words` in `ftplugin/vim.vim`.

Try the following (please do an update of the plugin first),

```vim
" file: test/issues/7/hotfix.vim
function! AugroupHotfix()
    call matchup#util#patch_match_words(
        \ '\<aug\%[roup]\s\+\%(END\>\)\@!\S:',
        \ '\<aug\%[roup]\s\+\%(END\>\)\@!\S\+:')
endfunction

let g:matchup_hotfix_vim = 'AugroupHotfix'
```

Equivalently, it could be patched to not show the augroup name.

Note: if you execute this after loading you must reload the test example using `:edit`.

**Comment by kiryph** [comment]
Thanks for clarifying this and considering this despite that is related to the definition in vimrc.

With your hotfix it looks now as following:
![untitled](https://user-images.githubusercontent.com/371756/32944864-5cb76f54-cb91-11e7-9af3-eb8310000c9f.png)

I guess I would prefer that only the matched words are highlighted. This seems to be more consistent compared to `if elseif` etc.

Since this actually not related to your plugin, I close this issue.

**Comment by andymass** [comment]
Thanks for testing.  Here is an example which does not highlight the name.

```vim
" file: test/issues/7/hotfix2.vim
function! AugroupHotfix()
    call matchup#util#patch_match_words(
        \ '\<aug\%[roup]\s\+\%(END\>\)\@!\S:',
        \ '\<aug\%[roup]\s\+\%(END\>\)\@!\S\@=:')
endfunction

let g:matchup_hotfix_vim = 'AugroupHotfix'
```

Note that the hotfix function is general and can be used for any filetype with `g:matchup_hotfix_{&filetype}`.
