### ISSUE TITLE
popup/floating-window behavior when window position changes, e.g. zz

### ISSUE THREAD

**Issue by jrudess** [andymass/vim-matchup#73]
### Explain the issue

1. neovim v0.4.0-1995-g158b78062
2. With the beginning match above the top view of the window, move the cursor to the end match, wait for the floating-window to appear below the cursor, then type zz
3. Unsure: Possibly close popup/floating-window immediately, or re-position it to be immediately below cursor again if cursor position moves.
4. After zz re-centers the cursor, the floating-window remains at its original 'y' position, but since the cursor has moved, it is out of position over random text.

The popup/floating-window behavior is different between vim and neovim.  With the minimal rc, the vim popup seems to always show up at the top line of the window, while in neovim the floating-window is immediately below the cursor.   This makes the current behavior not really an issue with vim, but in neovim it feels a little disorienting.

### Minimal vimrc file

Please provide a minimal vimrc file that reproduces the issue. The
following should often suffice:

```vim
set nocompatible

" load match-up
let &rtp  = '~/.vim/bundle/vim-matchup,' . &rtp
let &rtp .= ',~/.vim/bundle/vim-matchup/after'

" load other plugins, if necessary
" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable

let g:matchup_matchparen_offscreen = {
    \ 'method': 'popup',
    \ 'scrolloff': 1
    \ }
let g:matchup_matchparen_nomode = "ivV\<c-v>"
let g:matchup_matchparen_deferred = 1

```

**Comment by andymass** [comment]
I believe in vim it is possible to show a popup at the cursor which follows the text.  Is this not possible in neovim?  There is no great way to detect scrolling like with zz.  I went ahead and switched to the fixed strategy for neovim (like how it is in vim), planning an option for the "at cursor" strategy.

**Comment by andymass** [comment]
Thanks for the report.  

re 1892094
