### ISSUE TITLE
not working with macvim

### ISSUE THREAD

**Issue by cridemichel** [andymass/vim-matchup#74]
### Explain the issue

Most issues are related to bugs or problems. In these cases, you should
include a minimal working example and a minimal vimrc file (see below), as
well as:

1. What vim version are you using?

macvim 8.1.1722

2. Steps to reproduce

1) install matchup by vundle
2) create the following minimal .vimrc:
```vim
set nocompatible
let &runtimepath .= ',~/.vim/bundle/vim-matchup/'
filetype plugin indent on
syntax enable
```
3) open macvim and from command line open the following minimal tex file:
```latex  
\begin{document}
\end{document} 
``` 
4) I get following errors:
```text
Error detected while processing function matchup#loader#init_buffer[17]..matchup#perf#toc: 
line    9: 
E121: Undefined variable: s:alpha  
```
and matchup does not work, meaning that whatever thing I try to do (switching to insert mode,
editing the file) I get a lot of errors such as:

```text
Error detected while processing function 3[3]..4[62]..matchup#delim#get_current[1]..<SNR>45_get_delim[165]..matchup#perf#timeout_check: 
line    2:
E806: using Float as a String 
```

```text
Error detected while processing function 3[3]..4[62]..matchup#delim#get_current[1]..<SNR>45_get_delim[156]..matchup#perf#ti
line    2:
E121: Undefined variable: l:elapsed   
```

3. Expected behavior
4. Observed behavior

If your issue is instead a feature request or anything else, please
consider if minimal examples and vimrc files might still be relevant.

### Minimal working example

Please provide a minimal working example, e.g.,

```vim
if l:x == 1
  call one()
elseif l:x == 2
  call two()
else
  call three()
endif
```

### Minimal vimrc file

Please provide a minimal vimrc file that reproduces the issue. The
following should often suffice:

```vim
set nocompatible

" load match-up
let &rtp  = '~/.vim/bundle/vim-matchup,' . &rtp
let &rtp .= ',~/.vim/bundle/vim-matchup/after'

" load other plugins, if necessary
" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable

" match-up options go here
```

**Comment by andymass** [comment]
Can you try adding the after directory?  Like in the example?

**Comment by cridemichel** [comment]
> Can you try adding the after directory? Like in the example?

I have just done it and I get same errors...

**Comment by andymass** [comment]
Unfortunately I can't reproduce given the steps provided (on linux, since I don't have access to macvim).

Try:
     - using vundle in the normal way (not manipulating runtimepath)
     - reinstalling plugin completely

**Comment by cridemichel** [comment]
> Unfortunately I can't reproduce given the steps provided (on linux, since I don't have access to macvim).
> 
> Try:
> - using vundle in the normal way (not manipulating runtimepath)
> - reinstalling plugin completely

I tried already what you suggested without success, I think it is a specific issue of macvim, 
indeed I use vim from brew within the terminal it works as expected.
Hence, no chance to get it fixed?

**Comment by andymass** [comment]
> indeed I use vim from brew within the terminal it works as expected.

Can you tell me the exact `:version` for both the working vim and the non-working vim you have installed?

**Comment by cridemichel** [comment]
> > indeed I use vim from brew within the terminal it works as expected.
> 
> Can you tell me the exact `:version` for both the working vim and the non-working vim you have installed?

macvim  (not working) 

VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 28 2019 01:07:30)
macOS version
Included patches: 1-1722
Compiled by travis@Traviss-Mac.local
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +cursorshape       +job               +mouse_urxvt       +signs             +user_commands
+arabic            +dialog_con_gui    +jumplist          +mouse_xterm       +smartindent       +vartabs
+autocmd           +diff              +keymap            +multi_byte        -sound             +vertsplit
+autochdir         +digraphs          +lambda            +multi_lang        +spell             +virtualedit
-autoservername    +dnd               +langmap           -mzscheme          +startuptime       +visual
+balloon_eval      -ebcdic            +libcall           +netbeans_intg     +statusline        +visualextra
+balloon_eval_term +emacs_tags        +linebreak         +num64             -sun_workshop      +viminfo
+browse            +eval              +lispindent        +odbeditor         +syntax            +vreplace
++builtin_terms    +ex_extra          +listcmds          +packages          +tag_binary        +wildignore
+byte_offset       +extra_search      +localmap          +path_extra        -tag_old_static    +wildmenu
+channel           -farsi             +lua/dyn           +perl/dyn          -tag_any_white     +windows
+cindent           +file_in_path      +menu              +persistent_undo   -tcl               +writebackup
+clientserver      +find_in_path      +mksession         +postscript        +termguicolors     -X11
+clipboard         +float             +modify_fname      +printer           +terminal          -xfontset
+cmdline_compl     +folding           +mouse             +profile           +terminfo          +xim
+cmdline_hist      -footer            +mouseshape        +python/dyn        +termresponse      -xpm
+cmdline_info      +fork()            +mouse_dec         +python3/dyn       +textobjects       -xsmp
+comments          +fullscreen        -mouse_gpm         +quickfix          +textprop          -xterm_clipboard
+conceal           -gettext           -mouse_jsbterm     +reltime           +timers            -xterm_save
+cryptv            -hangul_input      +mouse_netterm     +rightleft         +title
+cscope            +iconv             +mouse_sgr         +ruby/dyn          +toolbar
+cursorbind        +insert_expand     -mouse_sysmouse    +scrollbind        +transparency
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework AppKit   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE

vim (from brew)

VIM - Vi IMproved 8.1 (2018 May 18, compilato Sep 18 2019 03:49:48)
Versione macOS
Patch incluse: 1-2050
Compilato da Homebrew
Versione gigante senza GUI.  Funzionalità incluse (+) o escluse (-):
+acl               +cmdline_info      -farsi             +libcall           -mouse_sysmouse    +python3           -tag_any_white     +visualextra
+arabic            +comments          +file_in_path      +linebreak         +mouse_urxvt       +quickfix          -tcl               +viminfo
+autocmd           +conceal           +find_in_path      +lispindent        +mouse_xterm       +reltime           +termguicolors     +vreplace
+autochdir         +cryptv            +float             +listcmds          +multi_byte        +rightleft         +terminal          +wildignore
-autoservername    +cscope            +folding           +localmap          +multi_lang        +ruby              +terminfo          +wildmenu
-balloon_eval      +cursorbind        -footer            +lua               -mzscheme          +scrollbind        +termresponse      +windows
+balloon_eval_term +cursorshape       +fork()            +menu              +netbeans_intg     +signs             +textobjects       +writebackup
-browse            +dialog_con        +gettext           +mksession         +num64             +smartindent       +textprop          -X11
++builtin_terms    +diff              -hangul_input      +modify_fname      +packages          -sound             +timers            -xfontset
+byte_offset       +digraphs          +iconv             +mouse             +path_extra        +spell             +title             -xim
+channel           -dnd               +insert_expand     -mouseshape        +perl              +startuptime       -toolbar           -xpm
+cindent           -ebcdic            +job               +mouse_dec         +persistent_undo   +statusline        +user_commands     -xsmp
-clientserver      +emacs_tags        +jumplist          -mouse_gpm         +postscript        -sun_workshop      +vartabs           -xterm_clipboard
+clipboard         +eval              +keymap            -mouse_jsbterm     +printer           +syntax            +vertsplit         -xterm_save
+cmdline_compl     +ex_extra          +lambda            +mouse_netterm     +profile           +tag_binary        +virtualedit
+cmdline_hist      +extra_search      +langmap           +mouse_sgr         -python            -tag_old_static    +visual
   file vimrc di sistema: "$VIM/vimrc"
       file vimrc utente: "$HOME/.vimrc"
    II file vimrc utente: "~/.vim/vimrc"
        file exrc utente: "$HOME/.exrc"
        file dei default: "$VIMRUNTIME/defaults.vim"
         $VIM di riserva: "/usr/local/share/vim"
Compilazione: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Link: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -lintl -framework AppKit  -L/usr/local/opt/lua/lib -llua5.3 -mmacosx-version-min=10.14 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.30.0/lib/perl5/5.30.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -framework CoreFoundation  -lruby.2.6

**Comment by cridemichel** [comment]
> > indeed I use vim from brew within the terminal it works as expected.
> 
> Can you tell me the exact `:version` for both the working vim and the non-working vim you have installed?

I think I have found the culprit. I am in italy hence my macosx sets language to it_IT.UTF-8,
hence the punctuation symbol is "," and not ".". This is causing the issue in the function
which is spawning error messages (matchup#perf#toc(context, state)).
The workaround which I found is to add the following two lines to my .vimrc:
```vim
set langmenu=en_US.UTF-8
language messages en_US.UTF-8
```
and now matchup works flawlessly. What do you think?

**Comment by andymass** [comment]
What is the output of `:lang` in macvim?

**Comment by cridemichel** [comment]
> What is the output of `:lang` in macvim?

without adding anything in .vimrc:

Current language: "it_IT"

**Comment by andymass** [comment]
Sorry, I meant the full output of :lang

**Comment by cridemichel** [comment]
that's the only output I've got...

**Comment by andymass** [comment]
Thanks.  Unfortunately, I can't do much to investigate and I think this needs to be raised on the macvim project.  That output is unexpected to me.

**Comment by cridemichel** [comment]
what do you get on you gvim from :lang?

**Comment by andymass** [comment]
> Current language: "LC_CTYPE=en_US.UTF-8;LC_NUMERIC=C;LC_TIME=en_US.UTF-8;LC_COLLATE=en_US.UTF-8;LC_MONETARY=en_US.UTF-8;LC_MESSAGES=en_US.UTF-8;LC_PAPER=en_US.UTF-8;LC_NAME=en_US.UTF-8;LC_ADDRESS=en_US.UTF-8;LC_TELEPHONE=en_US.UTF-8;LC_MEASUREMENT=en_US.UTF-8;LC_IDENTIFICATION=en_US.UTF-8"

**Comment by cridemichel** [comment]
but if I add the two lines posted above I get:
Current language: "it_IT/it_IT/it_IT/C/it_IT/en_US.UTF-8"
still different from yours...

**Comment by andymass** [comment]
Good that you found a working setup, thanks!
