### ISSUE TITLE
wrong matching in ruby

### ISSUE THREAD

**Issue by amerov** [andymass/vim-matchup#75]
reproduce: 
go to `do` keyword in line 1; press `%`
![Screenshot from 2019-10-08 02-14-21](https://user-images.githubusercontent.com/196747/66350339-7e8a9400-e974-11e9-9d4d-853138c564b2.png)

code sample:
```ruby
context 'webhooks' do
  before { allow_any_instance_of(described_class).to receive(:webhook_endpoint_active?).and_return(true) }

  it 'runs webhooks' do
    expect(Webhook::Runner).to receive(:deliver)
    subject
  end
end
```

**Comment by andymass** [comment]
What is your expectation here?

**Comment by amerov** [comment]
> What is your expectation here?

matching  line 1  `do` with line 2 `}` is wrong.
it should be match `do` with `end`
without plugin matching is ok.

**Comment by andymass** [comment]
Thanks for the report.  It should be fixed now.

**Comment by amerov** [comment]
Thanks!
It works.
