### ISSUE TITLE
offscreen match not displayed in popup window

### ISSUE THREAD

**Issue by lacygoill** [andymass/vim-matchup#79]
### Explain the issue

When match-up is configured to display an offscreen match in a popup window, sometimes the latter is not opened.

### Vim version

`8.1.2297`

### To reproduce

Write this in `/tmp/vim.vim`:

    if 1
      " some code
      " some code
      " some code
      " some code
      " some code
      " some code
      " some code
      " some code
      " some code
      " some code
      " some code
      " some code
      " some code
      " some code
      " some code
      " some code
      " some code
      " some code
      " some code
      " some code
      " some code
    endif

Then, write this in `/tmp/vimrc`:

    set rtp-=~/.vim
    set rtp-=~/.vim/after
    set rtp^=~/.vim/plugged/vim-matchup
    set rtp+=~/.vim/plugged/vim-matchup/after
    set lines=24

    filetype plugin on
    syn on
    let g:matchup_matchparen_offscreen = {'method': 'popup'}

Finally, start Vim with this shell command:

    vim -Nu /tmp/vimrc +'tabe /tmp/vim.vim'

### Expected behavior

The popup window is opened at the bottom of the screen to display the close word `endif` matching the open word `if` which is under the cursor.

### Observed behavior

The popup window is not opened.

![gif](https://user-images.githubusercontent.com/8505073/68774983-24918400-062e-11ea-9bcd-1c69a6f599ca.gif)

### Additional information

In Nvim (`0.5.0-156-gdb436d527`), the same command works as expected; i.e. the floating window is correctly opened to display `endif`.

**Comment by andymass** [comment]
Oh.. right... popups are local to tab.  Thanks for the clear report as always.

Can you test?

**Comment by lacygoill** [comment]
I've just tested the latest commit, and it fixes the issue entirely. Thank you very much for the quick fix.
