### ISSUE TITLE
popup window wrongly opened to display visible match when focusing window squashed to 0 lines

### ISSUE THREAD

**Issue by lacygoill** [andymass/vim-matchup#81]
**Explain the issue**

When focusing a window which is squashed to `0` lines, and the cursor is on an open/mid/close word, the popup window is opened to display a match, even if the latter is not offscreen.

**Vim version**

`8.1.2297`

**To reproduce**

Write this in `/tmp/file`:

    (some text inside parens)

And write this in `/tmp/vimrc`:

    set rtp-=~/.vim
    set rtp-=~/.vim/after
    set rtp^=~/.vim/plugged/vim-matchup
    set rtp+=~/.vim/plugged/vim-matchup/after

    let g:matchup_matchparen_offscreen = {'method': 'popup'}
    set wmh=0
    au VimEnter * au WinEnter * wincmd _
    sp

Then, start Vim with this shell command:

    vim -Nu /tmp/vimrc /tmp/file

Finally, press `C-w w` twice (or run `:wincmd w` twice).

**Expected behavior**

The popup window is not opened, because the matching closing parenthesis is already visible on the screen.

**Observed behavior**

The popup window is opened to display `(some text inside parens)`; presumably because the cursor is on the opening parenthesis, and `vim-matchup` considers that the matching closing parenthesis is offscreen.

![gif](https://user-images.githubusercontent.com/8505073/68842590-e4caab00-06c6-11ea-8e86-6bf32cf606be.gif)

**Additional information**

Nvim (`v0.5.0-157-g00dc12c5d`) is also affected by the issue.

---

The issue is not triggered if `'winminheight'` is set to a value greater than `0`.

It is not triggered either, if an offscreen match is displayed in the status line rather than in a popup window.

---

The position of the `WinEnter` autocmd (the one executing `wincmd _`) relative to the other autocmds seems to matter.
If it's installed  early, the issue is not triggered. This is why, in the previous minimal vimrc, I had to delay the installation of the autocmd with yet another autocmd listening to `VimEnter`.

I guess the issue is triggered when the autocmd is installed before this one: https://github.com/andymass/vim-matchup/blob/49d8cbc80c98cf0f030b9a3437965dbd94b369bf/autoload/matchup/matchparen.vim#L40

---

In practice, I'm affected by this issue because:

   - I set `'winminheight'` to `0`

   - I automatically squash the non-focused and non-special windows to `0` lines:
     https://github.com/lacygoill/vim-window/blob/3188b0bdb96f37569dd77514581cad4ae1483244/plugin/window.vim#L61
     https://github.com/lacygoill/vim-window/blob/3188b0bdb96f37569dd77514581cad4ae1483244/plugin/window.vim#L368

   - I install `vim-matchup` before `vim-window`

For the moment, I've fixed the issue by moving `vim-window` before `vim-matchup`.
However, I think this is brittle. What if I find another issue in the future which requires `vim-window` to be installed after? So, I thought the issue was worth being reported.

**Comment by lacygoill** [comment]
I'm not sure this is the right fix, but delaying the `WinEnter` autocmd installed by `vim-matchup` until the next `SafeState` seems to fix the issue.

Before:

    autocmd WinEnter * call s:matchparen.highlight(1)

After:

    autocmd WinEnter * au SafeState * ++once call s:matchparen.highlight(1)

**Comment by lacygoill** [comment]
I've just noticed that you don't even need the autocmd to trigger the issue.
You can also reproduce with the same text file as before, and this minimal vimrc (identical to the one in the OP minus the autocmd):

    set rtp-=~/.vim
    set rtp-=~/.vim/after
    set rtp^=~/.vim/plugged/vim-matchup
    set rtp+=~/.vim/plugged/vim-matchup/after

    let g:matchup_matchparen_offscreen = {'method': 'popup'}
    set wmh=0
    sp

Then, run:

    :wincmd w | wincmd _ | wincmd w

**Comment by andymass** [comment]
I am convinced the fact that the popup appears in the center of the window is some vim bug.  But regardless, the popup shouldn't be shown for 0 or 1 height windows, adding a check of which is the simplest solution.
