### ISSUE TITLE
Parens in strings being matched

### ISSUE THREAD

**Issue by ds26gte** [andymass/vim-matchup#82]
In this Lispy language fragment, syntax is appropriately set so that anything after `;` on a line is a comment, and strings are double-quote-delimited.

```
(define procname ; ) in comment isn't matched as expected
  ") in string is however matched"
  body)
```

`vim-matchup` correctly skips the `)` in the comment but not in the string. Any suggestions? Is this a config issue?

These are my settings

```
let matchup_matchparen_offscreen = {}
let matchup_delim_noskips = 2
```

**Comment by ds26gte** [comment]
p.s. Seems to happen only if the `string` highlight group was defined as link to another group. I was able to circumvent the problem by having defining `string` from scratch.

**Comment by andymass** [comment]
What filetype is this?  Do you have a fully reproducible example?

**Comment by ds26gte** [comment]
The filetype is `scheme`. To reproduce, either install no colorscheme or install `colorscheme default`, install `vim-matchup` as a package, and start neovim. Edit a file `j.scm`, which contains the contents above, i.e.,
```
(define procname ; ) in comment isn't matched as expected
  ") in string is however matched"
  body)
```

No or default colorscheme uses a link for the syntax group `string`: so the paren matching will fail.

Now, perform the ex command

`:hi string guibg=none guifg=green`

(Or put this in a vim file in `~/.config/nvim/plugin` and reopen neovim.)

The parens will now match correctly.

This may be the only acceptable solution -- i.e., having the user ensure that `string` is assigned its own colors and not linked to another group. So I'm willing to consider the issue solved.
