### ISSUE TITLE
Error in matching in LaTeX

### ISSUE THREAD

**Issue by lervag** [andymass/vim-matchup#84]
Given the following tex snippet:

```tex
\[
\begin{gathered}
First equation \\
Second equation \\[1ex]
Third and last equation
\end{gathered}
\]
```

With the following matchup options:

```vim
let g:matchup_matchparen_status_offscreen = 0
let g:matchup_override_vimtex = 1
```

The matching fails because of the leading backslash on line 4. I was made aware of this issue for vimtex and fixed it in [1f5cef6b](https://github.com/lervag/vimtex/commit/1f5cef6b03814274381e7ece0e23773fa9bda4df).

Let me know if you want/need more details.

**Comment by andymass** [comment]
Thanks!  I think I addressed this in a different way.  I might have missed some corner case.

**Comment by lervag** [comment]
Great, thanks! I'll let you know if I notice a similar issue (I probably won't because I never noticed the original one myself until i was made aware).
