### ISSUE TITLE
Janet multiline strings

### ISSUE THREAD

**Issue by rncar** [andymass/vim-matchup#85]
Hi, this is my first comment in vim-matchup repository, thank you for this awesome plugin.

Would be great to add the multiline strings of Janet (https://janet-lang.org).

For long strings where you don't want to type a lot of escape characters,
you can use 1 or more backticks (`) to delimit a string.
To close this string, simply repeat the opening sequence of backticks

An example:
```
``
This is a string.
Line 2
    Indented
"We can just type quotes here", and backslashes \ no problem.
``
```

Ref: https://janet-lang.org/docs/strings.html

**Comment by andymass** [comment]
Does Janet have a file type plugin?

**Comment by rncar** [comment]
https://github.com/janet-lang/janet.vim
