### ISSUE TITLE
vim-matchup causes Vim to throw an error when a terminal buffer is displayed in a popup window

### ISSUE THREAD

**Issue by bfrg** [andymass/vim-matchup#87]
### Explain the issue

vim-matchup causes Vim to throw an error when a terminal buffer is displayed in a popup window. 
Since version `8.2.0214` a popup window can't be made hidden anymore when it displays a terminal buffer.

**What Vim version are you using?**
Vim version `8.2.0309`

**Steps to reproduce**
Open a terminal buffer in a popup window:
```vim
call popup_create(term_start(&shell, #{term_finish: 'close', hidden: 1}), #{
        \ minwidth: 70,
        \ minheight: 20
        \ })
```

The command opens the popup window but prints the following error:
```
Error detected while processing function 4[31]..2[14]..1:
line    9:
E863: Not allowed for a terminal in a popup window
```
The error is caused by a call of `popup_hide()`:
https://github.com/andymass/vim-matchup/blob/5822783911ad760727592609e4c3db3ee222f39a/autoload/matchup/matchparen.vim#L141-L145

The window type needs to be checked first before calling `popup_hide()`. The following patch seems to work. Note: `win_gettype()` was added in version `8.2.0257`:
```diff
diff --git a/autoload/matchup/matchparen.vim b/autoload/matchup/matchparen.vim
index a87e76b..4bec308 100644
--- a/autoload/matchup/matchparen.vim
+++ b/autoload/matchup/matchparen.vim
@@ -138,7 +138,7 @@ function! s:matchparen.clear() abort dict " {{{1
     unlet! w:matchup_match_id_list
   endif
 
-  if exists('t:match_popup')
+  if exists('t:match_popup') && win_gettype() !=# 'popup'
     call popup_hide(t:match_popup)
   elseif has('nvim')
     call s:close_floating_win()
```

### Minimal vimrc file

```vim
set nocompatible

" load match-up
let &rtp  = '~/.vim/bundle/vim-matchup,' . &rtp
let &rtp .= ',~/.vim/bundle/vim-matchup/after'

filetype plugin indent on
syntax enable
```

**Comment by andymass** [comment]
If you don't hide the pop-up doesn't it stay visible incorrectly?

**Comment by bfrg** [comment]
Which popup window do you mean? If you're talking about the popup window displaying the off-screen match, it is properly closed before opening the terminal popup window.

**Comment by andymass** [comment]
Got it thanks.  I thought the failure mode was hovering over a ( _inside_ a terminal popup which created another terminal popup.

**Comment by andymass** [comment]
Actually, I am still confused about it.  `popup_hide(t:match_popup)` always intends to hide the off-screen match popup which is stored in `t:match_popup`.  It can never attempt to close the terminal-containing pop-up.  So the problem must be not that terminal popups cannot be hidden, but _any_ popup cannot be hidden from when the current window happens to be a terminal window.  Am I missing something?

**Comment by bfrg** [comment]
>  So the problem must be not that terminal popups cannot be hidden, but any popup cannot be hidden from when the current window happens to be a terminal popup window.

I think that's correct.

**Comment by bfrg** [comment]
Thanks for the fix. Feel free to close this issue.

**Comment by andymass** [comment]
Thanks for the good report.

I do think there's a bug in vim here but we can close this.  Feel free to open another if there are still problems.
