### ISSUE TITLE
matchup causes bad behaviour with block selection

### ISSUE THREAD

**Issue by idbrii** [andymass/vim-matchup#88]
### Explain the issue

matchup changes the behaviour of `$` during visual block selection if the cursor would land on a match-able paren. Using `$` should mean "select to end of line on all lines in block", but this behaviour changes it to "select to end of current line and same cursor column in block".

### Minimal working example

Given this .cs file:
```
this is some longer text
short {0}
```

Do commands:
`:exec "norm! gg\<C-v>G$"`

Without matchup installed, the whole block is selected.

With matchup installed, the "longer text" part is not selected. Like the cursor was moved to the end of line instead of using $.

Using matchup f5a677065c11972952f512473070a6e508a2660f.

I normally have `let g:matchup_matchparen_deferred = 1` so I noticed this as a flicker: the whole block would be selected, then selection would jump back to partial. Issue still occurs without defining this option.

Issue does not occur if I remove the `{0}` from the example text. Or even just add a letter after the `{0}` so the last character isn't a `}`.

### Minimal vimrc file

```
> type .vimrc
set hlsearch
colorscheme desert

> dir /b vimfiles\pack\bundle\start\
matchup
sensible

> gvim c:/bug.cs

:exec "norm! gg\<C-v>G$"
```

**Comment by andymass** [comment]
Thanks!  I think I know why this happens.   Meanwhile, a work-around is

     let g:matchup_matchparen_nomode="\<c-v>"

**Comment by andymass** [comment]
Should be OK now.  Let me know if there are any side issues.
