### ISSUE TITLE
:%bwipeout command causes the "E937: Attempt to delete a buffer that is in use: [NULL]" error

### ISSUE THREAD

**Issue by astyagun** [andymass/vim-matchup#89]
### Explain the issue

1. What vim version are you using? - MacVim

        VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 30 2019 11:57:56)
        macOS version
        Included patches: 1-2234

2. Steps to reproduce
    1. Call the `:%bw` command
3. Expected behavior
    1. No error is shown
4. Observed behavior
    1. There's an error: `E937: Attempt to delete a buffer that is in use: [NULL]`

**Comment by andymass** [comment]
I see the problem thanks.  

Are you using any particular configs/options?

Do any other plugins which use popups have this issue?

**Comment by astyagun** [comment]
This is the config: https://github.com/astyagun/.vim

I've tried commenting out everything in the config. And the only line, that seems to affect the presence of the error, is this line:

https://github.com/astyagun/.vim/blob/723a7064b1d2f279a834e4209495a7a267caf740/config/plug.vim#L43

When the line is uncommented, there is an error, when commented out - there's no error.

**Comment by astyagun** [comment]
I don't customize the plugin behavior with any of its options

**Comment by andymass** [comment]
Got it, thanks.  I feel that this is a vim bug, but I can make a workaround for your config.

If you use the pop-up feature in match-up then I'm not sure if it can be fixed at the moment.  Have to experiment a bit.

**Comment by astyagun** [comment]
If you mean the `let g:matchup_matchparen_offscreen = #{method: 'popup'}`, then I've just found out about this feature 🙂 Not using it currently, since it's not the default.

**Comment by andymass** [comment]
I think this is fixed upstream https://github.com/vim/vim/commit/7b4f76c0300f0bd9bf54ca1968fe9ae5e4dbdef4
