### ISSUE TITLE
The tag's attributes in HTML and XML are colored aswell

### ISSUE THREAD

**Issue by mectos** [andymass/vim-matchup#90]
![Screenshot from 2020-03-02 21-26-35](https://user-images.githubusercontent.com/44240685/75710351-1c3c8200-5ccd-11ea-9e3a-13299f1b8422.png)

Hello,
The problem as you can see, that the attributes are colored as well.
Another thing is that I dunno where did that blue color came from, It shows up only in tags though (parenthesis, brackets, they are all fine)

Thank you in advance for your time!

**Comment by andymass** [comment]
Does this comment resolve?  https://github.com/andymass/vim-matchup/issues/30#issuecomment-408408477

Regarding the other issues please give a reproducible example.

**Comment by mectos** [comment]
Yo man thanks for responding so fast.
Ah yes actually, but it resolves only when the file is an HTML, when it's a JS file, with JSX syntax (XML inside JS), it doesn't work perfectly. still like in the picture.

which kind of example? I can show you this section in my .vimrc, this blue color comes from nowhere actually.
```
Plug 'andymass/vim-matchup'
let g:matchup_matchpref = {}
let g:matchup_matchpref.html = {'tagnameonly': 1}
let g:matchup_matchparen_deferred = 1
let g:matchup_matchparen_hi_surround_always = 1
let b:match_words = 1
augroup matchup_matchparen_highlight
      autocmd!
      autocmd ColorScheme * hi MatchParen guifg=#f6f3e8 guibg=#857b6f gui=none
      autocmd ColorScheme * hi MatchParenCur guifg=#f6f3e8 guibg=#857b6f gui=none
augroup END
let g:loaded_matchit = 1
```
As you can, no blue color is mentioned here :(

**Comment by andymass** [comment]
I see in the picture the cursor is not where the blue is, it is on Hom[e].  Why is this?

By reproducible example I mean a minimal vimrc and a sample jsx file which demonstrates the problem.  You might have some other plugins which are causing problems.

**Comment by mectos** [comment]
Regarding the first question, I activated the option that the parenthesis/tags/brackets etc. will be highlighted when cursor between them (only the innermost)

[vimrc.txt](https://github.com/andymass/vim-matchup/files/4301462/vimrc.txt)
Attached the .vimrc :)

and about the sample jsx file, you want more than the picture I attached in the first post?

**Comment by andymass** [comment]
I finally got a chance to look into this.  The blue is defined by your colorscheme here: https://github.com/arzg/vim-colors-xcode/blob/713b9c3952441b11c5e0995593d48b7fc807bab7/colors/xcodewwdc.vim#L67

Parentheses and angle brackets are highlighted according to MatchParen/MatchParenCur while longer strings like html tags are highlighted with MatchWord.  You can override it similarly to the other highlights:

    augroup matchup_matchparen_highlight
        autocmd!
        autocmd ColorScheme * hi MatchParen guifg=#f6f3e8 guibg=#857b6f gui=none
        autocmd ColorScheme * hi MatchParenCur guifg=#f6f3e8 guibg=#857b6f gui=none
        autocmd ColorScheme * hi MatchWord guifg=#f6f3e8 guibg=#857b6f gui=none
    augroup END

**Comment by mectos** [comment]
Thanks man, exactly what I needed! <3
