### ISSUE TITLE
neovim match paren offscreen is affected by winminheight

### ISSUE THREAD

**Issue by habamax** [andymass/vim-matchup#91]
### Explain the issue
When you have popup method enabled it shows too much

1. What vim version are you using? **neovim nightly: NVIM v0.5.0-330-g71ee46acc**
2. Steps to reproduce **well, function that goes offscreen, place cursor on func or endfunc** 
3. Expected behavior **same as in vim?**
4. Observed behavior

![vim-matchup-neovim](https://user-images.githubusercontent.com/234774/76936154-795a4980-6903-11ea-90fe-8b36fd09975c.gif)

```vim
""" vim-matchup {{{1
let g:loaded_matchit = 1
let g:matchup_matchparen_offscreen = {'method': 'popup'}
let g:matchup_surround_enabled = 1
let g:matchup_enabled = 1
```

PS, sorry I didn't follow the guidance written in template. Feel free to close the issue.

**Comment by andymass** [comment]
Was it always this way or just recently?

**Comment by habamax** [comment]
> Was it always this way or just recently?

I am not really sure about it.

**Comment by habamax** [comment]
If you can tell me the sha of the commit I can use to bisect I can try to do it

**Comment by andymass** [comment]
Sorry, I meant with older neovim versions.

**Comment by habamax** [comment]
> 
> 
> Sorry, I meant with older neovim versions.

I don't remember, but I can install stable and check it out

**Comment by habamax** [comment]
I also tried to put some debug messages:

![image](https://user-images.githubusercontent.com/234774/76969331-4cc22400-693b-11ea-841d-ae8bfdd1e033.png)

![image](https://user-images.githubusercontent.com/234774/76969453-724f2d80-693b-11ea-90a0-36609091a17b.png)

**Comment by habamax** [comment]
> Sorry, I meant with older neovim versions.

Just checked -- all the same

**Comment by habamax** [comment]
Okay, I find the root cause...

I have `set winminheight=5` and in vim popups are not real windows and are not affected by the option.

It is global, so I am not sure if you should do smth about it, maybe a note in a documentation?

**Comment by andymass** [comment]
Thanks, that solves it.  We will probably just need to nvim_win_set_option( ... 'winminheight', 1) to fix it

**Comment by habamax** [comment]
> 
> 
> Thanks, that solves it. We will probably just need to nvim_win_set_option( ... 'winminheight', 1) to fix it

It would be nice!

**Comment by andymass** [comment]
Actually, winminheight is a global variable, so there's nothing I can do here.  In a way, neovim is doing exactly what you asked, it won't allow the window to become less than winminheight in height.

Please raise an issue with neovim.  I think floating windows should not be restricted to be at least winminheight.

**Comment by habamax** [comment]
> Actually, winminheight is a global variable, so there's nothing I can do here. 

That was my comment, indeed. Not sure if save/restore winminheight on show/hide match popup would be robust so I guess, there is nothing you can do.

> Please raise an issue with neovim. I think floating windows should not be restricted to be at least winminheight.

Well, let's agree on "this is not a bug but a feature" and close this issue.

**Comment by andymass** [comment]
Thanks!  You did point out the global issue, I just missed it somehow.

> Not sure if save/restore winminheight on show/hide match popup would be robust so I guess, there is nothing you can do.

This actually works!  And it seems robust enough to me.  Just pushed a fix, let me know if there are any issues.

**Comment by habamax** [comment]
Thank you, works like a charm!
