### ISSUE TITLE
Adding custom paris possible? Specifically < >

### ISSUE THREAD

**Issue by dseeni** [andymass/vim-matchup#92]
Hey Andy, 

This is a very neat plugin.. 
Is it possible to register Custom Pairs such as '<' : '>'??
I'd like to use that as I write vim script.. seems like it would be handy. 

Thanks.

**Comment by andymass** [comment]
Yes- You can configure this in your vimrc for filetypes:

    autocmd FileType vim setlocal matchpairs+=<:>

or 

    autocmd FileType vim let b:match_words += '<:>'

**Comment by dseeni** [comment]
![image](https://user-images.githubusercontent.com/6591429/78964638-bb644e80-7aaf-11ea-9e2d-9cca1d911eca.png)

This works! Thanks a bunch, bit new to vim, so I wasn't sure if I got it working. Looks like mps is the same as your reply I think?

**Comment by andymass** [comment]
Yes, using mps is also valid.  Generally it should work to use `set mps+<:>` globally but be aware that it is possible for a filetype to override the setting.
