### ISSUE TITLE
Highlight popup

### ISSUE THREAD

**Issue by habamax** [andymass/vim-matchup#93]
Is there a way to setup highlighting which is in popup?

![image](https://user-images.githubusercontent.com/234774/78555440-b2f0e700-7815-11ea-93d0-31d857ced6dd.png)

Couldn't find it in help file

**Comment by andymass** [comment]
Do you want to display the syntax colors of the language, or just configure the color of the popup window?

**Comment by habamax** [comment]
Color of pop-up window

**Comment by andymass** [comment]
Should be possible now:

```
      let g:matchup_matchparen_offscreen
          \ = {'method': 'popup', 'highlight': 'OffscreenPopup'}
      highlight! OffscreenPopup guibg=red guifg=blue
```

**Comment by habamax** [comment]
Thx! I was thinking it doesn't work... and it doesn't for nvim :)

For vim it works as expected, thank you very much!

**Comment by habamax** [comment]
Probably winhighlight should be used?

Somewhere around this?

https://github.com/andymass/vim-matchup/blob/189bbb1453b18827430c41d293c436cc6effdbbd/autoload/matchup/matchparen.vim#L620

```
let &l:winhighlight = "Normal:".get(g:matchup_matchparen_offscreen, 'highlight', 'Pmenu')
```

**Comment by habamax** [comment]
This works:

```
    call nvim_win_set_option(s:float_id,
          \ 'winhighlight',
          \ 'Normal:'.get(g:matchup_matchparen_offscreen, 'highlight', 'Pmenu'))
```

adding right after `nvim_open_win`

The only thing is that guifg has no effect -- syntax highlighting is not cleared:

![image](https://user-images.githubusercontent.com/234774/78675091-42b59480-78ed-11ea-9db4-0af50d3d44fd.png)

**Comment by andymass** [comment]
In neovim, the highlighting is based on the actual language syntax highlighting.  It is more obvious if the top part is off-screen.  Hence, with winhighlight we can configure the floating window's background but not the foreground.

**Comment by habamax** [comment]
Yep, thx!
