### ISSUE TITLE
Hit % does not work on underscore.js library

### ISSUE THREAD

**Issue by feliperama** [andymass/vim-matchup#95]
### Explain the issue

Hi, for some reason, the plugin doesn't work with this library:
https://underscorejs.org/underscore.js

However, testing with a simple file that I created myself it seems to be working. I will attached the logs when working (a simple javascript file) and when dont work (with underscore.js)
[bug_verbose.log](https://github.com/andymass/vim-matchup/files/4602541/bug_verbose.log)
[nobug_verbose.log](https://github.com/andymass/vim-matchup/files/4602542/nobug_verbose.log)

1. What vim version are you using?
neovim v0.4.3
2. Steps to reproduce
- Download the underscore.js somewhere
- Open at neovim
- hit % 
3. Expected behavior
- Goes to to the last ')' at the end of the file
4. Observed behavior
- you will see that the cursor doesn't move.

**Comment by andymass** [comment]
Hi.  I think you just need to increase the number of lines match-up looks ahead when typing `%`, e.g.,

    let g:matchup_delim_stopline=2000

in your vimrc.
