### ISSUE TITLE
Highlighting and % do not always work for vim9script :def functions

### ISSUE THREAD

**Issue by bfrg** [andymass/vim-matchup#96]
### Explain the issue

vim-matchup does not work very well with `vim9script` functions. Neither pressing `%` nor highlighting work when the cursor is put on a `return` inside a `:def` function.

When the cursor is put `def` or `enddef`, pressing `%` will jump to the next pair. But when the cursor is on `return`, the highlighting will disappear and pressing `%` (or `g%`) doesn't work anymore (see also screenshots below).

### Minimal working example

```vim
vim9script

def Foo(n: number): number
    return 200 * n + 12345
enddef
```

### Screenshots

![out](https://user-images.githubusercontent.com/6266600/84710931-7d7b1f00-af65-11ea-9876-ce36ffd64857.png)
From **left** to **right**: cursor is on `def`, `return` and `enddef`, respectively.

### Environment
Vim version `8.2.983`

**Comment by andymass** [comment]
I think the b:match_words shipped by vim is defective. (https://github.com/vim/vim/blob/c70222d12a2f8552273c0de48a3bf7138d649175/runtime/ftplugin/vim.vim#L85)

Should be maybe

```vim
  let b:match_words =
	\ '\<fu\%[nction]\>\|\<def\>:\<retu\%[rn]\>:\<endf\%[unction]\>\|\<enddef\>,' .
 	\ '\<\(wh\%[ile]\|for\)\>:\<brea\%[k]\>:\<con\%[tinue]\>:\<end\(w\%[hile]\|fo\%[r]\)\>,' .
	\ '\<if\>:\<el\%[seif]\>:\<en\%[dif]\>,' .
	\ '{:},' .
	\ '\<try\>:\<cat\%[ch]\>:\<fina\%[lly]\>:\<endt\%[ry]\>,' .
	\ '\<aug\%[roup]\s\+\%(END\>\)\@!\S:\<aug\%[roup]\s\+END\>,'
```

**Comment by bfrg** [comment]
Yes, your updated `b:match_words` works fine.

**Comment by andymass** [comment]
@bfrg thanks for checking.  I suspect matchit is broken too, then.  Would you mind raising to vim? 
 Bram is the maintainer so it can be done via issue.  Otherwise, I can when I get some time.

**Comment by andymass** [comment]
Thank you!  Closing as fixed upstream.
