### ISSUE TITLE
[Feature request] keepjumps

### ISSUE THREAD

**Issue by beardedsakimonkey** [andymass/vim-matchup#99]
Hi, in my vimrc i have something to this effect:
```
noremap % :keepjumps normal! %<cr>
```

It would be nice to be able to use `<plug>(matchup-%)` while keeping jumps.

Thanks

**Comment by andymass** [comment]
Added option `let g:matchup_motion_keepjumps = 1`.  Let me know if it works for you.

**Comment by beardedsakimonkey** [comment]
seems to be working well, thanks!
